### ISSUE TITLE
fixImageXml.py conflict

### ISSUE THREAD

**Issue by piyushrpt** [isce-framework/isce2#108]
@yunjunz and @CunrenLiang 

There is a potential conflict introduced by the two latest PRs in the default settings for fixImageXml.py .

The default value for using fullpath has always been "False" and that has been changed to "True". @yunjunz - do you see issues with flipping this back to original behavior?

**Comment by CunrenLiang** [comment]
If we use "action='store_false'" for both options, it does not work, but if we use "action='store_true'" for both options, it works as original version. Anyway I think the original version of fixImageXml.py is more explicit.

**Comment by piyushrpt** [comment]
@CunrenLiang lets leave the current version as is but moving forward we should replace all system calls with calls to the main function. This will make workflows too susceptible to changes in default arguments of executables.

**Comment by piyushrpt** [comment]
I have issued a PR #109 that includes this fix

**Comment by CunrenLiang** [comment]
@piyushrpt Yes, thanks for the suggestions.

**Comment by CunrenLiang** [comment]
by the way, currently all system calls create a isce.log file. For example, every time mdx.py is used to view an image, it creates a isce.log file. We usually use it to check results in different places, then it would create a bunch of useless log files.

**Comment by yunjunz** [comment]
@piyushrpt your fix looks good to me. I don't see any issues with flipping back to the original behavior.

**Comment by piyushrpt** [comment]
The default logging sets can be found under defaults/logging/logging.conf . Unfortunately, historically a filehandler was always attached. If a simple way can be figured out to activate the filehandler only for the app.py files that would solve the issue ... need to look into it

**Comment by piyushrpt** [comment]
Fixed by #109

**Comment by EJFielding** [comment]
The way that `mdx.py` wants to create an `isce.log` file is especially annoying when we want to display an ISCE image in a directory owned by someone else where we don't have write permission.
