### ISSUE TITLE
topsStack processing metadata changed?

### ISSUE THREAD

**Issue by EJFielding** [isce-framework/isce2#131]
I have a stack of Sentinel-1 data that I was processing with the topsStack workflow a few months ago, and I tried to update it today with some new data. In the meantime, I had also updated my version of ISCE2 to v. 2.3.3 and I think some additional updates last month.

I am getting an error at the baseline step:
```
Running: computeBaseline
['--baseline_file', '/u/sar-r2/fielding/Puerto_Rico/S1AB/A135/seismic/baselines/20191223_20200316/2
0191223_20200316.txt', '--master', '/u/sar-r2/fielding/Puerto_Rico/S1AB/A135/seismic/master/', '--s
lave', '/u/sar-r2/fielding/Puerto_Rico/S1AB/A135/seismic/slaves/20200316']
2020-05-06 19:50:54,870 - isce.burstslc - ERROR - Error. The attribute corresponding to the key "az
imuthprocessingbandwidth" is not present in the object "<class 'isceobj.Sensor.TOPS.BurstSLC.BurstS
LC'>".
Possible causes are the definition in the xml file of such attribute that is no longer defined
in the object "<class 'isceobj.Sensor.TOPS.BurstSLC.BurstSLC'>" or a spelling error
Completed Parsing the Configuration file
Functions to be executed:
['Function-1']
```

Has the metadata for the TOPS processing changed in the last few months?

Do I have to discard the whole stack and restart processing from the beginning?

**Comment by piyushrpt** [comment]
This metadata field has been available ever since we went first on github. You might be using a really old version of isce in some part of your toolchain.

**Comment by EJFielding** [comment]
Thanks for the quick reply. I found that I had accidentally activated an old ISCE2 module. I need to remove that old version from my system.
