### ISSUE TITLE
Build-deploy docker failing due to alpine changes

### ISSUE THREAD

**Issue by piyushrpt** [isce-framework/isce2#144]
The automated docker build from last PR merge failed possibly due to these new changes

See - https://dev.to/gustavorglima/how-to-solve-error-unsatisfiable-constraints-python-48k7

**Comment by piyushrpt** [comment]
@pymonger - Looks like docker/Dockerfile is broken due to hysds:pge-latest changes now. Are there other changes that are needed?

**Comment by rtburns-jpl** [comment]
If you're talking about the latest merge failure in circleci, I think that's RHEL 7 gem being too old. Yang was able to fix our profiler image by installing from RVM, maybe that's a possibility?
```bash
command curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
curl -L get.rvm.io | bash -s stable
source /home/conda/.rvm/scripts/rvm
sudo /home/conda/.rvm/bin/rvm install 2.3.0
export PATH=/home/conda/.rvm/gems/ruby-2.3.0/bin:/home/conda/.rvm/gems/ruby-2.3.0@global/wrappers/:$PATH
sudo gem install --no-ri --no-rdoc fpm 
```
