### ISSUE TITLE
runDispersive segmentation fault

### ISSUE THREAD

**Issue by vbrancat** [isce-framework/isce2#164]
I am running stripmapApp.py on a pair of UAVSAR NISAR sample products over the San Andreas Valley, CA, USA.
The processing chain runs smoothly until the ionospheric phase estimation step where it fails trying to apply the low-pass Gaussian filter.
Particularly, I am getting a "Segmentation Fault" when trying to execute cv2.Filter2D. I have checked the input data and the kernel and the look ok considering the pair of SLC being processed. I suspect the issue is related to opencv.

I am using the latest ISCE2 conda installation and opencv 3.4.7

Thanks a lot for your help!

**Comment by piyushrpt** [comment]
Are you able to run cv2.Filter2D on a simple numpy matrix all by itself?

**Comment by vbrancat** [comment]
Yes. It seems that the issue is solved by installing the newest version of opencv (4.3)

**Comment by piyushrpt** [comment]
That is interesting. This might be a conflict since autoRIFT explicitly needs opencv 3.x for its bindings. Looks like we only need the python interface for ionosphere estimation. I'm seeing some issues with opencv 3.x in general on couple of platforms. Hopeffully, they fix it soon.

**Comment by rtburns-jpl** [comment]
That's too bad, why is it incompatible with v4? Does the 3.4 pinning have anything to do with conda failing to resolve dependencies?

**Comment by piyushrpt** [comment]
The C++ API has changed between the two versions. It is on the TO DO list to upgrade autoRIFT to opencv 4
