### ISSUE TITLE
Link with DataAccessor_static for stdproc components with CMake

### ISSUE THREAD

**Issue by piyushrpt** [isce-framework/isce2#167]
Just like openmp, I think link DataAccessor_static linking is missing for stdproc components.

This seems to work fine on OSX but fails on Linux - as reported by @hfattahi

**Comment by rtburns-jpl** [comment]
Thanks for reporting this! Python extensions are "weakly linked" so it can be harder to detect linker errors. The errors don't occur at link-time - you have to import the library to see the "missing symbols" failures.

I'm considering adding a shim to Python_add_library, which adds a trivial "test" that just tries to import each compiled extension. Then we can run ctest on our CI and catch these errors early. However, I think I'd need to add special cases for non-importable python modules, such as those using cffi.
