### ISSUE TITLE
UAVSAR_Stack sensor does not properly process segments other than the first segment of a UAVSAR SLC stack

### ISSUE THREAD

**Issue by EJFielding** [isce-framework/isce2#170]
The stripmapStack processor support for segments of a UAVSAR SLC stack other than segment 1 is incomplete. Interferograms are processed successfully, but they have incorrect geometry information. See https://github.com/insarlab/MintPy/issues/407 for details.

I will see if I can fix this.

**Comment by EJFielding** [comment]
Is there a best practices document for changing my local branch to the new `isce2/main` branch in v2.4.0?

**Comment by piyushrpt** [comment]
The problem is not with the reader. It is with the prepare script which does not propagate the segment number to the reader. If this is done correctly, the script should work.

**Comment by EJFielding** [comment]
I see now that most of the changes required are in the `unpackFrame_UAVSAR.py` code.

**Comment by EJFielding** [comment]
This was fixed by #171.
