### ISSUE TITLE
Feature: Change detection in Polarimetric SAR Images #25 

### ISSUE THREAD

**Issue by jjerphan** [isce-framework/isce2#177]
Hello,

@h-sdl and I have implemented a small pipeline for change detection for polarimetric SAR images in python from [1].

In short, we can detect changes between two SAR and subclasses changes in the two images:

![Example 1](https://gitlab.com/jjerphan/rsd-project/-/raw/master/figs/Redon_res.png) 
![Example 2](https://gitlab.com/jjerphan/rsd-project/-/raw/master/figs/Sajnam_res.png)

The best would be to known whether such a feature would be interesting to include in PyRAT.
 We do not know this library that much and thus this needs discussions. 

See our repository of the implementation: https://gitlab.com/jjerphan/rsd-project

See this original proposal of the method:
[1] Advanced Methods for Change Detection in Multi-polarization and
Very-High Resolution Multitemporal SAR Images. Davide Pirrone. PhD thesis, International Doctorate School in
Information and Communication Technologies - University of Trento, 1 2019.

See the slides of the presentation of this method we made (in French): https://cloud.mines-paristech.fr/index.php/s/aXhZ2o5BM8fIBR0

**Comment by hfattahi** [comment]
Hi @jjerphan 

In general we welcome user contributions which use isce frame-work to extend existing isce workflows or develop new workflows within isce framework. 
Are you using ISCE2 anywhere in your workflow? 

Or do you mean to contribute to PyRAT? If yes then that will be a question for PyRAT and not ISCE!

**Comment by jjerphan** [comment]
Hi @hfattahi,

Thanks for you answer.

> Or do you mean to contribute to PyRAT? If yes then that will be a question for PyRAT and not ISCE!

Oops, I've made a mistake: I would like to know if such an algorithm is on interest for ISCE.

> In general we welcome user contributions which use isce frame-work to extend existing isce workflows or develop new workflows within isce framework.
> Are you using ISCE2 anywhere in your workflow?

I am not using ISCE anywhere. In fact I am not working on this project any-more, it's just that I think that it would be nice to have this method available in a SAR framework or library, so that it could used.

I hope this makes my initial message clearer. :slightly_smiling_face:
