### ISSUE TITLE
Tutorial/Example Help

### ISSUE THREAD

**Issue by esnyder100** [isce-framework/isce2#178]
I've been reviewing many manuals in the isce and isce-docs downloads. I downloaded both from their respective github pages through the command line (https://github.com/isce-framework/isce2; https://github.com/isce-framework/isce2-docs). I've been trying to replicate Lab 5 from the lab5processingenvisat.pdf, but I've been unable to find the 'data' or 'lab5' directories. Do you know where they're located or where I can find any tutorial or example scripts that are not pdfs?

**Comment by rtburns-jpl** [comment]
I think we are not able to distribute the tutorial data, see https://github.com/isce-framework/isce2-docs/blob/master/tutorial/isce_tutorial.tex#L107_L123. As I understand it, you must adapt the material to data you have obtained independently.

**Comment by piyushrpt** [comment]
Must up to date material should be in the Notebooks folder of isce2-docs: https://github.com/isce-framework/isce2-docs/tree/master/Notebooks

The other material might be dated.
