### ISSUE TITLE
not well-formed (invalid token): line 3, column 13

### ISSUE THREAD

**Issue by DONGYUSEN** [isce-framework/isce2#189]
Completed Parsing the Configuration file
Functions to be executed:
['Function-1']
Running: Sentinel1_TOPS
['--dirname', '/Volumes/DATA1/JBT-A/S1B_IW_SLC__1SDV_20190420T151749_20190420T151817_015892_01DDA3_A970.zip', '--swaths', '1', '--orbitdir', '/Volumes/MSWAP/S1_orbit', '--outdir', '/Volumes/DATA/jbta/isce/secondarys/20190420', '--auxdir', '/Volumes/DATA/jbta/aux', '--bbox', '11.47 11.72 42.30 42.60', '--pol', 'vv']
Input XML files:  ['/vsizip//Volumes/DATA1/JBT-A/S1B_IW_SLC__1SDV_20190420T151749_20190420T151817_015892_01DDA3_A970.zip/S1B_IW_SLC__1SDV_20190420T151749_20190420T151817_015892_01DDA3_A970.SAFE/annotation/s1b-iw1-slc-vv-20190420t151751-20190420t151816-015892-01dda3-004.xml']
Input TIFF files:  ['/vsizip//Volumes/DATA1/JBT-A/S1B_IW_SLC__1SDV_20190420T151749_20190420T151817_015892_01DDA3_A970.zip/S1B_IW_SLC__1SDV_20190420T151749_20190420T151817_015892_01DDA3_A970.SAFE/measurement/s1b-iw1-slc-vv-20190420t151751-20190420t151816-015892-01dda3-004.tiff']
Manifest files:  ['/vsizip//Volumes/DATA1/JBT-A/S1B_IW_SLC__1SDV_20190420T151749_20190420T151817_015892_01DDA3_A970.zip/S1B_IW_SLC__1SDV_20190420T151749_20190420T151817_015892_01DDA3_A970.SAFE/manifest.safe']
MANS:  /Volumes/DATA1/JBT-A/S1B_IW_SLC__1SDV_20190420T151749_20190420T151817_015892_01DDA3_A970.zip S1B_IW_SLC__1SDV_20190420T151749_20190420T151817_015892_01DDA3_A970.SAFE/manifest.safe
Setting IPF version to :  002.91
not well-formed (invalid token): line 3, column 13

**Comment by piyushrpt** [comment]
Similar questions have been answered on the user forums. Check the downloaded zip file to check that its a complete and valid zip file.

**Comment by DONGYUSEN** [comment]
Thx, I will check the dataset now !

**Comment by DONGYUSEN** [comment]
the errors caused by the orbit file. 🔢
