### ISSUE TITLE
installing issue

### ISSUE THREAD

**Issue by manuelgeologo** [isce-framework/isce2#199]
Hello all! I'm trying to install isce2 following the cmake method and came across an error at 95%. Does anyone knows what can be wrong?. I have ubuntu 20.04 and anaconda. Thanks !

![image](https://user-images.githubusercontent.com/65048837/97644009-ec927500-1a27-11eb-8b99-2338a09e5ce1.png)

**Comment by rtburns-jpl** [comment]
Looks like you don't have Motif installed. Can you `apt install libmotif-dev` and give it a go again?

**Comment by manuelgeologo** [comment]
> Looks like you don't have Motif installed. Can you `apt install libmotif-dev` and give it a go again?

It's installed (version 2.3.8). Also, the file Xm.h does exist in /usr/include/xm

**Comment by rtburns-jpl** [comment]
Hmm, that's odd. Could you run `make VERBOSE=y` so I can see the failing compile command?

**Comment by manuelgeologo** [comment]
> Hmm, that's odd. Could you run `make VERBOSE=y` so I can see the failing compile command?
I got this: 

![image](https://user-images.githubusercontent.com/65048837/97648639-01750580-1a34-11eb-8c70-f45bb1a6265e.png)

**Comment by rtburns-jpl** [comment]
Could you tell me what the variables `MOTIF_INCLUDE_DIR:PATH` and `MOTIF_LIBRARIES:FILEPATH` are set to inside your `build/CMakeCache.txt`?

**Comment by manuelgeologo** [comment]
yes, here they are. 


MOTIF_INCLUDE_DIR:PATH=/usr/include

MOTIF_LIBRARIES:FILEPATH=/usr/lib/x86_64-linux-gnu/libXm.so

**Comment by rtburns-jpl** [comment]
Huh... so you have motif installed, and the files are in the right place, and it was detected properly by cmake... but it's not putting the flags on the link line? Wow, I'm stumped.

In the meantime, you should be able to disable motif by running cmake with `-DMOTIF_FOUND=NO`. I think it's only used for mdx, so everything else will build ok. And just in case you weren't aware, we do have a prebuilt conda package on conda-forge.

**Comment by manuelgeologo** [comment]
> Huh... so you have motif installed, and the files are in the right place, and it was detected properly by cmake... but it's not putting the flags on the link line? Wow, I'm stumped.
> 
> In the meantime, you should be able to disable motif by running cmake with `-DMOTIF_FOUND=NO`. I think it's only used for mdx, so everything else will build ok. And just in case you weren't aware, we do have a prebuilt conda package on conda-forge.

yeah, weird.. I will try disabling motif or making a fresh install. I didn't notice there is an install option with conda, probably easier, I will try it !. Thanks a lot for the help.

**Comment by manuelgeologo** [comment]
I forgot to close the thread. Problem solved, thanks for the help.
