### ISSUE TITLE
Sentinel1.py fails on line 973 when using gdal 3.1.3 

### ISSUE THREAD

**Issue by Alex-Lewandowski** [isce-framework/isce2#218]
It looks like gdal now expects the environment variable CPL_ZIP_ENCODING = UTF-8. Adding it to the script with os.environ got it working again.

**Comment by rtburns-jpl** [comment]
Did you install gdal via conda? If so, that should be done automatically by gdal's activate script, when you activate the conda environment.

**Comment by Alex-Lewandowski** [comment]
Ahh, that explains it. We did install gdal with conda but it is part of a multistage docker build and the environment variable didn't get carried all the way through. Thanks for pointing me in the right direction!
