### ISSUE TITLE
problem with the commit  #225: 'Bash script edits to make stackSentinel.py faster in places'

### ISSUE THREAD

**Issue by mirzaees** [isce-framework/isce2#230]
This change has proposed a few difficulties in job submission on HPC.
It was agreed to be optional but the way it is implemented is based on existing `num_process` argumet of stackSentinel.py
This argument was supposed to be used in `multiprocessing` module to speedup topo.py
The problem is that we would like it to be 1 (not applied) for ifgrams and unwrapping steps, as it is proposed but we definitely need it to be a higher value for topo.py
run files should not deal with parallelization as there are so many ways to do that, but if you prefer to keep this change, we should consider to use another argument, maybe a new one other than `num_process`
@yunjunz , @hfattahi  what is your opinion?

**Comment by yunjunz** [comment]
Having an independent argument for topo, with the default value grabbing from `num_process`, sounds good to me. In this way, non-HPC users could use the current version as it is, and HPC users could use the previous version.

This mix is rooted from the different parallelizations between topo.py and the other scripts. A cleaner way could be generating a run_file for topo with multiple lines (each line for one burst).

**Comment by mirzaees** [comment]
thank you @yunjunz , then I will make a PR for adding a new argument for topo.py
Do you agree with something like `cpu_count` of `num_cpu` ?

**Comment by yunjunz** [comment]
I would suggest `--num_proc4topo`, `--num_process4topo` for clarity.

Could you please also change the `--num-proc` and `--num-process` to `--num_proc` and `--num_process` for style consistency? I was not careful about it before.

**Comment by mirzaees** [comment]
Sure,
Thank you!

**Comment by RussellGrew** [comment]
Sorry about the issue!

**Comment by yunjunz** [comment]
> Sorry about the issue!

No worries at all, I appreciate both of your useful contributions!
