### ISSUE TITLE
Question on how to use this framework for preprocessing Sentinel-1 GRD single polarization

### ISSUE THREAD

**Issue by rbavery** [isce-framework/isce2#240]
We are looking to apply 5 operations to a time series of single polarization VV Sentinel-1 GRD, instead of the InSAR product. These include:
1. Geocoding
2. Radiometric Terrain Correction to gamma-nought backscatter and resampling to 30 meters
3. mosaicking images taken during the same day 
4. adaptive multi-temporal SAR speckle filtering
5. coregistration with a Landsat time series

Any pointers on if this is the right package to extend to support processing single polarization SAR images? And where I might start?

I haven't found any scalable open source alternatives to preprocessing single polarization Sentinel-1 data and this seemed like a project that is closest to that goal.

We are looking to process this time series similar to Reiche 2018 to use SAR and optical data in conjunction for mapping deforestation: https://www.sciencedirect.com/science/article/abs/pii/S0034425717304959

**Comment by rtburns-jpl** [comment]
Hi, thanks for getting in touch! I'll try to answer your question as best I can, but perhaps take my words with a grain of salt as I am a relative newcomer to isce2.

As far as I understand, isce2 is a loose collection of modules which are tailor-built for their respective workflows and sensors. This is research code which contains all the functionality as far as the underlying algorithms you want in some form, but may need some serious elbow grease to be adapted to the higher-level parts of your data processing workflow. In particular, I'm not sure if we have anything set up for GRD processing, and many modules such as RTC are in need of documentation: https://github.com/isce-framework/isce2/issues/176. Also, isce2 is more aimed at radar imagery than optical data.

If that doesn't discourage you, I would suggest choosing a single one of your bullet points and seeing what's involved in adapting that portion of your workflow. I think this short excursion should give you a good idea of what challenges and issues you may expect.

**Comment by rbavery** [comment]
Thanks a bunch for the reply @rtburns-jpl . Since the project I'm doing is short term, I probably can't spend the time to rework parts of this project for my application (I'll probably use SNAP's Sentinel-1 toolbox instead).  I really appreciate the info and will look to this project if I ever need to work with InSAR data.
