### ISSUE TITLE
Avoiding Unzipping in alos2app?

### ISSUE THREAD

**Issue by cmarshak** [isce-framework/isce2#246]
I am using the [`alos2app`](https://github.com/isce-framework/isce2/blob/main/examples/input_files/alos2/alos2App.xml) and trying to save as much disk space as possible. I know with `topsApp` that we can replace the reference/secondary directories with the paths of the reference/secondary zip files. Does the `alos2app` have the same capabilities or are there other tips in the processing pipeline to save space eg only unzipping a particular polarization as indicated [here](https://github.com/isce-framework/isce2/blob/main/examples/input_files/alos2/alos2_tutorial.txt)?

I am currently using version 2.3 via conda on a Linux machine.

I know that @CunrenLiang did most of the development here and some am tagging him. 

Thank you for your help.

**Comment by CunrenLiang** [comment]
We don't yet have the feature for reading from zip files directly. It takes much more time.
Yes, you can only unzip the polarization you want to process, and delete the unzipped files after you are done with the processing.

**Comment by CunrenLiang** [comment]
We don't yet have the feature for reading from zip files directly. It takes much more time.
Yes, you can only unzip the polarization you want to process, and delete the unzipped files after you are done with the processing.

**Comment by cmarshak** [comment]
Thank you!
