### ISSUE TITLE
orbits fetchOrbit.py

### ISSUE THREAD

**Issue by alejobeap** [isce-framework/isce2#253]
**Dear
Iḿ trying to prepare the satck with ISCE for Sentinel but I had the message** 
20210228
orbit was not found in the /mnt/procesamiento/Procesamiento_Sentinel/Sangay/Stack_Descendente/Orbits
downloading precise or restituted orbits ...
Traceback (most recent call last):
  File "/home/insar/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 736, in <module>
    main()
  File "/home/insar/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 700, in main
    acquisitionDates, stackMasterDate, slaveDates, safe_dict, updateStack = checkCurrentStatus(inps)
  File "/home/insar/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 577, in checkCurrentStatus
    acquisitionDates, stackMasterDate, slaveDates, safe_dict = get_dates(inps)
  File "/home/insar/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 243, in get_dates
    safeObj.get_orbit(inps.orbit_dirname, inps.work_dir)
  File "/home/insar/instaladores/isce2/contrib/stack/topsStack/Stack.py", line 909, in get_orbit
    orbitFile = glob.glob(os.path.join(restitutedOrbitDir,'*.EOF'))[0]
IndexError: list index out of range

**I know that the page is down and I change with the direction in fetcOrbits.py to** 

server = 'https://aux.sentinel1.eo.esa.int/'

orbitMap = [('precise','aux_poeorb'),
            ('restituted','aux_resorb')]

20190122
orbit was not found in the /mnt/procesamiento/Procesamiento_Sentinel/Sangay/Stack_Descendente/Orbits
downloading precise or restituted orbits ...
fetchOrbit.py -i /mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/S1A_IW_SLC__1SDV_20190122T105307_20190122T105336_025589_02D706_6D80.zip -o /mnt/procesamiento/Procesamiento_Sentinel/Sangay/Stack_Descendente/orbits/20190122
Reference time:  2019-01-22 10:53:36
Satellite name:  S1A
https://aux.sentinel1.eo.esa.int/aux_poeorb/?validity_start=2019-01-20..2019-01-24&sentinel1__mission=S1A
Querying for precise orbits
/home/insar/anaconda3/envs/isce2/lib/python3.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
Exception - something went wrong with the web scraper:
Exception: 404 Client Error: Not Found for url: https://aux.sentinel1.eo.esa.int/aux_poeorb/?validity_start=2019-01-20..2019-01-24&sentinel1__mission=S1A
Continuing process
Failed to find precise orbits for Time 2019-01-22 10:53:36
https://aux.sentinel1.eo.esa.int/aux_resorb/?validity_start=2019-01-21..2019-01-23&sentinel1__mission=S1A
Querying for restituted orbits
/home/insar/anaconda3/envs/isce2/lib/python3.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
Exception - something went wrong with the web scraper:
Exception: 404 Client Error: Not Found for url: https://aux.sentinel1.eo.esa.int/aux_resorb/?validity_start=2019-01-21..2019-01-23&sentinel1__mission=S1A
Continuing process
Failed to find restituted orbits for Time 2019-01-22 10:53:36
Traceback (most recent call last):
  File "/home/insar/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 736, in <module>
    main()
  File "/home/insar/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 700, in main
    acquisitionDates, stackMasterDate, slaveDates, safe_dict, updateStack = checkCurrentStatus(inps)
  File "/home/insar/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 577, in checkCurrentStatus
    acquisitionDates, stackMasterDate, slaveDates, safe_dict = get_dates(inps)
  File "/home/insar/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 243, in get_dates
    safeObj.get_orbit(inps.orbit_dirname, inps.work_dir)
  File "/home/insar/instaladores/isce2/contrib/stack/topsStack/Stack.py", line 928, in get_orbit
    self.orbit =  orbitFile[0]
IndexError: list index out of range

**What can I do to download the orbits for processing?**

**Thank you**

Pedro

**Comment by rtburns-jpl** [comment]
Possibly same issue as https://github.com/isce-framework/isce2/issues/249?

**Comment by alejobeap** [comment]
No, the error is different in all cases

**Comment by AhmetMA** [comment]
The orbits are now at: https://qc.sentinel1.copernicus.eu/ 
(-> https://scihub.copernicus.eu/news/News00837)

**Comment by alejobeap** [comment]
Thanks, now it works ok with the new fetchOrbits.py

**Comment by alejobeap** [comment]
Dear @bjmarfito 
I have been trying with the ascending track but it started to give me errors in the download of the orbits, in the descending track it worked correctly. Is it something to do with the tracks?

20210315
orbit was not found in the /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Ascendente/orbits
downloading precise or restituted orbits ...
fetchOrbit.py -i /mnt/nas_insar/Cotopaxi_Sentinel_Ascendente/S1A_IW_SLC__1SDV_20210315T233713_20210315T233743_037015_045B27_2B9A.zip -o /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Ascendente/orbits/20210315
Reference time:  2021-03-15 23:37:43
Satellite name:  S1A
Failed to find S1A orbits for tref 2021-03-15 23:37:43
Traceback (most recent call last):
  File "/opt/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 773, in <module>
    main()
  File "/opt/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 737, in main
    acquisitionDates, stackReferenceDate, secondaryDates, safe_dict, updateStack = checkCurrentStatus(inps)
  File "/opt/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 613, in checkCurrentStatus
    acquisitionDates, stackReferenceDate, secondaryDates, safe_dict = get_dates(inps)
  File "/opt/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 254, in get_dates
    safeObj.get_orbit(inps.orbit_dirname, inps.work_dir)
  File "/opt/instaladores/isce2/contrib/stack/topsStack/Stack.py", line 963, in get_orbit
    self.orbit =  orbitFile[0]
IndexError: list index out of range

Thanks for your help.

**Comment by piyushrpt** [comment]
There is another change coming in the way ESA distributes orbits - https://scihub.copernicus.eu/gnss/#/home . This site does not have all the orbits yet. The orbits will be removed from the aux site when this happens. I would say for now, just recursively copy the files on the aux site to a local folder and use that.

**Comment by alejobeap** [comment]
thanks I'm trying to do that but I had:

writing  /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Ascendente/run_files/run_01_unpack_topo_reference
Traceback (most recent call last):
  File "/opt/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 773, in <module>
    main()
  File "/opt/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 756, in main
    interferogramStack(inps, acquisitionDates, stackReferenceDate, secondaryDates, safe_dict, pairs, updateStack)
  File "/opt/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 560, in interferogramStack
    i = slcStack(inps, acquisitionDates, stackReferenceDate, secondaryDates, safe_dict, updateStack)
  File "/opt/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 447, in slcStack
    runObj.unpackStackReferenceSLC(safe_dict)
  File "/opt/instaladores/isce2/contrib/stack/topsStack/Stack.py", line 337, in unpackStackReferenceSLC
    configObj.topo('[Function-2]')
  File "/opt/instaladores/isce2/contrib/stack/topsStack/Stack.py", line 79, in topo
    self.f.write('numProcess : ' + str(self.numProcess4topo) + '\n')
AttributeError: 'config' object has no attribute 'numProcess4topo'

**Comment by bjmarfito** [comment]
@alejobeap, pls. download again the edited code on this link (https://onedrive.live.com/?authkey=%21APZ5Z8oqV4jvyY8&cid=B5903921196601EA&id=B5903921196601EA%2163958&parId=B5903921196601EA%2152894&o=OneUp) and try if it works for you. Thanks!

**Comment by bjmarfito** [comment]
I forgot to tell you that I've made some minor changes on the code to corrects its logic for querying orbits. Kindly download it again using the link on the previous comment. Thanks!

**Comment by alejobeap** [comment]
Dear @bjmarfito  the STack and download was OK:
But (bellow) I had the same #255 

20201206
orbit was not found in the /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/orbits
downloading precise or restituted orbits ...
fetchOrbit.py -i /mnt/nas_insar/Cotopaxi_Sentinel_Descendente/S1A_IW_SLC__1SDV_20201206T105257_20201206T105324_035564_0428A4_69D5.zip -o /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/orbits/20201206
Reference time:  2020-12-06 10:53:24
Satellite name:  S1A
Downloading URL:  http://aux.sentinel1.eo.esa.int/POEORB/2020/12/27/S1A_OPER_AUX_POEORB_OPOD_20201227T120845_V20201206T225942_20201208T005942.EOF
Number of SAFE files to be used (cover BBOX): 73
*****************************************
Number of dates : 73
List of dates : 
['20190104', '20190110', '20190116', '20190203', '20190209', '20190221', '20190305', '20190311', '20190404', '20190416', '20190504', '20190516', '20190609', '20190621', '20190703', '20190715', '20190808', '20190820', '20190901', '20190913', '20191001', '20191013', '20191019', '20191106', '20191118', '20191206', '20191218', '20191224', '20200105', '20200204', '20200216', '20200305', '20200317', '20200404', '20200416', '20200504', '20200522', '20200603', '20200615', '20200709', '20200802', '20200814', '20200826', '20200907', '20200913', '20200919', '20200925', '20201001', '20201007', '20201019', '20201025', '20201031', '20201112', '20201118', '20201124', '20201130', '20201206', '20201212', '20201218', '20201224', '20201230', '20210111', '20210117', '20210123', '20210129', '20210204', '20210210', '20210216', '20210222', '20210228', '20210306', '20210312', '20210318']
date      south      north
20190104 -2.433936 -0.323071
20190110 -2.042191 0.06481
20190116 -2.434106 -0.323322
20190203 -2.041609 0.065102
20190209 -2.434005 -0.323113
20190221 -2.434834 -0.323969
20190305 -2.434319 -0.323337
20190311 -2.041865 0.06488
20190404 -2.042116 0.064708
20190416 -2.042173 0.064566
20190504 -2.433813 -0.322951
20190516 -2.433768 -0.322887
20190609 -2.434034 -0.322867
20190621 -2.434087 -0.323189
20190703 -2.42397 -0.317281
20190715 -2.424231 -0.317531
20190808 -2.42416 -0.317398
20190820 -2.424466 -0.317614
20190901 -2.424523 -0.317817
20190913 -2.424627 -0.317913
20191001 -2.032095 0.070226
20191013 -2.032205 0.070228
20191019 -2.424752 -0.318007
20191106 -2.031856 0.070841
20191118 -2.032435 0.07028
20191206 -2.424521 -0.317792
20191218 -2.424981 -0.318377
20191224 -2.031924 0.070604
20200105 -2.03185 0.070713
20200204 -2.423801 -0.317217
20200216 -2.424619 -0.317887
20200305 -2.032148 0.070412
20200317 -2.032003 0.070319
20200404 -2.424273 -0.31771
20200416 -2.423961 -0.31722
20200504 -2.032009 0.070551
20200522 -2.423683 -0.316838
20200603 -2.423865 -0.316926
20200615 -2.423716 -0.317006
20200709 -2.423632 -0.316925
20200802 -2.423828 -0.317134
20200814 -2.423875 -0.31714
20200826 -2.424142 -0.317267
20200907 -2.424415 -0.3178
20200913 -2.032672 0.070174
20200919 -2.424443 -0.317612
20200925 -2.031601 0.070876
20201001 -2.424541 -0.317833
20201007 -2.031975 0.070616
20201019 -2.031708 0.070849
20201025 -2.424052 -0.317312
20201031 -2.031387 0.07102
20201112 -2.031896 0.070793
20201118 -2.423908 -0.317322
20201124 -2.031984 0.07059
20201130 -2.424215 -0.317542
20201206 -2.0321 0.070592
20201212 -2.42404 -0.317229
20201218 -2.031359 0.071194
20201224 -2.423974 -0.317015
20201230 -2.032148 0.07062
20210111 -2.031485 0.071166
20210117 -2.423819 -0.317105
20210123 -2.031562 0.071124
20210129 -2.423972 -0.317421
20210204 -2.03126 0.07131
20210210 -2.423843 -0.317295
20210216 -2.031502 0.071057
20210222 -2.424036 -0.317325
20210228 -2.031272 0.071255
20210306 -2.424136 -0.317289
20210312 -2.031208 0.071186
20210318 -2.423932 -0.31722
*****************************************
The overlap region among all dates (based on the preview kml files):
 South   North   East  West 
-2.031208 -0.323969 -78.897453 -76.460556
*****************************************
All dates (73)
['20190104', '20190110', '20190116', '20190203', '20190209', '20190221', '20190305', '20190311', '20190404', '20190416', '20190504', '20190516', '20190609', '20190621', '20190703', '20190715', '20190808', '20190820', '20190901', '20190913', '20191001', '20191013', '20191019', '20191106', '20191118', '20191206', '20191218', '20191224', '20200105', '20200204', '20200216', '20200305', '20200317', '20200404', '20200416', '20200504', '20200522', '20200603', '20200615', '20200709', '20200802', '20200814', '20200826', '20200907', '20200913', '20200919', '20200925', '20201001', '20201007', '20201019', '20201025', '20201031', '20201112', '20201118', '20201124', '20201130', '20201206', '20201212', '20201218', '20201224', '20201230', '20210111', '20210117', '20210123', '20210129', '20210204', '20210210', '20210216', '20210222', '20210228', '20210306', '20210312', '20210318']

dates covering the bbox (73)
['20190104', '20190110', '20190116', '20190203', '20190209', '20190221', '20190305', '20190311', '20190404', '20190416', '20190504', '20190516', '20190609', '20190621', '20190703', '20190715', '20190808', '20190820', '20190901', '20190913', '20191001', '20191013', '20191019', '20191106', '20191118', '20191206', '20191218', '20191224', '20200105', '20200204', '20200216', '20200305', '20200317', '20200404', '20200416', '20200504', '20200522', '20200603', '20200615', '20200709', '20200802', '20200814', '20200826', '20200907', '20200913', '20200919', '20200925', '20201001', '20201007', '20201019', '20201025', '20201031', '20201112', '20201118', '20201124', '20201130', '20201206', '20201212', '20201218', '20201224', '20201230', '20210111', '20210117', '20210123', '20210129', '20210204', '20210210', '20210216', '20210222', '20210228', '20210306', '20210312', '20210318']

The reference date was not chosen. The first date is considered as reference date.

All SLCs will be coregistered to : 20190104
secondary dates :
['20190110', '20190116', '20190203', '20190209', '20190221', '20190305', '20190311', '20190404', '20190416', '20190504', '20190516', '20190609', '20190621', '20190703', '20190715', '20190808', '20190820', '20190901', '20190913', '20191001', '20191013', '20191019', '20191106', '20191118', '20191206', '20191218', '20191224', '20200105', '20200204', '20200216', '20200305', '20200317', '20200404', '20200416', '20200504', '20200522', '20200603', '20200615', '20200709', '20200802', '20200814', '20200826', '20200907', '20200913', '20200919', '20200925', '20201001', '20201007', '20201019', '20201025', '20201031', '20201112', '20201118', '20201124', '20201130', '20201206', '20201212', '20201218', '20201224', '20201230', '20210111', '20210117', '20210123', '20210129', '20210204', '20210210', '20210216', '20210222', '20210228', '20210306', '20210312', '20210318']

No existing stack was identified. A new stack will be generated.
*****************************************
Coregistration method:  NESD
Workflow:  interferogram
*****************************************
writing  /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/run_files/run_01_unpack_topo_reference
writing  /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/run_files/run_02_unpack_secondary_slc
writing  /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/run_files/run_03_average_baseline
writing  /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/run_files/run_04_extract_burst_overlaps
writing  /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/run_files/run_05_overlap_geo2rdr
writing  /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/run_files/run_06_overlap_resample
writing  /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/run_files/run_07_pairs_misreg
writing  /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/run_files/run_08_timeseries_misreg
writing  /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/run_files/run_09_fullBurst_geo2rdr
writing  /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/run_files/run_10_fullBurst_resample
writing  /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/run_files/run_11_extract_stack_valid_region
writing  /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/run_files/run_12_merge_reference_secondary_slc
writing  /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/run_files/run_13_generate_burst_igram
writing  /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/run_files/run_14_merge_burst_igram
writing  /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/run_files/run_15_filter_coherence
writing  /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/run_files/run_16_unwrap

**BUT**
**when I run the /run_01_unpack_topo_reference  I had the same error #255** 

(isce2) [isce@srvisce run_files]$ ./run_01_unpack_topo_reference 
Completed Parsing the Configuration file
Functions to be executed:
['Function-1', 'Function-2']
Running: Sentinel1_TOPS
['--dirname', '/mnt/nas_insar/Cotopaxi_Sentinel_Descendente/S1B_IW_SLC__1SDV_20190104T105208_20190104T105235_014343_01AB02_D0CF.zip', '--swaths', '3', '--orbit', '/mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/orbits/20190104/S1B_OPER_AUX_POEORB_OPOD_20190125T110741_V20190104T225942_20190106T005942.EOF', '--outdir', '/mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/reference', '--auxdir', '/mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/auxdir', '--bbox', '-0.81 -0.57 -78.56 -78.33', '--pol', 'vv']
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
Input XML files:  ['/vsizip//mnt/nas_insar/Cotopaxi_Sentinel_Descendente/S1B_IW_SLC__1SDV_20190104T105208_20190104T105235_014343_01AB02_D0CF.zip/S1B_IW_SLC__1SDV_20190104T105208_20190104T105235_014343_01AB02_D0CF.SAFE/annotation/s1b-iw3-slc-vv-20190104t105208-20190104t105233-014343-01ab02-006.xml']
Input TIFF files:  ['/vsizip//mnt/nas_insar/Cotopaxi_Sentinel_Descendente/S1B_IW_SLC__1SDV_20190104T105208_20190104T105235_014343_01AB02_D0CF.zip/S1B_IW_SLC__1SDV_20190104T105208_20190104T105235_014343_01AB02_D0CF.SAFE/measurement/s1b-iw3-slc-vv-20190104t105208-20190104t105233-014343-01ab02-006.tiff']
Manifest files:  ['/vsizip//mnt/nas_insar/Cotopaxi_Sentinel_Descendente/S1B_IW_SLC__1SDV_20190104T105208_20190104T105235_014343_01AB02_D0CF.zip/S1B_IW_SLC__1SDV_20190104T105208_20190104T105235_014343_01AB02_D0CF.SAFE/manifest.safe']
MANS:  /mnt/nas_insar/Cotopaxi_Sentinel_Descendente/S1B_IW_SLC__1SDV_20190104T105208_20190104T105235_014343_01AB02_D0CF.zip S1B_IW_SLC__1SDV_20190104T105208_20190104T105235_014343_01AB02_D0CF.SAFE/manifest.safe
Setting IPF version to :  002.91
Extracting orbit from Orbit File:  /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/orbits/20190104/S1B_OPER_AUX_POEORB_OPOD_20190125T110741_V20190104T225942_20190106T005942.EOF
Time stamp (2019-01-04 10:52:09.793942) falls outside of the interpolation interval [9999-12-31 00:00:00:0001-01-01 00:00:00]
Running: topo
['--reference', '/mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/reference', '--dem', '/mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/DEM/demLat_S02_N02_Lon_W079_W077.dem.wgs84', '--geom_referenceDir', '/mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/geom_reference']
##LLEGA Namespace(dem='/mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/DEM/demLat_S02_N02_Lon_W079_W077.dem.wgs84', geom_referenceDir='/mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/geom_reference', reference='/mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/reference')
running in parallel with 16 processes
Traceback (most recent call last):
  File "/opt/instaladores/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/opt/instaladores/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/opt/instaladores/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/opt/instaladores/isce2/contrib/stack/topsStack/topo.py", line 113, in main
    **bbox = [np.min(boxes[:,0]), np.max(boxes[:,1]), np.min(boxes[:,2]), np.max(boxes[:,3])]**
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

Thanks

**Comment by bjmarfito** [comment]
@alejobeap, apologies for the inconvenience I've made. I've edited the code again to reflect the changes on the downloading of the orbit files. You may download it again using the link and check if it works properly now. Thanks!

**Comment by bjmarfito** [comment]
@alejobeap, yes the download is okay but the problem you have is your image file does not match the orbit file. You may need to redownload the code on the link to see if it fixes the issue.

**Comment by alejobeap** [comment]
Thanks I downloaded the new code. I'm running again my stack. I'll let you know how the processing goes.

**Comment by alejobeap** [comment]
Thanks I run the ascending and descending track and the stack was Ok @bjmarfito.

![image](https://user-images.githubusercontent.com/65787135/112709269-dcbb7780-8e85-11eb-8de5-23993c8f2098.png)

Thank you again for your help.

Pedro

PD. If there is any change with the download location of the orbits, please let us know. Thanks

**Comment by bjmarfito** [comment]
I've not done it properly without your feedbacks and suggestions @alejobeap and @rtburns-jpl. Thank you very much!
