### ISSUE TITLE
https://aux.sentinel1.eo.esa.int is down for a couple of days

### ISSUE THREAD

**Issue by bjmarfito** [isce-framework/isce2#267]
For a couple of days now, https://aux.sentinel1.eo.esa.int/ site is down so I can't download Sentinel-1 orbit files using fetchOrbit.py. Is it just temporary or has ESA permanently moved the orbit files site to https://scihub.copernicus.eu/gnss/#/home?

**Comment by piyushrpt** [comment]
These orbits are available here for now - https://s1qc.asf.alaska.edu/ . Everyone is hoping that the GNSS site with all the historical orbits will be updated soon.

**Comment by bjmarfito** [comment]
Thank you @piyushrpt.

**Comment by alejobeap** [comment]
Thanks, Downloading directly from the page mentioned and copying it into the orbit folder will the stack work?

**Comment by bjmarfito** [comment]
Yes you can @alejobeap. Just specify the address of the orbit folder using the -o option on the stackSentinel.py.

**Comment by bjmarfito** [comment]
@piyushrpt, based on new announcements from ESA (https://scihub.copernicus.eu/news/News00855 and https://sentinel.esa.int/documents/247904/3455957/Sentinel-1-C-POD-Full-Mission-Reprocessing-2021.pdf), are these announcements indicate that the old Sentinel-1 orbit files are already available on the https://scihub.copernicus.eu/gnss/#/home?

**Comment by piyushrpt** [comment]
Looks like reprocessed POEORBs are being made available on the gnss site

**Comment by alejobeap** [comment]
Dear
I'm trying with my orbits backup and download the orbit for the 20200405 and 20200411 but I had the error when I run the stack:
stackSentinel.py -s /mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/ -d /mnt/procesamiento/Procesamiento_Sentinel/Sangay/Stack_Descendente/DEM/demLat_S03_S01_Lon_W079_W077.dem.wgs84 -a /mnt/procesamiento/Procesamiento_Sentinel/Sangay/Stack_Descendente/Auxdir -o /mnt/procesamiento/Procesamiento_Sentinel/Sangay/Stack_Descendente/orbits -n '3 2' -C NESD -b '-2.08 -1.93 -78.40 -78.28'  -W interferogram

writing  /mnt/procesamiento/Procesamiento_Sentinel/Sangay/Stack_Descendente/run_files/run_1_unpack_slc_topo_master
Traceback (most recent call last):
  File "/home/insar/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 736, in <module>
    main()
  File "/home/insar/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 719, in main
    interferogramStack(inps, acquisitionDates, stackMasterDate, slaveDates, safe_dict, pairs, updateStack)  
  File "/home/insar/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 531, in interferogramStack
    i = slcStack(inps, acquisitionDates, stackMasterDate, slaveDates, safe_dict, updateStack)
  File "/home/insar/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 438, in slcStack
    runObj.unpackSlavesSLC(stackMasterDate, slaveDates, safe_dict)
  File "/home/insar/instaladores/isce2/contrib/stack/topsStack/Stack.py", line 328, in unpackSlavesSLC
    configObj.orbit_type = safe_dict[slave].orbitType

![image](https://user-images.githubusercontent.com/65787135/114558188-0cad9d80-9c30-11eb-99cc-862283ba3359.png)

Thanks for your help
