### ISSUE TITLE
Config files for run_01 and run_02

### ISSUE THREAD

**Issue by alejobeap** [isce-framework/isce2#268]
Dear
I run according the issue #267 with my backup orbits files and download the last orbits.
when I tried to run in the run_file folder the step run_01 and run_02 I had some errors.
I reviewed the config_files for example for run_02 the file config_secondary_20190203:
[Common]
##########################
##########################
[Function-1]
Sentinel1_TOPS :
dirname : /mnt/nas_insar/Cotopaxi_Sentinel_Descendente/S1A_IW_SLC__1SDV_20190203T105242_20190203T105309_025764_02DD65_ACE3.zip
swaths : 3
**orbit : /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/orbits/**
outdir : /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/secondarys/20190203
auxdir : /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/Auxdir
bbox : -0.81 -0.57 -78.56 -78.33
pol : vv
##########################

but in the error in the terminal was:
No suitable orbit file found. If you want to process anyway - unset the orbitdir parameter

![image](https://user-images.githubusercontent.com/65787135/113800319-5a9c4000-971c-11eb-86a3-10233a927157.png)

I put in the all files config_secondary_XXXXXXX the correct directory and file (example bellow)

[Common]
##########################
##########################
[Function-1]
Sentinel1_TOPS :
dirname : /mnt/nas_insar/Cotopaxi_Sentinel_Descendente/S1A_IW_SLC__1SDV_20190203T105242_20190203T105309_025764_02DD65_ACE3.zip
swaths : 3
**orbit : /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/orbits/20190203/S1A_OPER_AUX_POEORB_OPOD_20190223T120736_V20190202T225942_20190204T005942.EOF**
outdir : /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/secondarys/20190203
auxdir : /mnt/nas_insar/ISCE_Procesamiento/Cotopaxi_Descendente/Auxdir
bbox : -0.81 -0.57 -78.56 -78.33
pol : vv
##########################

and ran this step again and it worked. In this case it was only a small amount of data but there is a way to make it generate these files correctly. I don't know if it is because the orbits download is not possible because until the previous week the orbits site was working, everything was working correctly.

Thank you for your help.

**Comment by piyushrpt** [comment]
Should be `orbitdir` in the config file if you are providing a folder. `orbit` is for providing a specific file.

**Comment by alejobeap** [comment]
Also I have this error in the last orbit file 

Completed Parsing the Configuration file
Functions to be executed:
['Function-1']
Running: Sentinel1_TOPS
['--dirname', '/mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.zip /mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/S1B_IW_SLC__1SDV_20210411T105244_20210411T105311_026418_03275C_D7A4.zip', '--swaths', '3 2', '--orbitdir', '/mnt/procesamiento/Procesamiento_Sentinel/Sangay/Stack_Descendente/orbits/20210411/S1B_OPER_AUX_RESORB_OPOD_20210411T153115_V20210411T100232_20210411T132002.EOF', '--outdir', '/mnt/procesamiento/Procesamiento_Sentinel/Sangay/Stack_Descendente/slaves/20210411', '--auxdir', '/mnt/procesamiento/Procesamiento_Sentinel/Sangay/Stack_Descendente/Auxdir', '--bbox', '-2.08 -1.93 -78.40 -78.28', '--pol', 'vv']
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
Editado por: Wilson Acero, Pedro A. Espin B. & Patricia Mothes
Instituto Geofisico-Escuela Politecnica Nacional (2020)
www.igepn.edu.ec
Input XML files:  ['/vsizip//mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.zip/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.SAFE/annotation/s1b-iw3-slc-vv-20210411t105219-20210411t105244-026418-03275c-006.xml', '/vsizip//mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/S1B_IW_SLC__1SDV_20210411T105244_20210411T105311_026418_03275C_D7A4.zip/S1B_IW_SLC__1SDV_20210411T105244_20210411T105311_026418_03275C_D7A4.SAFE/annotation/s1b-iw3-slc-vv-20210411t105244-20210411t105309-026418-03275c-006.xml']
Input TIFF files:  ['/vsizip//mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.zip/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.SAFE/measurement/s1b-iw3-slc-vv-20210411t105219-20210411t105244-026418-03275c-006.tiff', '/vsizip//mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/S1B_IW_SLC__1SDV_20210411T105244_20210411T105311_026418_03275C_D7A4.zip/S1B_IW_SLC__1SDV_20210411T105244_20210411T105311_026418_03275C_D7A4.SAFE/measurement/s1b-iw3-slc-vv-20210411t105244-20210411t105309-026418-03275c-006.tiff']
Manifest files:  ['/vsizip//mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.zip/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.SAFE/manifest.safe', '/vsizip//mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/S1B_IW_SLC__1SDV_20210411T105244_20210411T105311_026418_03275C_D7A4.zip/S1B_IW_SLC__1SDV_20210411T105244_20210411T105311_026418_03275C_D7A4.SAFE/manifest.safe']
Input XML files:  ['/vsizip//mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.zip/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.SAFE/annotation/s1b-iw3-slc-vv-20210411t105219-20210411t105244-026418-03275c-006.xml']
Input TIFF files:  ['/vsizip//mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.zip/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.SAFE/measurement/s1b-iw3-slc-vv-20210411t105219-20210411t105244-026418-03275c-006.tiff']
MANS:  /mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.zip S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.SAFE/manifest.safe
Setting IPF version to :  003.31
**No suitable orbit file found. If you want to process anyway - unset the orbitdir parameter**
Input XML files:  ['/vsizip//mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.zip/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.SAFE/annotation/s1b-iw2-slc-vv-20210411t105221-20210411t105246-026418-03275c-005.xml', '/vsizip//mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/S1B_IW_SLC__1SDV_20210411T105244_20210411T105311_026418_03275C_D7A4.zip/S1B_IW_SLC__1SDV_20210411T105244_20210411T105311_026418_03275C_D7A4.SAFE/annotation/s1b-iw2-slc-vv-20210411t105246-20210411t105311-026418-03275c-005.xml']
Input TIFF files:  ['/vsizip//mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.zip/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.SAFE/measurement/s1b-iw2-slc-vv-20210411t105221-20210411t105246-026418-03275c-005.tiff', '/vsizip//mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/S1B_IW_SLC__1SDV_20210411T105244_20210411T105311_026418_03275C_D7A4.zip/S1B_IW_SLC__1SDV_20210411T105244_20210411T105311_026418_03275C_D7A4.SAFE/measurement/s1b-iw2-slc-vv-20210411t105246-20210411t105311-026418-03275c-005.tiff']
Manifest files:  ['/vsizip//mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.zip/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.SAFE/manifest.safe', '/vsizip//mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/S1B_IW_SLC__1SDV_20210411T105244_20210411T105311_026418_03275C_D7A4.zip/S1B_IW_SLC__1SDV_20210411T105244_20210411T105311_026418_03275C_D7A4.SAFE/manifest.safe']
Input XML files:  ['/vsizip//mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.zip/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.SAFE/annotation/s1b-iw2-slc-vv-20210411t105221-20210411t105246-026418-03275c-005.xml']
Input TIFF files:  ['/vsizip//mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.zip/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.SAFE/measurement/s1b-iw2-slc-vv-20210411t105221-20210411t105246-026418-03275c-005.tiff']
MANS:  /mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.zip S1B_IW_SLC__1SDV_20210411T105219_20210411T105246_026418_03275C_4D6D.SAFE/manifest.safe
Setting IPF version to :  003.31

![image](https://user-images.githubusercontent.com/65787135/114618029-81073180-9c6e-11eb-9b87-0dcab2cd3d3d.png)

**Which orbit should I download?**

Thanks

**Comment by alejobeap** [comment]
I

**Comment by xiangbenzhang** [comment]
![image](https://github.com/isce-framework/isce2/assets/139545921/4cbaf1a0-c850-4e42-afb7-00022122ec48)
Hello friends, the problem you encountered, I also encountered when dealing with it in recent days, but I still don't know where his problem is, is it a problem with orbital data? Please answer this question for me, thank you!
