### ISSUE TITLE
StackSentinel with download recents orbits

### ISSUE THREAD

**Issue by alejobeap** [isce-framework/isce2#270]
Dear
I'm trying with my orbits backup and download the orbit for the 20210405 and 20210411 (according to the issue #267)  but I had the error when I run the stack:
stackSentinel.py -s /mnt/datos_sentinel/Datos_Sentinel1/Sangay/Descendente/SLC/ -d /mnt/procesamiento/Procesamiento_Sentinel/Sangay/Stack_Descendente/DEM/demLat_S03_S01_Lon_W079_W077.dem.wgs84 -a /mnt/procesamiento/Procesamiento_Sentinel/Sangay/Stack_Descendente/Auxdir -o /mnt/procesamiento/Procesamiento_Sentinel/Sangay/Stack_Descendente/orbits -n '3 2' -C NESD -b '-2.08 -1.93 -78.40 -78.28' -W interferogram

writing /mnt/procesamiento/Procesamiento_Sentinel/Sangay/Stack_Descendente/run_files/run_1_unpack_slc_topo_master
Traceback (most recent call last):
File "/home/insar/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 736, in
main()
File "/home/insar/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 719, in main
interferogramStack(inps, acquisitionDates, stackMasterDate, slaveDates, safe_dict, pairs, updateStack)
File "/home/insar/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 531, in interferogramStack
i = slcStack(inps, acquisitionDates, stackMasterDate, slaveDates, safe_dict, updateStack)
File "/home/insar/instaladores/isce2/contrib/stack/topsStack/stackSentinel.py", line 438, in slcStack
runObj.unpackSlavesSLC(stackMasterDate, slaveDates, safe_dict)
File "/home/insar/instaladores/isce2/contrib/stack/topsStack/Stack.py", line 328, in unpackSlavesSLC
configObj.orbit_type = safe_dict[slave].orbitType
The error
![image](https://user-images.githubusercontent.com/65787135/114560369-3ff12c00-9c32-11eb-9096-fed50338493a.png)

My Sentinel data
![image](https://user-images.githubusercontent.com/65787135/114560978-c6a60900-9c32-11eb-9398-bbebfa792b70.png)

My backup orbits
![image](https://user-images.githubusercontent.com/65787135/114560771-965e6a80-9c32-11eb-8830-f7fc329fc6e1.png)

20210405 orbits
![image](https://user-images.githubusercontent.com/65787135/114560853-ac6c2b00-9c32-11eb-8880-0c620a410ca6.png)

20210411 orbits
![image](https://user-images.githubusercontent.com/65787135/114560892-b4c46600-9c32-11eb-81c9-0d73465c6baa.png)

Thanks for your help

**Comment by alejobeap** [comment]
And also I had the same problem of the issue #268 when the stack was working
Thanks for your help

**Comment by RussellGrew** [comment]
Maybe the solution is in https://github.com/isce-framework/isce2/issues/267

Also you seem to be running a pretty old version of ISCE? An upgrade may help.

Looking at `-o /mnt/procesamiento/Procesamiento_Sentinel/Sangay/Stack_Descendente/orbits` in my version of this folder I have all the orbits at the top level and not in dedicated sub folders. Certainly I have had to manually download some orbits for the past few weeks. 

Good luck.

**Comment by RussellGrew** [comment]
For the community, was it the orbits folder?

**Comment by bjmarfito** [comment]
@RussellGrew, you may use the orbits folder or you may specify a different folder containing the orbit files using the -o option.
