### ISSUE TITLE
stripmapStack geom_reference/los.rdr incorrect scheme

### ISSUE THREAD

**Issue by EJFielding** [isce-framework/isce2#277]
When running stripmapStack on UAVSAR data, the multilooked `geom_reference/los.rdr` is created in BSQ file scheme, but the `los.rdr.xml` file is set to scheme BIP.
This is run setup I used:
```
stackStripMap.py -s SLC/ -d /u/sar-r0/fielding/Calif/SF_Bay/topo/USGS/1_3asec/BayArea_USGS_13.dem.wgs84 -a 8 -r 2 -W interferogram --filter_strength 0.2 --nofocus -S uavsar_stack -t 350
```
﻿
My version of ISCE2 is compiled with:
`GDAL 3.1.4, released 2020/10/20`

**Comment by geniusinaction** [comment]
I see the same thing, running stripmapStack on Envisat data. There is a 'tiled' pattern to the angle values in los.rdr which obviously messes up my troposphere corrections and the like when I import the data into MintPy. See 3 and 4 here:

![Screenshot 2021-06-17 14 06 27](https://user-images.githubusercontent.com/6486830/122472518-8ede7900-cf75-11eb-8dee-bb7142a18d96.png)

I cloned the repo a few days ago, so this is a 'current' issue.

Processing an individual pair with the same reference image in stripmapApp does not have this problem, so is there a code snippet I can copy from one to the other that fixes this?

**Comment by EJFielding** [comment]
I forget exactly what I did, but I think you can hand-edit the `los.rdr.xml` file and change the scheme to BSQ so that MintPy reads it correctly. You have to remove the MintPy `.rsc` files and `.h5` files to get it to re-read everything.

**Comment by geniusinaction** [comment]
Can confirm that changing 'BIP' to 'BSQ' in los.rdr.xml seems to mitigate the problem, even if it doesn't fix it at source.

Can also confirm that grepping for 'BIP' in the contrib/stack/stripmapStack directory doesn't turn up anything that looks like it might be to blame...
