### ISSUE TITLE
Zero sized isce.log gets created upon conda environment activation

### ISSUE THREAD

**Issue by scottstanie** [isce-framework/isce2#281]
Whenever my conda environment activates, it makes an empty `isce.log` file.

```bash
(mapping) scott:isce2$ mkdir emptydir && cd emptydir
(mapping) scott:emptydir$ ls
(mapping) scott:emptydir$ conda activate mapping
(mapping) scott:emptydir$ ls
isce.log
```
This means that every new window I open where my `~/.bash_profile` activates conda, I get a new file.

I haven't dug in to figure out if's from this line in the FileWriter init https://github.com/isce-framework/isce2/blob/main/components/iscesys/StdOEL/src/FileWriter.cpp#L20 or if it's just a setting for python's `logging`...  It looks like this problem was once fixed here:
https://github.com/isce-framework/isce2/pull/140
but was overwritten (possibly accidentally?) in this commit
https://github.com/isce-framework/isce2/commit/88def96714688f724913f4b8ebc926b0890055af

**Comment by rtburns-jpl** [comment]
I think this is a good suggestion, and it does look like the change to logging.conf was accidental, possibly due to a merge conflict. Maybe @falkamelung can confirm; I'd be in favor of this fix.

**Comment by scottstanie** [comment]
Ok I see now that the file is created from the "delay" argument of a `RotatingFileHandler` being set to false. When `delay=True`, it doesn't create a file until the first logging call is emitted, and it should avoid the empty files.

https://docs.python.org/3/library/logging.handlers.html#logging.handlers.RotatingFileHandler

I opened #293 to revert the argument change.
