### ISSUE TITLE
Reducing dependencies for basic isce2 installation

### ISSUE THREAD

**Issue by scottyhq** [isce-framework/isce2#284]
Mirroring an issue I opened up in the conda-forge feedstock repository because it's probably actually in this repository where dependencies are defined https://github.com/conda-forge/isce2-feedstock/issues/38. A fresh install of isce2 from conda-forge results in a whopping `Total:       588.9 MB` of downloaded packages. I think that many of these should be considered 'optional' depending on the workflow you're interested in, and some of them could probably simply be removed resulting in smoother installation:
```
ffmpeg-4.3.1               |       hca11adc_2        91.9 MB  conda-forge
qt-5.12.9                  |       hda022c4_4        99.5 MB  conda-forge
```
As far as I can tell, other libraries are tied to specific isce2 apps (like `py-opencv` for autorift). If these are just runtime dependencies for specific apps I'd argue that they could be omitted from the main isce2 package? I'm guessing there is some complication here with scons where these libraries are actually used to build the conda-forge distribution... but not sure. 

In any case, reduced dependencies would be nice for folks who are just using a single isce2 app like topsApp.py. see also #275

**Comment by rtburns-jpl** [comment]
I think this is more of a packaging issue than an isce2 issue, since isce2's build system is already capable of detecting which dependencies are available and building the correct subset of modules which are supported. So I'll close this here and follow up in the linked issue.
