### ISSUE TITLE
geocode from stripmapApp

### ISSUE THREAD

**Issue by scottstanie** [isce-framework/isce2#294]
I'm using `stripmapApp.py` with two UAVSAR_HDF5_SLC data takes:

SanAnd_23511_14068_001_140529_L090_CX_143_02.h5
SanAnd_23511_14128_002_140829_L090_CX_143_02.h5

Everything runs fine to generate and unwrap the interferograms, but the geocoding step seems to be outputing a mirror of the correct data:

<img width="601" alt="image" src="https://user-images.githubusercontent.com/8291800/119748151-dcc1fe80-be59-11eb-80b3-db19da6e12a6.png">

I can correctly geocode the `.unw` file when I use GDAL, either manually, or using the `geocodeGdal.py` script
`gdalwarp -of ENVI -geoloc  -te -122.57166666666667 38.08277777777778 -121.56611111111111 38.72361111111111  -tr 0.0003 0.0003 -srcnodata 0 -dstnodata 0  -r near /data7/jpl/sanAnd_23511/testint/filt_topophase.unw.vrt /data7/jpl/sanAnd_23511/testint/filt_topophase3.unw.geo`

<img width="601" alt="image" src="https://user-images.githubusercontent.com/8291800/119748159-e2b7df80-be59-11eb-8244-dd9c1a9749f7.png">

I'm not sure if it's related to #277 , since this is also using UAVSAR data, but not using `stripmapStack`.

**Comment by rtburns-jpl** [comment]
At a glance it looks like the data is mirrored along the flight path. Maybe the geocoder is not properly truncating positions corresponding to an incorrect look direction?

**Comment by hfattahi** [comment]
How do you display the geocoded unwrpped from stripmapApp? Note that it has two bands. While the one from geocodeGdal may have one band.

**Comment by scottstanie** [comment]
That screenshot was in QGIS, but the same shows from plotting with GDAL/rasterio in Python:

```python
﻿﻿In [13]: with rasterio.open("filt_topophase.unw.geo") as src:
    ...:     amp = src.read(1)
    ...:     phase = src.read(2)
    ...:
In [14]: fig, axes = plt.subplots(1, 2)
In [15]: axes[0].imshow(np.log(amp)); axes[1].imshow(phase)
```
<img width="718" alt="image" src="https://user-images.githubusercontent.com/8291800/119867900-00318b80-bee4-11eb-8439-504758aee979.png">

**Comment by piyushrpt** [comment]
geo2rdr needs a check to see what side of the track the target point is on. This is not an issue with spaceborne data. Could become an issue with airborne lines with horizontal headings - since we use a simple bbox to determine geocoding extent.

**Comment by scottstanie** [comment]
Ok I see- the flight path was right down the middle of the two mirrored images, and, athough it was flying towards the southwest and left-looking, the image in the top left was formed since those would be the zero-Doppler points if it was right-looking. 
I think I get conceptually how you would check for this: finding the azimuth angle from ground point to satellite lat/lon point, then checking if that's greater/less than the aircraft heading angle for left/right looking platforms.

I'm not sure which place would be the preferred code location to tinker with to add this check
Were you imagining something getting added to `geo2rdr.f90`? Or elsewhere before/after?

**Comment by piyushrpt** [comment]
Your post filtering approach would work nicely. Also (target_xyz - midsat_xyz) .dot. midsat_vxyz should let you determine the side on which target lies at the very start before needing to solve anything. You could just try and add a check up first - in geo2rdr and geocode both.

**Comment by scottstanie** [comment]
Hmm, I was trying to come up with some way to just take a dot product, but unless I'm drawing this wrong, don't the two points on the left (green) and right (red) of the platform give the same dot product, since the two theta angles are the same?

<img width="718" alt="image" src="https://user-images.githubusercontent.com/8291800/120548298-d383e500-c3b7-11eb-979e-1ed2b39f847b.png">

I was thinking that the check could be done by converting the `(target_xyz - midsat_xyz) ` vector into TCN coordinates, so that if the C coordinate is positive (negative), the target is on the left (right)

**Comment by gmgunter** [comment]
In the isce3 implementation of `geo2rdr`, there's a [sanity check](https://github.com/isce-framework/isce3/blob/0eb175f86f6c74d86c19ba9623f23054513fc657/cxx/isce3/geometry/detail/Geo2Rdr.icc#L83-L89) that compares the radar look side with the sign of  <img src="https://render.githubusercontent.com/render/math?math=(\vec{r}\times\vec{v})\cdot\vec{p}">, where `r` is the (platform-to-target) slant range vector, `v` is the platform velocity vector, and `p` is the platform position vector. If the sign is positive, the target is on the left side of the track. 

This is conceptually very similar to your suggestion of checking the C coordinate of the slant range vector in TCN coords, and perhaps a bit simpler to compute.

**Comment by scottstanie** [comment]
oh awesome, thanks @gmgunter . I'll see about how to add in the analogous check to `geo2rdr`

**Comment by piyushrpt** [comment]
Oops ... yes cross product is the right one ... Thanks @gmgunter

**Comment by scottstanie** [comment]
I have something in my branch #302 that seems to be checking the pixel side correctly now.

<img width="507" alt="image" src="https://user-images.githubusercontent.com/8291800/121937648-85080c00-cd10-11eb-9c9b-fdd4ee2f7d3f.png">

I realized the geocoding step was in `geozero`, not geo2rdr.  I couldn't tell if `geo2rdr`, which has a very similar structure, also needed this look side check.
