### ISSUE TITLE
Higher no. of default azimuth looks compared to range looks in alosStack processor.

### ISSUE THREAD

**Issue by bjmarfito** [isce-framework/isce2#311]
I've noticed that the default no. of azimuth looks is higher compared to range looks in alosStack processor even though the range has finer pixel spacing than the azimuth. The default value of azimuth look is 28 while for range look is 5.

Are the no. of looks normal for InSAR processing of ALOS-2 data?

**Comment by bjmarfito** [comment]
Checked the pixel spacing. The processing parameters are probably correct.

I'll close this issue. Sorry for the noise.

**Comment by EJFielding** [comment]
HI @bjmarfito, you did not say what mode of ALOS-2 data you are using, but I assume it is the ScanSAR (WD1) mode. The ALOS-2 ScanSAR SLC images that are processed with "full aperture" mode are highly oversampled in azimuth. The actual azimuth resolution is around 50 meters, but the azimuth line spacing is around 3 meters. The `alosStack` and `alos2App` processors both have a default to take 14 azimuth looks as they form the interferograms (specified by the `looks1` parameters) that averages in the azimuth direction to get closer to the actual resolution. You should think of these as only removing the oversampling. Then in the later steps of processing, the default `looks2` looks for the ScanSAR mode are 2 additional azimuth looks and 5 range looks to get pixels that are approximately square with about 80 meter pixel size with a total of 28 azimuth looks and 5 range looks from the original SLC spacing.

**Comment by bjmarfito** [comment]
Ah ok I get it now because I'm wondering before why the azimuth look is greater than range look in `alos2App.py` workflow. Thank you @EJFielding. 

Yes you're correct, I've used ALOS-2 ScanSAR data to generate the interferogram.
