### ISSUE TITLE
Throwing exceptions instead of `exit(1)` in GDALAccessor.cpp

### ISSUE THREAD

**Issue by scottstanie** [isce-framework/isce2#312]
Currently when you misspell a file, or try to open an existing file while in a directory other than the base directory, it calls

```
#define ERR_MESSAGE cout << "Error in file " << __FILE__ << " at line " << __LINE__  << " Exiting" <<  endl; exit(1);
```
in `GDALAccessor.cpp` and does a hard shutdown of the python interpreter.

If my base directory was /data7/jpl/sanAnd_23511_143A/:
```
$ ls -1 /data7/jpl/sanAnd_23511_143A/
20140529_slc
20140529_slc.xml
20140829_slc
20140829_slc.xml
catalog
coregisteredSlc
...
```

and I start a python interpreter, change to a new folder within that:

```python
In [6]: cd test_igram_form/
/data7/jpl/sanAnd_23511_143A/test_igram_form
```

then opening and creating a SlcImage will end in a hard crash:

```python
In [1]: import isce, isceobj
In [2]: imageSlc1 = isceobj.createImage()
In [3]: imageSlc1.load('../20140529_slc/20140529.slc.xml')

In [9]: objSlc1 = isceobj.createSlcImage()

In [10]: from iscesys.ImageUtil.ImageUtil import ImageUtil as IU
In [11]: IU.copyAttributes(imageSlc1, objSlc1)
Out[11]: <isceobj.Image.SlcImage.SlcImage at 0x7fa63780ad30>

In [12]: objSlc1.setAccessMode("read")

In [13]: objSlc1.createImage()
GDAL open (R): 20140529_slc/20140529.slc.vrt
ERROR 4: 20140529_slc/20140529.slc.vrt: No such file or directory
Error. Cannot open the file 20140529_slc/20140529.slc.vrt in read mode.
Error in file /home/scott/repos/isce2/components/iscesys/ImageApi/InterleavedAccessor/src/GDALAccessor.cpp at line 77 Exiting
(mapping) [scott@lidar test_igram_form]$
```

Is this something that people don't run into that often, and therefore hasn't been a problem? I can see that the `ERR_MESSAGE` macro is used a lot, but I'm not sure if there's a reason to `exit(1)` on error, or if it's just been around for awhile and hasn't been worth the effort to change.

I was testing possible fixes in a branch 
https://github.com/scottstanie/isce2/compare/uavsar-nisar-stack...scottstanie:binding-exceptions?expand=1 (this just compares it to another branch of mine to show only the bindings/c++ changes)

The two places for changes are in the GDALAccessor module:

```cpp
        if ((*fd) == NULL)
        {
            string errMsg = "Cannot open the file " + filename + " in "
                            + accessMode + " mode.";
            throw runtime_error(errMsg);
            // ERR_MESSAGE
            // ;
        }
```

and in the `DataAccessormodule.cpp` bindings, the line
```cpp
ptDataAccessor = (uint64_t) AF->createAccessor(filename, filemode, size,
        bands, width, scheme);
```

changes to catch the thrown exception:

```c++
try
  {
    ptDataAccessor = (uint64_t) AF->createAccessor(filename, filemode, size,
        bands, width, scheme);
  }
  catch(const std::exception& e)
  {
    PyErr_SetString(PyExc_OSError, e.what());
    return NULL;
  }
```

When I add these, I get this:

```python
In [13]:     objSlc1.createImage()
GDAL open (R): 20140529_slc/20140529.slc.vrt
ERROR 4: 20140529_slc/20140529.slc.vrt: No such file or directory
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-13-21bae87193b5> in <module>
----> 1 objSlc1.createImage()

~/repos/isce2/install/packages/isce/components/isceobj/Image/SlcImage.py in createImage(self)
     78     def createImage(self):
     79         self.checkInitialization()
---> 80         Image.createImage(self)
     81
     82     def updateParameters(self):

~/repos/isce2/install/packages/isce/components/isceobj/Image/Image.py in createImage(self)
    297     # # as mandatory are not set, an exception is thrown.
    298     def createImage(self):
--> 299         self.createAccessor()
    300         da = self.getAccessor()
    301

~/repos/isce2/install/packages/isce/components/iscesys/ImageApi/DataAccessorPy.py in createAccessor(self)
    165                 print('Cannot select appropruiate image API')
    166                 raise Exception
--> 167             self._accessor, self._factory = DA.createAccessor(
    168                 filename, self.accessMode, size, self.bands,
    169                 self.width,scheme,caster,self._extraInfo

OSError: Cannot open the file 20140529_slc/20140529.slc.vrt in read mode.

In [14]:

```

I'm wondering whether changes like this would be appreciated, or whether people are fine with the current behavior.

**Comment by rtburns-jpl** [comment]
Thanks for the detailed writeup! Handling the exception seems like much more graceful behavior to me.

> Is this something that people don't run into that often, and therefore hasn't been a problem?

Maybe. It's also possible that most people use non-interactive workflows that don't care whether errors are handled cleanly. But if this is affecting you, I'd be happy to review a PR switching over to the exception-based behavior. The changes you linked look nice and simple to me.

**Comment by scottstanie** [comment]
Ok that makes sense that people mostly use the pre-made workflows more than tinkering with the components interactively. I was doing a bit more interactive while figuring out some new additions to the stripmap stack workflow.

I'll `git cherry-pick` the relevant commits and submit a PR.
