### ISSUE TITLE
Staging an Ellipsoid Corrected DEM for TopsApp

### ISSUE THREAD

**Issue by cmarshak** [isce-framework/isce2#329]
This was solved thanks to @EJFielding (also thanks to Grace Bato, David Bekaert, and Simran Sanga to help me get it straight).

As expert ISCE users know, if you use the field `demFilename` in the topsApp XML, it needs to be an [ISCE formatted raster](https://gdal.org/drivers/raster/isce.html).

My problem was that my DEM was in WGS84 height, but ISCE2 kept correcting the heights as if it were in EGM08 (the geoid that SRTM is in).

I couldn't find this in the documentation anywhere, but Eric knew how to do this - so I am putting this here for future reference.

If you want to use an Ellipsoid corrected DEM for Topsapp - there is a property in the metadata XML of the raster (ISCE formatted rasters have XML and binary files similar to ENVI) to indicate to ISCE2 if it needs to do additional correction. I believe in older versions of ISCE2, they determined this based on the suffix `*.wgs84` - though am not sure.

So, the XML needs

```
<imageFile>
<property name="reference">
        <value>WGS84</value>
        <doc>Geodetic datum</doc>
</property>
...
</imageFile>
```
appended to it.

To confirm, @dbekaert noted these lines of code: https://github.com/isce-framework/isce2/blob/main/components/isceobj/TopsProc/runVerifyDEM.py

Rough idea in python 

```
from lxml import etree

tree = etree.parse(xml_metadata_path)
root = tree.getroot()

wgs84_prop = etree.Element("property", name='reference')
etree.SubElement(wgs84_prop, "value").text = "WGS84"
etree.SubElement(wgs84_prop, "doc").text = "Geodetic datum"

root.insert(0, wgs84_prop)

with open(xml_fr, 'wb') as file:
    file.write(etree.tostring(root_fr, pretty_print=True))
```

Still not perfect, but provides a rough idea.

Hopefully will be google-able now and searchable in Github. Sorry if this is redundent.

**Comment by dbekaert** [comment]
Thank you @cmarshak for documenting.

**Comment by tonianr** [comment]
Hi, @cmarshak do you know how to use generate a DSM from LiDAR .las files to the format acceptable in ISCE2 stripmapstack processing? I know how to create DSMs from my raw LiDAR data but I'm not sure what format generate in ArcGIS for ISCE2 and what scripts to use. Here is the information on the data I'm downloading:
![image](https://user-images.githubusercontent.com/78233913/134379469-c52bcb6a-09d0-4347-b1ef-baf56053066b.png)

I have the option of choosing vertical datum: WGS84/ITF94 Ellipsoid and Geoids 03, 18, 12A, 12B, 09, 99. 
since the Earthdata forum has been down I'm finding it extremely hard to find solutions, any help will be appreciated.

**Comment by EJFielding** [comment]
Hi @tonianr, the ISCE2 processing expects the DEM to be in WGS84 Ellipsoid vertical datum. If you can get your DEM generated with ellipsoid heights instead of geoid, then it will be what you need for ISCE2.

**Comment by tonianr** [comment]
@EJFielding Thank you, would ISCE2 recognize the DEM as a .tif file? Or is there a specific format that I should be using?

**Comment by EJFielding** [comment]
There are ways to use a GeoTIFF file as a DEM in ISCE2 if you create the necessary .xml and .vrt files, but you are better off converting it to a standard ISCE raster format with the GDAL `gdal_translate -of ISCE` command.

**Comment by yunjunz** [comment]
Nice discussion. I would recommend the `isce-2` repo maintainer enable the `Discussions` tab so that this "non-code-commit" type of discussion/documentation could be located there and is easier to find for users.

**Comment by rtburns-jpl** [comment]
You read my mind @yunjunz, I've been talking to the other isce2 maintainers about that this morning. I'll go ahead and press the button.

**Comment by tonianr** [comment]
> There are ways to use a GeoTIFF file as a DEM in ISCE2 if you create the necessary .xml and .vrt files, but you are better off converting it to a standard ISCE raster format with the GDAL `gdal_translate -of ISCE` command.

Thank you, @EJFielding I used a DEM that I downloaded from NOAA for my ISCE2 stripmapstack processing.

Steps for anyone looking to do the same:
![image](https://user-images.githubusercontent.com/78233913/134782363-5cb14df4-1519-499a-9a1b-45fa0a959436.png)

**Comment by EJFielding** [comment]
@tonianr I started a new discussion on the Discussion section about this. Because this issue is closed, it is not so easy for people to find the discussion here.

**Comment by tonianr** [comment]
Ok I will add my follow up there @EJFielding

**Comment by EJFielding** [comment]
I was also going to point out that I don't think what you posted is correct. It looks like you are converting to the EGM96 geoid heights, but ISCE2 expects the WGS84 ellipsoid heights.

**Comment by tonianr** [comment]
> I was also going to point out that I don't think what you posted is correct. It looks like you are converting to the EGM96 geoid heights, but ISCE2 expects the WGS84 ellipsoid heights.

@EJFielding I'll update it on the new discussion when I've converted to ISCE2 format instead of SRTM format!
