### ISSUE TITLE
Bugs in GPU modules

### ISSUE THREAD

**Issue by gj313** [isce-framework/isce2#331]
when I build the codes and run topsApp.py on my GPU devices, 
errors "out of memory" and "no kernel image is available for execution on the device" occur in the GPUtopozero module.
A similar problem also exists in the GPUgeo2rdr module.

I modified the file components/zerodop/GPUtopozero/src/Topo.cpp, 
long pixPerImg = (((num_GPU_bytes / 8) / 9) / 1e7) * 1e7; // Round down to the nearest 10M pixels
with
long pixPerImg = 4096*4096; //(((num_GPU_bytes / 8) / 9) / 1e7) * 1e7; // Round down to the nearest 10M pixels ;
and put 
SET_PROPERTY(TARGET GPUgeo2rdr/GPUtopozero PROPERTY CUDA_ARCHITECTURES 50)
into the CMakeLists.txt files.

Then rebuild the codes, the problems disappear.

**Comment by rtburns-jpl** [comment]
Interesting, looks like we are trying to use all the memory on the GPU which fails when anyone else is also using the GPU's memory. Hardcoding 4096*4096 doesn't look ideal either.

What if you change this line to `return freeByte;`? Seems like that would tell it to only use what memory is available.
https://github.com/isce-framework/isce2/blob/def109815df5f724c5dc653878314577e3505c48/components/zerodop/GPUtopozero/cuda/gpuTopo.cu#L597

**Comment by lijun99** [comment]
"no kernel image is available for execution on the device" is usually associated with an incorrect CUDA Architecture(s) being used for compiling. CUDA 11 uses sm_52 as default; therefore, your sm_50 device is out of luck unless you specify it explicitly, as @rtburns-jpl pointed out.  ``-DCMAKE_CUDA_ARCHITECTURES`` for new versions of cmake, for old cmake version, use ``-DCMAKE_CUDA_FLAGS=sm_50`` instead.

**Comment by zhuhaxixiong** [comment]
i also meet this error during topsApp geo2rdr process,can you give me some advice,i use scons to compile isce with GPU

**Comment by lijun99** [comment]
The developer for these gpu modules has left JPL. I might be able to check how to fix this, but there is no guarantee. GPU modules are not officially supported by ISCE2, but as I understand, will be supported by ISCE3. For now, if you don't have a workstation grade GPU(>=8G memory), please use CPU modules instead. 

For the "no kernel image is available for execution on the device" error, as mentioned above, you need to specify the CUDA architecture. With cmake, it's ``-DCMAKE_CUDA_ARCHITECTURES``. With scons, you need to modify the ``scons_tools/cuda.py`` file, by adding ``-arch=sm_xx`` to ``env['ENABLESHAREDNVCCFLAG'] = '-std=c++11 -shared -Xcompiler -fPIC'``.

**Comment by zhuhaxixiong** [comment]
i try to compile isce with scons by adding **-arch=sm_50** to **env['ENABLESHAREDNVCCFLAG'] = '-std=c++11 -shared -Xcompiler -fPIC'** in scons_tools/cuda.py. and test gpu by running topsApp.py   
![image](https://user-images.githubusercontent.com/28261361/142094514-51b86e24-6e1f-4323-95ca-daf7d2a5e029.png)
the error occurs in TOPO shows as the picture:
  Loading slantrange and doppler data...
    Allocating host and general GPU memory...
    Copying general memory to GPU...
    Allocating block memory (88390897 pixels per image)...
    (NOTE: There will be 47 'empty' threads per image block).
    Starting GPU Topo for block 0...
    **Sync kernel error: out of memory
    Async kernel error: an illegal memory access was encountered**
    GPU finished block 0 in 0.004391 s.
    Copying memory back to host...
    GPU finished block 0 (with memory copies) in 0.211855 s.
    Cleaning device memory and returning to main Topo function...
  Writing block 0 out (asynchronously) to image files...
    Loading slantrange and doppler data...
    Allocating host and general GPU memory...
    Copying general memory to GPU...
    Allocating block memory (88390897 pixels per image)...
    (NOTE: There will be 47 'empty' threads per image block).
    Starting GPU Topo for block 1...
    **Sync kernel error: all CUDA-capable devices are busy or unavailable
    Async kernel error: all CUDA-capable devices are busy or unavailable**
    GPU finished block 1 in 0.000007 s.
    Copying memory back to host...
    GPU finished block 1 (with memory copies) in 0.000027 s.
    Cleaning device memory and returning to main Topo function...
does this mean that gpu mould was bad and i can not use GPU mould on my computer! 
finally topsApp also have an erro:
![image](https://user-images.githubusercontent.com/28261361/142096865-66f1e3cf-bc5b-4299-bd5e-4c8579d30c85.png)
my gpu decvice is GTX10606G,my cuda version is 11.4
![image](https://user-images.githubusercontent.com/28261361/142095002-06fcec32-4d88-4400-91e4-b7c41402013a.png)
 and then i trt to build isce with cmake  in  the build directory i create  by:
 cmake .. -DCMAKE_INSTALL_PREFIX=/home/leslie-zhu/SoftWare/isce2/install -DCMAKE_CUDA_ARCHITECTURES=50
and a cmake warning occurs:
![image](https://user-images.githubusercontent.com/28261361/142095405-bdd881d3-2813-48e6-a669-8bf077c0e028.png)
in the last anoter camke warning occurs:
![image](https://user-images.githubusercontent.com/28261361/142095529-f92135f2-1f1e-47ec-9de8-6f93b71e040d.png)
my cmake version is 3.16.3

**Comment by lijun99** [comment]
I just took a look at the gpuTopo code and it is written in terms of double precision (DP). Therefore, the code is only suitable for Tesla GPUs such as K40, P100, V100, ...;  almost all gaming and graphical workstation cards have limited DP support. Of course, it's arguable whether single precision will suffice but it requires detailed comparison and a final decision by the ISCE team. For now, I am sorry that you may need to stick to CPU modules only.   

If you do have a Tesla GPU, here is a detailed instruction to install ISCE2 with CUDA modules, https://github.com/lijun99/isce2-install. `CMAKE_CUDA_ARCHITECTURES` is not supported by cmake 3.16, you may need to upgrade cmake or use `CMAKE_CUDA_FLAGS` to pass the architecture option(s).

**Comment by zhuhaxixiong** [comment]
THANKS FOR YOUR REPLY !

**Comment by lijun99** [comment]
I have patched GPUgeo and GPUtopo modules, to use the max free GPU memory available. I have tested on two gaming cards (with 2G and 12G mem) and it seems that the program runs reasonably fast, even though they have limited double precision support. 

If likely, please try it out before I submit a merge request. 
https://github.com/lijun99/isce2/tree/gpu

**Comment by zhuhaxixiong** [comment]
thanks for your your help.i will try it , and i wonder isce can generate a DEM from inteferogram?
