### ISSUE TITLE
How can I present the unw ifgs?

### ISSUE THREAD

**Issue by PeymanPython** [isce-framework/isce2#333]
Hello Guys,
I have performed all the run_files(16 cases) successfully and now want to show the unwraped interferograms, but not sure if I am running the right code and files! because I came across the following error:

(insar) user@user-B250-HD3:~/tools/MirAhmad/merged/interferograms/20200110_20200122$ mdx.py filt_fine.unw.conncomp
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
Running: mdx filt_fine.unw.conncomp -s 3181 -ch1 -i1  
sh: 1: mdx: not found

![Screen](https://user-images.githubusercontent.com/55481769/132464175-00849622-f485-4d29-acf6-f0b7c30c9d34.png)

**Comment by geniusinaction** [comment]
Is mdx on your path?

**Comment by PeymanPython** [comment]
@geniusinaction 
Many thanks for your reply.
Do you mean I should write an address in the .bashrc file? Cold you write me an example?

Best,
Peyman

**Comment by geniusinaction** [comment]
Yes in your .bashrc, or in a script that you source before you run the processing. What the exact command should be depends where mdx is located, which can differ depending on whether you compiled it yourself, or installed it via conda/conda-forge.

For conda installs, mdx can be found in $ISCE_HOME/bin, so the command would be something like

> `export PATH=$PATH:$ISCE_HOME/bin`

and if you compiled it yourself, substitute the path to your mdx executable for the $ISCE_HOME/bin part.

**Comment by PeymanPython** [comment]
@geniusinaction 
Thanks a lot, now it works properly without any error.
