### ISSUE TITLE
PyCuAmpcor not compiling with cmake

### ISSUE THREAD

**Issue by geniusinaction** [isce-framework/isce2#334]
Being the owner of a gleaming new RTX 3090 GPU, I have been trying to see how much faster my processing tasks might run. This is fun!

I followed @lijun99 's great instructions for the cmake compilation (https://github.com/lijun99/isce2-install) and it compiled without complaints. (I could not get it to compile fully under scons.) 

topsApp.py also ran well, at least at first. GPUtopozero and GPUgeo2rdr ran just fine (and quickly!) But as soon as I tried to run denseoffsets, the rails came off:

>Running step denseoffsets
>Traceback (most recent call last):
>  File "/home/gareth/miniconda3/envs/isce2+/bin/topsApp.py", line 1077, in <module>
>    insar.run()
>  File "/home/gareth/miniconda3/envs/isce2+/lib/python3.8/site-packages/isce/components/iscesys/Component/Application.py", line 142, in run
>    exitStatus = self._processSteps()
>  File "/home/gareth/miniconda3/envs/isce2+/lib/python3.8/site-packages/isce/components/iscesys/Component/Application.py", line 405, in _processSteps
>    result = func(*pargs, **kwargs)
>  File "/home/gareth/miniconda3/envs/isce2+/lib/python3.8/site-packages/isce/components/isceobj/TopsProc/Factories.py", line 40, in __call__
>    return self.method(self.other, *args, **kwargs)
>  File "/home/gareth/miniconda3/envs/isce2+/lib/python3.8/site-packages/isce/components/isceobj/TopsProc/runDenseOffsets.py", line 26, in runDenseOffsets
>    runDenseOffsetsGPU(self)
>  File "/home/gareth/miniconda3/envs/isce2+/lib/python3.8/site-packages/isce/components/isceobj/TopsProc/runDenseOffsets.py", line 144, in runDenseOffsetsGPU
>    from contrib.PyCuAmpcor import PyCuAmpcor
>ModuleNotFoundError: No module named 'contrib.PyCuAmpcor'

Looking closely, there is no compiled library file for PyCuAmpcor in my build directory

>\> ls isce2/build/components/contrib/PyCuAmpcor/
> CMakeFiles  cmake_install.cmake  CTestTestfile.cmake  Makefile

...so it really isn't there to be imported! I am able to compile the standalone package, per the instructions (https://github.com/lijun99/cuAmpcor), so it's not a case that it won't compile, it just isn't compiling with isce.

I presume it's a cmake issue(?) but cannot easily parse what those files are saying!

**Comment by rtburns-jpl** [comment]
Hey, sorry you're having trouble with it. This is probably due to the cmake rule for PyCuAmpcor which "helpfully" skips building the module if its dependencies aren't available:

https://github.com/isce-framework/isce2/blob/9f9e2e89fc2924d58c253bd7b08cc507e6892e86/contrib/PyCuAmpcor/CMakeLists.txt#L1-L7

Can you post your cmake configure log? Most likely one of these isn't installed or wasn't detected properly.

**Comment by lijun99** [comment]
Most likely pybind11 is missing, which can be installed by ``conda install pybind11``. @rtburns-jpl has recently updated PyCuAmpcor to use pybind11 wrapper while I haven't update my guide about that yet.

**Comment by geniusinaction** [comment]
I installed pybind11, and now `cmake' and `make install' result in multiple lines of output describing all the various PyCuAmpcor files that it has managed to compile, it happily reports 

>[ 87%] Built target PyCuAmpcor

...and when I run dense offsets in topsApp.py now, it runs to the end, and really quickly. So I think the issue is fixed.

Thanks for the assistance!

**Comment by zhuhaxixiong** [comment]
i compile isce with cuda bt scons ,after scons in terminal this error occurs:
PycuAmpcor/src/cuCorrNormalizer.cucuAmpcorParameter.cu not found
ubuntu 20.04  cuda 11.4 isce 2.5.3

**Comment by zhuhaxixiong** [comment]
i compile isce with cuda bt scons ,after scons in terminal this error occurs:
PycuAmpcor/src/cuCorrNormalizer.cucuAmpcorParameter.cu not found
ubuntu 20.04  cuda 11.4 isce 2.5.3

**Comment by lijun99** [comment]
Missing a comma at the end of https://github.com/isce-framework/isce2/blob/main/contrib/PyCuAmpcor/src/SConscript#L14. 

If you don't want to wait for commit, please add the comma by yourself. 

Sorry, haven't used scons for a long time!
