### ISSUE TITLE
ALOS 1 LEVEL1.0 timeseriers

### ISSUE THREAD

**Issue by zhuhaxixiong** [isce-framework/isce2#339]
i download ALOS1 1.0 data from ASF to do timesserisers by stackstripmap ,when i unpack the zip and generate SLC folder i use  stackStripMap.py -s /media/leslie-zhu/D/MAHZANGFENG/SLC -d /media/leslie-zhu/D/MAHZANGFENG/DEM/demLat_N04_N06_Lon_E095_E097.dem.wgs84 -W inteferogram -x '4.43 5.30 95.56 96.40' -m 20080916 -t 500 -b 10000 -a 5 -r 4 -S ALOS -u snaphu  
and my  -W  was set to interferogram ,but the run_file is empty,how i can do the next step in mintpy?maybe the new version  add the alosSatck process ,does i can solve this problem?

**Comment by zhuhaxixiong** [comment]
easy problem by careless

**Comment by volter29** [comment]
> easy problem by careless

Hi @zhuhaxixiong 
I ran into this error but I can't quite understand where my erurr is. Could you give me a hand? I would be grateful.
Thank you

stackStripMap.py -s /media/calderone/DATADRIVE5/elaborazione_ravenna/ascendente/SLC -d /media/calderone/DATADRIVE5/elaborazione_ravenna/dem/DEM/demLat_N44_N45_Lon_E011_E013.dem.wgs84 -x '44.3642 44.4067 12.1753 12.2512' -t 500 -b 260 -a 2 -r 2 --nofocus -W slc -z --useGPU --summary
