### ISSUE TITLE
ISCE forum closed?

### ISSUE THREAD

**Issue by volter29** [isce-framework/isce2#343]
sorry if I write here, but I wanted to ask why ISCE Earthdef :: ISCEForum has been closed. There was a lot of information that helped solve various problems. Is the closure of the forum final or is it just temporary?

Thanks again to the developers for this software

FM

**Comment by rtburns-jpl** [comment]
Hi, sorry to say the forum is permanently closed. You can read a littlle more about that here: https://github.com/isce-framework/isce2/discussions/342

We've set up GitHub Discussions as a replacement: https://github.com/isce-framework/isce2/discussions

**Comment by volter29** [comment]
thank you for the answer and for the work you are doing. The forum is essential to understand and solve many problems. I just wanted to inform you that the search function of the forum archive does not work now.

thank you again
FM
