### ISSUE TITLE
Coregistration error for CSK with stackStripMap.py

### ISSUE THREAD

**Issue by lsbts** [isce-framework/isce2#345]
Hello,

I'm trying to process a stack of Cosmo-SkyMed images (around 100 SLC images), to get the interferograms for each pair of dates.
At the moment, I've tried to do that with 4 dates, but I have a problem in the coregistration of the images.

I follow the [stripmapStack README](https://github.com/isce-framework/isce2/blob/main/contrib/stack/stripmapStack/README.md). However, the coregistration appears to be off by several pixels. Below are the 2 images visualized with mdx.py, with a couloured composition (red channel is reference date, blue and green channels are the coregistered date):

![stackstripmap_color](https://user-images.githubusercontent.com/50442306/134703200-aea66424-c223-40ee-8ab7-8e58459c70f8.png)
The problem is similar with the other dates, they are all badly coregistered with the master date (and among them too).

I launch the program with
```
stackStripMap.py -s ./SLC -d ./DEM/demLat*.dem.wgs84 -u snaphu --nofocus --working_directory ./working_dir --workflow interferogram
```

I do not have this problem with the application stripmapApp.py , as the coregistration is good. As seen below, the 2 dates are well coregistered (color code is the same as above):

![stripmap_color](https://user-images.githubusercontent.com/50442306/134703346-d6ee2f0a-b0ac-47ed-885d-15e4114d44d9.png)

Do you have any idea to correct the coregistration problem I have with stackStripMap.py? I did not see any parameter related to the coregistration with `stackStripMap.py --help`, but maybe I am missing something here?

Thank you,

**Comment by piyushrpt** [comment]
Probably need the `-z` flag a well in the prep stage to inform the script that the SLCs are in zero doppler geometry.

**Comment by lsbts** [comment]
> 
> 
> Probably need the `-z` flag a well in the prep stage to inform the script that the SLCs are in zero doppler geometry.

Thank you @piyushrpt , that is the solution!

**Comment by Shawn-ZHOU-666** [comment]
Hi @lsbts ,
I'm curious how you visualized the coregistered images using mdx.py.
Did you load the .slc files from each date's subdirectory under merged/SLC/?
