### ISSUE TITLE
Errors while running sh run_01_unpack_topo_reference   in linux terminal

### ISSUE THREAD

**Issue by hariiirs** [isce-framework/isce2#360]
I am stacking Sentinel-1 images for StaMPS processing. Got stucked here - 

/run_files$ sh run_01_unpack_topo_reference

Completed Parsing the Configuration file
Functions to be executed:
['Function-1', 'Function-2']
Running: Sentinel1_TOPS
['--dirname', '/home/hari_s/Desktop/PSI_Insar/Ludhiana_Chandigarh/Ascending/data/SLCs/S1A_IW_SLC__1SDV_20201210T125600_20201210T125626_035624_042AC6_21EC.zip', '--swaths', '3', '--orbitdir', '/home/hari_s/Desktop/PSI_Insar/Ludhiana_Chandigarh/Ascending/data/orbits', '--outdir', '/home/hari_s/Sirmaur/reference', '--auxdir', '/home/hari_s/Desktop/PSI_Insar/Ludhiana_Chandigarh/Ascending/data/orbits', '--bbox', '30.51 30.76 77.36 77.99', '--pol', 'vv']
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
Input XML files:  ['/vsizip//home/hari_s/Desktop/PSI_Insar/Ludhiana_Chandigarh/Ascending/data/SLCs/S1A_IW_SLC__1SDV_20201210T125600_20201210T125626_035624_042AC6_21EC.zip/S1A_IW_SLC__1SDV_20201210T125600_20201210T125626_035624_042AC6_21EC.SAFE/annotation/s1a-iw3-slc-vv-20201210t125600-20201210t125626-035624-042ac6-006.xml']
Input TIFF files:  ['/vsizip//home/hari_s/Desktop/PSI_Insar/Ludhiana_Chandigarh/Ascending/data/SLCs/S1A_IW_SLC__1SDV_20201210T125600_20201210T125626_035624_042AC6_21EC.zip/S1A_IW_SLC__1SDV_20201210T125600_20201210T125626_035624_042AC6_21EC.SAFE/measurement/s1a-iw3-slc-vv-20201210t125600-20201210t125626-035624-042ac6-006.tiff']
Manifest files:  ['/vsizip//home/hari_s/Desktop/PSI_Insar/Ludhiana_Chandigarh/Ascending/data/SLCs/S1A_IW_SLC__1SDV_20201210T125600_20201210T125626_035624_042AC6_21EC.zip/S1A_IW_SLC__1SDV_20201210T125600_20201210T125626_035624_042AC6_21EC.SAFE/manifest.safe']
MANS:  /home/hari_s/Desktop/PSI_Insar/Ludhiana_Chandigarh/Ascending/data/SLCs/S1A_IW_SLC__1SDV_20201210T125600_20201210T125626_035624_042AC6_21EC.zip S1A_IW_SLC__1SDV_20201210T125600_20201210T125626_035624_042AC6_21EC.SAFE/manifest.safe
Setting IPF version to :  003.31
No suitable orbit file found. If you want to process anyway - unset the orbitdir parameter
Running: topo
['--reference', '/home/hari_s/Sirmaur/reference', '--dem', '/home/hari_s/Sirmaur/DEM/demLat_N30_N31_Lon_E077_E078.dem.wgs84', '--geom_referenceDir', '/home/hari_s/Sirmaur/geom_reference', '--numProcess', '4']
running in parallel with 4 processes
Traceback (most recent call last):
  File "/home/hari_s/anaconda3/envs/isce2/share/isce2/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/home/hari_s/anaconda3/envs/isce2/share/isce2/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/home/hari_s/anaconda3/envs/isce2/share/isce2/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/home/hari_s/anaconda3/envs/isce2/share/isce2/topsStack/topo.py", line 112, in main
    bbox = [np.min(boxes[:,0]), np.max(boxes[:,1]), np.min(boxes[:,2]), np.max(boxes[:,3])]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

Kindly help me.

**Comment by hariiirs** [comment]
Now it is running fine. actually I have downloaded new orbit files.

**Comment by ThreeIcug** [comment]
Hi  , I have suffer the same error. I have download the new orbit files from https://scihub.copernicus.eu/gnss/#/home. But it doenot work.

**Comment by manudeo** [comment]
Hi @ThreeIcug, try redownloading your SLCs. The redownloading fixed this issue for me.

**Comment by nadiahassanpour** [comment]
> Hi @ThreeIcug, try redownloading your SLCs. The redownloading fixed this issue for me.
> 
> Edit: check the path of your orbit file in config files for reference unpacking, it is possible that full path is not there.

Dear Manudeo, I have this problem too and my Orbit file and my SLCs are completely correct, how can I solve this problem?

**Comment by manudeo** [comment]
Go to the parent directory of orbit files and run this: cp orbits/*/* orbits/ 

if your orbit directory is named orbits, else do suitable modifications. What we are doing here is making a copy of all the orbits which are stored in the respective date folders in orbits folder to the orbit folder. There is a bug which do not write full orbit file path for some dates. 

All the best. 

-Manu

**Comment by rtburns-jpl** [comment]
Sounds like this has been resolved, happy to reopen if there are further issues
