### ISSUE TITLE
run_12_merge_reference_secondary_slc (error: SentinelWrapper.py -c /M/test/final/configs/config_merge_lat)

### ISSUE THREAD

**Issue by dream81** [isce-framework/isce2#397]
Completed Parsing the Configuration file
Functions to be executed:
['Function-1']
Running: mergeBursts
['--stack', '/M/test/final/stack', '--inp_reference', '/M/test/final/reference', '--dirname', '/M/test/final/geom_reference', '--name_pattern', 'lat*rdr', '--outfile', '/M/test/final/merged/geom_reference/lat.rdr', '--method', 'top', '--multilook', '--range_looks', '40', '--azimuth_looks', '10', '--multilook_tool', 'gdal', '--no_data_value', '0']
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
Updating the valid region of each burst to the common valid region of the stack
bursts:  1 5
Updating the valid region of each burst to the common valid region of the stack
bursts:  1 4
writing merged file to disk ...
Input file size is 48518, 6871
0...10...20...30...40...50...60...70...80...90...100 - done.
True
multi looking using gdal ...
/M/test/final/merged/geom_reference/lat.rdr.full
ERROR 1: Input and output dataset sizes or band counts do not
match in GDALDatasetCopyWholeRaster()
ERROR 4: /M/test/final/merged/geom_reference/lat.rdr: No such file or directory
Traceback (most recent call last):
  File "/home/isce-2.5.3/contrib/stack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/home/isce-2.5.3/contrib/stack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/home/isce-2.5.3/contrib/stack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/home/isce-2.5.3/contrib/stack/topsStack/mergeBursts.py", line 415, in main
    multilook(inps.outfile+suffix,
  File "/home/isce-2.5.3/contrib/stack/topsStack/mergeBursts.py", line 315, in multilook
    gdal.Translate(outname+".vrt", ds, options=gdal.TranslateOptions(format="VRT"))
  File "/home/dream/anaconda3/envs/insar/lib/python3.8/site-packages/osgeo/gdal.py", line 491, in Translate
    return TranslateInternal(destName, srcDS, opts, callback, callback_data)
  File "/home/dream/anaconda3/envs/insar/lib/python3.8/site-packages/osgeo/gdal.py", line 4582, in TranslateInternal
    return _gdal.TranslateInternal(*args)
ValueError: Received a NULL pointer.

**Comment by xsar123** [comment]
Hi, dream81, I met the same error message as yours. Could you share how did you resolve it? Thanks a lot.

**Comment by PickleRickrx** [comment]
> Hi, dream81, I met the same error message as yours. Could you share how did you resolve it? Thanks a lot.

I've met the same situation, I wonder if you solve this problem and would you please tell the solution?many thanks.

**Comment by ThreeIcug** [comment]
Looks like we've all met the error. Do you have a solution?
