### ISSUE TITLE
 IndexError: list index out of range while processing TerraSAR with unpackFrame_TSX.py

### ISSUE THREAD

**Issue by wandi12345** [isce-framework/isce2#407]
Hi everyone,
when I run this command unpackFrame_TSX.py -i /misc/TerraSAR/DATA/ -o /misc/TerraSAR/UPDATA/
this error occured:  IndexError: list index out of range

The data structure looks like this：
/dims_op_oc_dfd2_679780118_1/TSX-1.SAR.L1B/TDX1_SAR__SSC______SL_S_SRA_20211012T103712_20211012T103714/
 and, I also tried change unpackFrame_TSX.py lines 32, but not work. 
![aaba41dc4a671f4f1d1d9ba1d312ad5](https://user-images.githubusercontent.com/74475233/144157668-dfd3a9e2-f950-4c2d-9636-c1f777efdcf3.png)

**Comment by piyushrpt** [comment]
See https://github.com/isce-framework/isce2/discussions/409
