### ISSUE TITLE
Sentinel 1 TOPS burst VRT dimensions off by 1

### ISSUE THREAD

**Issue by LiangJYu** [isce-framework/isce2#418]
The bug was discovered [here](https://github.com/opera-adt/sentinel1-reader/pull/1#discussion_r768042666). The VRT write method in that project/repo mirrors TOPS/Sentinel1.py [here](https://github.com/isce-framework/isce2/blob/0e5114a8bede3caf1d533d98e44dfe4b983e3f48/components/isceobj/Sensor/TOPS/Sentinel1.py#L1373).

**Comment by piyushrpt** [comment]
I believe these are meant to be used in python-like notation `slice(0,10)` goes from `0..9`. 
This was done to avoid having to do +/-1 in a large number of places. 

The imagery should correspond to  

`valid_arr = img_arr[first_valid_line:last_valid_line, first_valid_sample:last_valid_sample]`

Correspondingly, 

`number_of_valid_{lines/samples} = last_valid_{line/sample} - first_valid_{line/sample}`

**Comment by piyushrpt** [comment]
Also see [here](https://github.com/isce-framework/isce2/blob/0e5114a8bede3caf1d533d98e44dfe4b983e3f48/components/isceobj/Sensor/TOPS/BurstSLC.py#L314)

`last_valid_sample` and `last_valid_line` are always computed on the fly from the other two parameters to conform to python conventions.

**Comment by hfattahi** [comment]
I can summarize my understanding as follows:
Basically if we simplify to F for first line/sample and L for last line/sample and W for width/length, then we have
```
W = L - F + 1
```
And then
```
L = F + W -1
```
If we rearrange the variables such that
```
W2 = W-1
```
Then L can be computed as:
```
L = F + W2
```
isce2 reader computes W2  [here]https://github.com/isce-framework/isce2/blob/0e5114a8bede3caf1d533d98e44dfe4b983e3f48/components/isceobj/Sensor/TOPS/Sentinel1.py#L668 and not W. Therefore it does not look like a bug in isce2. 
We may still need ```+1``` in the new implementation [here](https://github.com/opera-adt/sentinel1-reader/pull/1#discussion_r768042666)

**Comment by piyushrpt** [comment]
In the reader, `F` and `W` have the same interpretation as yours. But the `last{Sample/Line}` is actually

`L2 = L + 1`

Metadata only stores `F` and `W`. You will only see these being set in the readers.  `L2` is always computed on the fly as 
`L2 = F + W`

**Comment by hfattahi** [comment]
Thanks again @piyushrpt for the clarification. @LiangJYu are you ok to close this issue. If yes please go ahead and close it.
