### ISSUE TITLE
issue adding an image and generating new pairs with stackSentinel.py

### ISSUE THREAD

**Issue by FedeDC** [isce-framework/isce2#437]
I am trying to extend the interferometric pairs created with stackSentinel.py.
It was done with a 2.5.1 version of isce, and as I am doing some tests,  in order to test how to extend a previous serie, I did it with few images.
However, when adding a new image to the image source (-s), and run the stackSentinel.py command, with exactly the same parameters I do before, I get the following error, and I can't understand what it refers to:
"Exception: The original SAFE files for latest 3 coregistered SLCs is needed"
the only thing it manages to create when running (with exactly the same parameters as the previous time) is the file isce.log and SAFE_files.txt (containing the correct directories and image names, included in the -s argument).
Anyone who can guide me?
Thank you very much!
Fede

**Comment by hfattahi** [comment]
The error message is clear:

"Exception: The original SAFE files for latest 3 coregistered SLCs is needed"

Have you deleted the zip/SAFE files for the previous stack? You would need at least 3 latest zip file that you used for the previous stack to be able to update the stack with new acquisitions.

**Comment by FedeDC** [comment]
> The error message is clear:
> 
> "Exception: The original SAFE files for latest 3 coregistered SLCs is needed"
> 
> Have you deleted the zip/SAFE files for the previous stack? You would need at least 3 latest zip file that you used for the previous stack to be able to update the stack with new acquisitions.

Hello, 
Thanks for your reply 
To run the routine adding the new image, simply replicate the command and arguments from the previous time:
stackSentinel.py -s ./imagenes/ -d ./dem/demLat_S25_S24_Lon_W069_W068.dem.wgs84 -b '-24.4020 -24.3934 -68.2496 -68.2372' -a ./orbit/S1/auxi/ -w ./Resultados -o ./orbit/S1/precise/ -c all

Where I clarify the source of the images (-s), I don't know if it works correctly without that argument, since in the help it clarifies that it is a mandatory argument.
First, I had used the following images:
'20200913', '20201112', '20210216'
And add the image of '20210417'

Once I run the command and arguments, the terminal displays the following:

This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
Number of SAFE files found: 4
2022-01-24 16:16:52,463 - shapely.geos - DEBUG - Found GEOS DLL: <CDLL '/usr/local/lib/python3.6/dist-packages/shapely/.libs/libgeos_c-a68605fd.so.1.13.1', handle 2f28040 at 0x7f05278e6cc0>, using it.
2022-01-24 16:16:52,473 - shapely.geos - DEBUG - Trying `CDLL(libc.so.6)`
2022-01-24 16:16:52,473 - shapely.geos - DEBUG - Library path: 'libc.so.6'
2022-01-24 16:16:52,474 - shapely.geos - DEBUG - DLL: <CDLL 'libc.so.6', handle 7f059d4f9000 at 0x7f055c60a470>
Number of SAFE files to be used (cover BBOX): 4
*****************************************
Number of dates : 4
List of dates : 
['20200913', '20201112', '20210216', '20210417']
date      south      north
20200913 -24.877998 -22.640013
20201112 -24.878412 -22.640438
20210216 -24.878403 -22.640415
20210417 -24.879137 -22.64097
*****************************************
The overlap region among all dates (based on the preview kml files):
 South   North   East  West 
-24.877998 -22.64097 -69.19725 -66.342613
*****************************************
All dates (4)
['20200913', '20201112', '20210216', '20210417']

dates covering the bbox (4)
['20200913', '20201112', '20210216', '20210417']

The reference date was not chosen. The first date is considered as reference date.

All SLCs will be coregistered to : 20200913
secondary dates :
['20201112', '20210216', '20210417']

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

An existing stack with following coregistered SLCs was found:
['20201112', '20210216']

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

New acquisitions was found: 
['20210417']

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Traceback (most recent call last):
  File "./isce251/contrib/stack/topsStack/stackSentinel.py", line 772, in <module>
    main(sys.argv[1:])
  File "./isce251/contrib/stack/topsStack/stackSentinel.py", line 735, in main
    acquisitionDates, stackReferenceDate, secondaryDates, safe_dict, updateStack = checkCurrentStatus(inps)
  File "./isce251/contrib/stack/topsStack/stackSentinel.py", line 661, in checkCurrentStatus
    raise Exception('The original SAFE files for latest {0} coregistered SLCs is needed'.format(numSLCReprocess))
Exception: The original SAFE files for latest 3 coregistered SLCs is needed

**Comment by hfattahi** [comment]
The coregistration approach by default  is "NESD" which means that there needs to be a network of SLCs to refine the misregistration. Change the coregistration approach to ```geometry```. That may let you go forward with your update.

Anyways, the idea of the stack update is for cases where user may have a stack of 10s or 100s images and now wants to update with new few acquisitions. You have only 4 dates. Go ahead and just reprocess from scratch if changing the coregistration algorithm to geometry suggested above does not work.

**Comment by FedeDC** [comment]
Yes, I just wanted to do a test with a few images, so as not to step on what has been done in other processes with a larger number of images.
But, I don't understand very well. Does the problem lie in the number of images, which does not allow to generate the SLCs network to apply the default correlation method or is it directly the default correlation method?

**Comment by hfattahi** [comment]
Great idea to test with smaller dataset.

Would you please redo your test with coregistration set to geometry by adding the following option to your stackSentinel.py command:
```--coregistration geometry```

And let me know if that helps?

The default coregistration is NESD where we need pairs of SLCs to estimate a small misregistration at the differential double difference interferograms at the boundaries of burst overlaps. If that is your method of coregistration and if you add a new acquisition, you need at least one SLC from before to crate double difference interferograms and in practice the resampling of the previous SLCs which are directly (or indirectly) connected with the new acquisition need to be updated. So you need some data from before. By experience the gain is limited and in many regions this refinement not needed. Our understanding have improved and we are moving towards using only ```geometry``` for coregistration and refine the offsets with newer algorithms and ancillary data. Those developments will evolve to isce3. You can see more details about NESD [here](https://ieeexplore.ieee.org/abstract/document/7637021). 

But again I strongly recommend to use ```--coregistration geometry```.

Hope that helps.

**Comment by FedeDC** [comment]
Great, thank you very much for your response and patience.
I'll run the commands with a few images and let you know in a few hours.

**Comment by FedeDC** [comment]
Hello,
I ran the routine with 3 initial images and added a new acquisition.
The first time I ran the command with the following arguments:

stackSentinel.py -s ./imagenes/ -d ./dem/demLat_S25_S24_Lon_W069_W068.dem.wgs84 -b '-24.4020 -24.3934 -68.2496 -68.2372' -a ./Isce/orbit/S1/auxi/ -w ./PS/Prueba3/Resultados -o ./Isce/orbit/S1/precise/ -c all -C geometry

However, when adding the new image, and running the same line with the same arguments, there was an error related to the --num_connections (-c all) argument.
By removing this option and running the line below, the new run_files were generated without any new problems.

stackSentinel.py -s ./imagenes/ -d ./dem/demLat_S25_S24_Lon_W069_W068.dem.wgs84 -b '-24.4020 -24.3934 -68.2496 -68.2372' -a ./Isce/orbit/S1/auxi/ -w ./PS/Prueba3/Resultados -o ./Isce/orbit/S1/precise/ -C geometry

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Updating an existing stack ...

*****************************************
Coregistration method:  geometry
Workflow:  interferogram
*****************************************

In addition, I did another test with 16 images, with similar parameters to the previous test, but this time with the NESD geocorregistration method. 

stackSentinel.py -s ./imagenes/ -d ./dem/demLat_S25_S24_Lon_W069_W068.dem.wgs84 -b '-24.4020 -24.3934 -68.2496 -68.2372' -a ./Isce/orbit/S1/auxi/ -w ./PS/Prueba3/Resultados -o ./Isce/orbit/S1/precise/

And when I added the new image, and ran the line again, the files were created in run_files, without any problem.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Updating an existing stack ...

*****************************************
Coregistration method:  NESD
Workflow:  interferogram
*****************************************

**Comment by hfattahi** [comment]
Thanks for the update. Things seem to be working as expected. If you agree please go ahead and close this issue.

**Comment by FedeDC** [comment]
Great, thank you very much for the help.
