### ISSUE TITLE
unpackFrame_ALOS_raw.py

### ISSUE THREAD

**Issue by libingquan13** [isce-framework/isce2#452]

**Comment by pikaqiu202201** [comment]
I can't run this step, I'm using alos1Leve1.1, can you help me

**Comment by piyushrpt** [comment]
Level 1.1 is SLC and not RAW data.

**Comment by pikaqiu202201** [comment]
I don't know which steps to use to unzip and generate slc, can you help me, thanks a lot

**Comment by keepfighting666** [comment]
> I don't know which steps to use to unzip and generate slc, can you help me, thanks a lot

hello, I have the same error. Can you help me?

**Comment by gangjizetian** [comment]
> I don't know which steps to use to unzip and generate slc, can you help me, thanks a lot

May I ask if you have resolved this issue? Looking forward to your reply. Thank you
