### ISSUE TITLE
Error: run_01_unpack_topo_reference - too many indices for array

### ISSUE THREAD

**Issue by jaha2600** [isce-framework/isce2#454]
I am running the most recent version of stackSentinel.py on a linux terminal (downloaded March 8th 2022).
Run files generate correctly but running run_01 results in an error, similar to that seen in #255, #360.
An example of the error code is shown below. This occurs with every SLC file that I have downloaded (files are from ASF Vertex).
An slc filelist is attached. [slc_list.txt](https://github.com/isce-framework/isce2/files/8226836/slc_list.txt)
I have tried re-downloading orbit files and SLC's but no change.

`(isce2) jasmine@benbecula:/data/GREENLAND/2022/ISCE_2/run_files$ ./run_01_unpack_topo_reference` 
Completed Parsing the Configuration file
Functions to be executed:
['Function-1', 'Function-2']
Running: Sentinel1_TOPS
['--dirname', '/data/GREENLAND/2022/ISCE_2/slc_todo/25_370/S1A_IW_SLC__1SDH_20190502T100105_20190502T100132_027047_030BE3_F29A.zip', '--swaths', '1 2 3', '--orbit', '/data/GREENLAND/2022/ISCE_2/orbits/20190502/S1A_OPER_AUX_POEORB_OPOD_20210312T054134_V20190501T225942_20190503T005942.EOF', '--outdir', '/data/GREENLAND/2022/ISCE_2/reference', '--auxdir', '/data/GREENLAND/2022/ISCE_2/aux_dir', '--bbox', '65.69 67.47 -54.15 -49.17', '--pol', 'vv']
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
No annotation xml file found in zip file: /data/GREENLAND/2022/ISCE_2/slc_todo/25_370/S1A_IW_SLC__1SDH_20190502T100105_20190502T100132_027047_030BE3_F29A.zip
No annotation xml file found in zip file: /data/GREENLAND/2022/ISCE_2/slc_todo/25_370/S1A_IW_SLC__1SDH_20190502T100105_20190502T100132_027047_030BE3_F29A.zip
No annotation xml file found in zip file: /data/GREENLAND/2022/ISCE_2/slc_todo/25_370/S1A_IW_SLC__1SDH_20190502T100105_20190502T100132_027047_030BE3_F29A.zip
Running: topo
['--reference', '/data/GREENLAND/2022/ISCE_2/reference', '--dem', '/data/GREENLAND/2022/ISCE_2/dem/glo_30.dem.wgs84', '--geom_referenceDir', '/data/GREENLAND/2022/ISCE_2/geom_reference', '--numProcess', '1']
running in parallel with 1 processes
Traceback (most recent call last):
  File "/home/jasmine/Applications/isce/contrib/stack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/home/jasmine/Applications/isce/contrib/stack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/home/jasmine/Applications/isce/contrib/stack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/home/jasmine/Applications/isce/contrib/stack/topsStack/topo.py", line 112, in main
    bbox = [np.min(boxes[:,0]), np.max(boxes[:,1]), np.min(boxes[:,2]), np.max(boxes[:,3])]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by piyushrpt** [comment]
Set the polarization field to `hh` when setting it up. By default it looks for `vv` only

**Comment by zhaoyazhu** [comment]
hello ,me too, help me

**Comment by hariiirs** [comment]
Just re-run stackSentinel.py with fresh orbit files.

**Comment by ApoorvaMalviya** [comment]
My orbit files are fresh and correct (downloaded using eof), DEM is also correct, everything is at its appropriate place and still I'm getting this error. please help me with this.



(InSARenv) iirs@wrdlb01:~/AMISCE/Outputs/run_files$ sh run_01_unpack_topo_reference

Completed Parsing the Configuration file
Functions to be executed:
['Function-1', 'Function-2']
Running: Sentinel1_TOPS
['--dirname', '/home/iirs/AMISCE/SLCs/S1B_IW_SLC__1SDV_20191002T004230_20191002T004300_018289_022729_0330.zip', '--swaths', '16', '--orbitdir', '/home/iirs/AMISCE/Outputs/orbits', '--outdir', '/home/iirs/AMISCE/Outputs/reference', '--auxdir', '/home/iirs/AMISCE/Outputs/orbits', '--bbox', '30.5 31.5 78.5 79.5', '--pol', 'vv']
Swath number must be one out of [1,2,3]
Running: topo
['--reference', '/home/iirs/AMISCE/Outputs/reference', '--dem', '/home/iirs/AMISCE/DEM/demLat_N30_N31_Lon_E078_E079.dem.wgs84', '--geom_referenceDir', '/home/iirs/AMISCE/Outputs/geom_reference', '--numProcess', '4']
running in parallel with 4 processes
Traceback (most recent call last):
  File "/home/iirs/anaconda3/envs/InSARenv/share/isce2/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/home/iirs/anaconda3/envs/InSARenv/share/isce2/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/home/iirs/anaconda3/envs/InSARenv/share/isce2/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/home/iirs/anaconda3/envs/InSARenv/share/isce2/topsStack/topo.py", line 112, in main
    bbox = [np.min(boxes[:,0]), np.max(boxes[:,1]), np.min(boxes[:,2]), np.max(boxes[:,3])]
                   ~~~~~^^^^^
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
