### ISSUE TITLE
StripmapApp error with Envisat - KeyError: 'nom_chirp_14' (_populateInstrument)

### ISSUE THREAD

**Issue by Carolinah23** [isce-framework/isce2#471]
Hello all,

I am trying to create some interferograms using Envisat data from 2004. I downloaded the instrument data from the ESA website (https://earth.esa.int/eogateway/instruments/asar/auxiliary-data) and requested the orbit data, it is already on my computer. 
When I try to run `stripmapApp.py stripmapApp.xml --start=startup --end=preprocess` I get the following error

![image](https://user-images.githubusercontent.com/54252458/161152090-284ea8b7-6c44-4487-a996-bb40c919cdd3.png)

These are the input XML files that I am using:

```
#Reference image
    cmd_reference_config='''<component name="reference">
    <property name="IMAGEFILE"> 
/media/carolina/CarolOffice/PSI/Envisat/Test/Data/ASA_IMS_1PNESA20040418_161027_000000182026_00083_11159_0000.N1
    </property>

    <property name="INSTRUMENT_DIRECTORY">
        /media/carolina/CarolOffice/PSI/Envisat/Test/Data/Instrument
    </property>
    <property name="ORBIT_DIRECTORY">
        /media/carolina/CarolOffice/PSI/Envisat/Test/Data/Doris
    </property>
    <property name="OUTPUT">
        20040418
    </property>
    </component>'''
```

```
#Secondary image
    cmd_secondary_config='''<component name="reference">
    <property name="IMAGEFILE">
/media/carolina/CarolOffice/PSI/Envisat/Test/Data/ASA_IMS_1PNESA20040523_161031_000000182027_00083_11660_0000.N1
    </property>
    <property name="INSTRUMENT_DIRECTORY">
        /media/carolina/CarolOffice/PSI/Envisat/Test/Data/Instrument
    </property>
    <property name="ORBIT_DIRECTORY">
        /media/carolina/CarolOffice/PSI/Envisat/Test/Data/Doris
    </property>
    <property name="OUTPUT">
        20040523
    </property>
    </component>'''
```

```
    #stripmapApp.py
    cmd_stripmap_config='''<?xml version="1.0" encoding="UTF-8"?>
    <stripmapApp>
    <component name="insar">
        <property name="sensor name">EnviSAT</property>
        <component name="reference">
            <catalog>reference.xml</catalog>
        </component>
        <component name="secondary">
            <catalog>secondary.xml</catalog>
        </component>

        <!--  
        <property name="demFilename">
            <value>demLat_N18_N21_Lon_W156_W154.dem.wgs84</value>
        </property>
        -->

        <property name="unwrapper name">icu</property>

    </component>
    </stripmapApp>''' 
```
I have run the example from the [UNAVCO 2021 workshop](https://github.com/parosen/Geo-SInC/blob/main/UNAVCO2021/1.4_Stripmap_Data_Processing_Interferometry/stripmapApp.ipynb) and it works, so I think it is not an installation problem. 

I am using isce2 2.5.1 and python 3.8.12 and I am using Ubuntu 20.04.4 LTS, I try to update isce2 to the newest version but it stayed the same.

I appreciate any help!

**Comment by piyushrpt** [comment]
Are you sure the dataset is `Envisat` RAW data and not `Envisat_SLC`? Check the naming convention

**Comment by Carolinah23** [comment]
Yes, I am using EnviSAT SLC. Thanks for pointing out the problem! I just fixed it, I changed the sensor name from `EnviSAT` to `EnviSAT_SLC` in the `stripmapApp.xml` file.
I followed the structure of the example given in the [examples folder](https://github.com/isce-framework/isce2/blob/main/examples/input_files/reference_EnviSAT.xml)
