### ISSUE TITLE
Latest Sentinel-1 data produced with IPF 003.40 (and 3.51?) after 2021-11-04 07:56:32 are not supported.

### ISSUE THREAD

**Issue by S0sh0rt** [isce-framework/isce2#478]
Running SentinelWrapper.py config_reference returns this message and does not complete successfully:

Setting IPF version to :  003.40
'utf-8' codec can't decode byte 0xc0 in position 10: invalid start byte

**Comment by piyushrpt** [comment]
Check your downloaded zip files. Likely an incomplete download

**Comment by S0sh0rt** [comment]
I have used the same SLC files in S1TBX and GAMMA. The zip files also test without error.

**Comment by piyushrpt** [comment]
Would be helpful if actual granule names are provided

**Comment by S0sh0rt** [comment]
CentOS 7 with a build from the latest ISCE 2.6 clone.
zip files were downloaded from ASF, no repackaging. 
Files produced prior to 2021-11-04 process correctly.
The files below result with invalid start byte, when running run_01_unpack_topo_reference from stackSentinel.py.
S1A_IW_SLC__1SDV_20220216T041150_20220216T041217_041933_04FE4B_4E5A.zip
S1A_IW_SLC__1SDV_20220228T041150_20220228T041217_042108_050449_451B.zip
S1A_IW_SLC__1SDV_20220312T041150_20220312T041217_042283_050A3A_EB71.zip
S1A_IW_SLC__1SDV_20220324T041150_20220324T041217_042458_05102C_F4AF.zip

**Comment by piyushrpt** [comment]
I had no issues working with one scene at least. Do you have a weird environment setup with `PYTHONIOENCODING` set to something specific or have weird characters in your folder names? `0xc0` is a character with an accent - not sure its standard ASCII

```python
import os
import shutil
import isce  # noqa
from isceobj.Sensor.TOPS import Sentinel1


fname = "S1A_IW_SLC__1SDV_20220216T041150_20220216T041217_041933_04FE4B_4E5A.zip"
outname = "test"


for swaths in range(1, 4):
    if os.path.isdir(outname):
        shutil.rmtree(outname)

    parser = Sentinel1.Sentinel1()
    parser.configure()

    parser.safe = [fname]
    parser.swathNumber = 2
    parser.output = outname
    parser.polarization = "vv"
    parser.extractImage(virtual=True)
```

**Comment by piyushrpt** [comment]
If you are on an international (non-english) language setup, try setting this env variable:
https://github.com/isce-framework/isce2/blob/566ebfb9a85f2bdb5d538b3ba86b289aaaf702a7/docker/Dockerfile#L4

**Comment by S0sh0rt** [comment]
I am now also unable to reproduce the issue.  It must have been something with my environment in the terminal I used for 2022 data, and not the terminal used for the 2021 data.  Thank you for your support and prompt replies.

**Comment by Xious-1314** [comment]
Hello, is there any good solution to the problem you encountered at that time? I have also encountered the same problem in the process of learning, and I would like to ask for your help.

**Comment by Xious-1314** [comment]
Hello everyone, I solved this problem by deleting the original track file and re-downloading it.
