### ISSUE TITLE
dem

### ISSUE THREAD

**Issue by OliviaDdy** [isce-framework/isce2#481]
Recently, I use the isce2 library to complete the DEM extraction of sentienl1 .
I have completed the compilation of isce2, and use the contrib/stack/topsStack module to complete the DEM extraction,
However, in the initial process, when the dem acquisition was performed, the following problems occurred,

I have completed https://urs.earthdata.nasa.gov/profile LP DAAC Data Pool” and “LP DAAC OpenDAP” application additions

when I run
dem.py -a stitch -b 24 25 117 119 -s 1 -m xml -r -c -n XXX -w  XXX  -u https://e4ftl01.cr.usgs.gov/MEASURES/SRTMGL1.003/2000.02.11/

This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
curl -k -f -u XXX:XXX -O https://e4ftl01.cr.usgs.gov/MEASURES/SRTMGL1.003/2000.02.11/N24E117.SRTMGL1.hgt.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:-  0     0    0     0    0     0      0      0 --:--:--  0:0  0     0    0     0    0     0      0      0 --:--:--  0:0  0     0    0     0    0     0      0      0 --:--:--  0:0  0     0    0     0    0     0      0      0 --:--:--  0:0  0     0    0     0    0     0      0      0 --:--:--  0:0100   498  100   498    0     0     99      0  0:00:05  0:00:05 --:--:--   132
curl -k -f -u XXX:XXX -O https://e4ftl01.cr.usgs.gov/MEASURES/SRTMGL1.003/2000.02.11/N24E118.SRTMGL1.hgt.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:-  0     0    0     0    0     0      0      0 --:--:--  0:0  0     0    0     0    0     0      0      0 --:--:--  0:0  0     0    0     0    0     0      0      0 --:--:--  0:0  0     0    0     0    0     0      0      0 --:--:--  0:0  0     0    0     0    0     0      0      0 --:--:--  0:0100   498  100   498    0     0     88      0  0:00:05  0:0100   498  100   498    0     0     88      0  0:00:05  0:00:05 --:--:--   146
[./N24E117.SRTMGL1.hgt.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ./N24E117.SRTMGL1.hgt.zip or
        ./N24E117.SRTMGL1.hgt.zip.zip, and cannot find ./N24E117.SRTMGL1.hgt.zip.ZIP, period.
[./N24E118.SRTMGL1.hgt.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ./N24E118.SRTMGL1.hgt.zip or
        ./N24E118.SRTMGL1.hgt.zip.zip, and cannot find ./N24E118.SRTMGL1.hgt.zip.ZIP, period.
Cannot open DEM file ./N24E117.hgt for reading.
API open (R): ./demLat_N24_N25_Lon_E117_E119.dem
API close:  ./demLat_N24_N25_Lon_E117_E119.dem
Writing geotrans to VRT for ./demLat_N24_N25_Lon_E117_E119.dem
GDAL open (R): ./demLat_N24_N25_Lon_E117_E119.dem.vrt
ERROR 1: Invalid dataset dimensions : 7200 x -1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot open the file ./demLat_N24_N25_Lon_E117_E119.dem.vrt in read mode.
已放弃

(isce) [XXX@ShuBei-178 DEM]$ ls
demLat_N24_N25_Lon_E117_E119.dem
demLat_N24_N25_Lon_E117_E119.dem.vrt
demLat_N24_N25_Lon_E117_E119.dem.xml
insar.log

The main performance is that the dem data has not been converted to wgs84, and the deLat_N24_N25_Lon_E117_E119.dem data is unreadable

Have you encountered such a problem? How can I fix it, thanks !
@pymonger @vincentschut @hfattahi @aivazis @shitong01

**Comment by RussellGrew** [comment]
I had the same problem with your command.

It works if I drop the credentials and URL, and seems to source the data from the same place.

```
dem.py -a stitch -b 24 25 117 119 -s 1 -m xml -r -c
```

```
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
curl -n  -L -c $HOME/.earthdatacookie -b $HOME/.earthdatacookie -k -f -O http://e4ftl01.cr.usgs.gov/MEASURES/SRTMGL1.003/2000.02.11/N24E117.SRTMGL1.hgt.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   267  100   267    0     0    656      0 --:--:-- --:--:-- --:--:--   657
100   498  100   498    0     0     26      0  0:00:19  0:00:18  0:00:01   153
100   291    0   291    0     0     14      0 --:--:--  0:00:20 --:--:--   315
100   267  100   267    0     0     12      0  0:00:22  0:00:21  0:00:01    12
100 13.4M  100 13.4M    0     0   162k      0  0:01:24  0:01:24 --:--:--  549k
curl -n  -L -c $HOME/.earthdatacookie -b $HOME/.earthdatacookie -k -f -O http://e4ftl01.cr.usgs.gov/MEASURES/SRTMGL1.003/2000.02.11/N24E118.SRTMGL1.hgt.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   267  100   267    0     0    655      0 --:--:-- --:--:-- --:--:--   656
100 4103k  100 4103k    0     0   155k      0  0:00:26  0:00:26 --:--:--  531k
API open (R): ./demLat_N24_N25_Lon_E117_E119.dem
API close:  ./demLat_N24_N25_Lon_E117_E119.dem
Writing geotrans to VRT for ./demLat_N24_N25_Lon_E117_E119.dem
GDAL open (R): ./demLat_N24_N25_Lon_E117_E119.dem.vrt
API open (WR): demLat_N24_N25_Lon_E117_E119.dem.wgs84

    << Geoid Correction I2 SRTM>>

Jet Propulsion Laboratory - Radar Science and Engineering


Sampling Geoid at grid points -  Longitude Samples:    23 Latitude Lines:    13
Corner Geoid Heights (m) =   14.28   5.53   4.32  12.05

Correcting data to geoid height...

At line:      512
At line:     1024
At line:     1536
At line:     2048
At line:     2560
At line:     3072
At line:     3584
GDAL close: ./demLat_N24_N25_Lon_E117_E119.dem.vrt
API close:  demLat_N24_N25_Lon_E117_E119.dem.wgs84
API open (R): demLat_N24_N25_Lon_E117_E119.dem.wgs84
API close:  demLat_N24_N25_Lon_E117_E119.dem.wgs84
Writing geotrans to VRT for demLat_N24_N25_Lon_E117_E119.dem.wgs84
Writing geotrans to VRT for /home/russell/scratch/demLat_N24_N25_Lon_E117_E119.dem.wgs84
N24E117.SRTMGL1.hgt.zip = succeded
N24E118.SRTMGL1.hgt.zip = succeded
```

Good luck.

**Comment by rtburns-jpl** [comment]
Assuming Russel's command works and closing as resolved. Please comment if there are further issues and I'll reopen.

**Comment by MSSJoud** [comment]
Agreed after two years that was annoying but needs to check the logic of dem.py 
This one works : 


  
  dem.py -a stitch -b 45 46 11 12 -s 1 -c -r   -u https://e4ftl01.cr.usgs.gov/MEASURES/SRTMGL1.003/2000.02.11/
