### ISSUE TITLE
What is the unit of dense_offsets.bil.geo

### ISSUE THREAD

**Issue by Arctic-Ambrun** [isce-framework/isce2#483]
Hello everyone, I want to use the azimuth dense_offset to get a 3D deformation.
I have already checked out the band 1 is azimuth and band 2 is range offsets.
Here I want to ask the unit,
Is that means the pixel or meter? how should I convert it in to meter or minimeters?
Thanks in advance

**Comment by Arctic-Ambrun** [comment]
Hello everyone?

**Comment by piyushrpt** [comment]
Its in pixels. Would recommend reading up tutorial notebooks from the annual UNAVCO  ISCE training regarding this.
