### ISSUE TITLE
SBAS Processing: Variable Reachning 2GB data limit

### ISSUE THREAD

**Issue by hariiirs** [isce-framework/isce2#493]
I have a stack of 153 interferograms for SBAS processing. While performing stamps (1,5) then its showing the following message 

![Screenshot from 2022-05-19 14-19-06](https://user-images.githubusercontent.com/42439461/169255333-b07ead81-e435-405f-9d04-2f2d0853a10d.png)
 
Any one please can help me regarding any adverse effect of this message. It does not stopping the processing chain but only showing this message. I am worrying about this line of message "This will be slower but avoids matlab not saving the data".

Thanks in advance
Hari Shankar

**Comment by PeymanPython** [comment]
@hariiirs,
That error usually happens while the RAM, and CPU of your machine don't support this amount of data. 150 interferograms are too large for your machine. Thus, you have 3 solutions for : 
1- Decrease the number of your interferograms, 
2- Shrink your study area, and 
3- Reinforce your machine to support such big data.

**Comment by rtburns-jpl** [comment]
Sounds like this was a hardware issue, so closing as resolved. Happy to reopen if that is not the case.
