### ISSUE TITLE
water mask data cannot download

### ISSUE THREAD

**Issue by kylemurray2** [isce-framework/isce2#538]
The USGS may not have these files available anymore?

curl: (22) The requested URL returned error: 404
2022-07-21 13:50:07,180 - isce.iscesys.DataRetriever - WARNING - There was a problem in retrieving the file  http://e4ftl01.cr.usgs.gov/MEASURES/SRTMSWBD.003/2000.02.11/N19W159.SRTMSWBD.raw.zip. Requested file seems not present on server.

**Comment by EJFielding** [comment]
Hi Kyle,

The USGS servers of the water masks and SRTM DEM data are having a lot of problems for the last three weeks. The server seems better today, but it varies a lot.

**Comment by kylemurray2** [comment]
Hi Eric,
Thanks for your response.  I'm finding I can download the data with the URL in my browser but I have to sign in with my earthData account in my browser first at the base url: https://e4ftl01.cr.usgs.gov/MEASURES/SRTMSWBD.003/2000.02.11/
Perhaps for some reason the code createWaterMask.py or waterMask.py can't access my login credentials (from netrc)

dem.py works fine though..

**Comment by EJFielding** [comment]
I believe that the DEM download in topsApp reads .netrc the same way as dem.py. The water mask code should also be similar. The servers are variable in availability.

**Comment by EJFielding** [comment]
We think this has been fixed by #560 that has been merged. It seems the USGS servers changed to require `https` instead of `http` for SRTM DEM and water body data. There are still some server availability issues, but the ISCE2 code is now using the correct URLs.

**Comment by rtburns-jpl** [comment]
Closing as resolved by #560

**Comment by jerry7nol** [comment]
> We think this has been fixed by #560 that has been merged. It seems the USGS servers changed to require `https` instead of `http` for SRTM DEM and water body data. There are still some server availability issues, but the ISCE2 code is now using the correct URLs.

Hi Eric. 
i downloaded watermask.raw,but how can i use it in topsApp.py. do you have any documents about that?
thank you

**Comment by EJFielding** [comment]
Hi Jerry,
The `topsApp.py` has the flag to apply a water mask before unwrapping turned on by default. It is looking for a file named "watermask.msk", so you probably need to rename your file. You can open the `applications/topsApp.py` script to see what are all the parameters you can change.
