### ISSUE TITLE
local incidence angle_ALOS-2 ScanSAR

### ISSUE THREAD

**Issue by RShamshiri** [isce-framework/isce2#545]
Hello everyone!

I am running alosstack on a couple of ScanSAR images. I see the lon, lat, hgt, and los files in the insar folder in the "/dates_resampled/201227 (the reference date)" path, but not the local incidence angle. I am wondering where can I find it or how can I create that file.

Kind regards
Roghayeh

**Comment by EJFielding** [comment]
Hello Roghayeh,

Yes, you found the available geometry files under `dates_resampled/{reference_date}/insar`. The `alosStack` workflow is designed for InSAR processing, including MintPy time-series analysis of the InSAR phase. We did not design it for Radiometric Terrain Correction or other processing that depends on the local incidence angle. It does not calculate the local incidence angle that includes the effect of the local slope, but you should be able to calculate that from the `.los` and the `.hgt` with some extra work.

Best regards,
  ++Eric

**Comment by RShamshiri** [comment]
Hello Eric,

Thank you so much! I calculated that. 

Kind regards,
Roghayeh
