### ISSUE TITLE
release_history not updated to v2.6.0

### ISSUE THREAD

**Issue by EJFielding** [isce-framework/isce2#556]
The `release_history.py` file does not have the 2.6.0 release. I think this is why all the ISCE2 programs report the version is still 2.5.3 when we run them.
@rtburns-jpl

**Comment by rtburns-jpl** [comment]
Thanks. I think we're due for a new bugfix release anyway. I'll make a hotfix for our conda-forge package, and then make a new release that includes an updated release_history.py.

**Comment by rtburns-jpl** [comment]
The conda-forge package hotfix has been merged, so if you update your conda environments isce2 should show the correct version now. I'm going to be on vacation next week, but once I get back I'll publish the new bugfix release.

**Comment by yunjunz** [comment]
Thank you for the hotfix @rtburns-jpl. Any idea why the conda-forge version on osx for python 3.7 and 3.9 is failing and not available?

**Comment by rtburns-jpl** [comment]
I think there is an upstream issue in gdal causing `Symbol not found: _ZSTD_compressBound` in our tests, which causes the package build to sometimes fail. I've been trying to update to a new version of gdal, but this is blocked by our build failures with latest gfortran versions: https://github.com/conda-forge/isce2-feedstock/pull/49

**Comment by EJFielding** [comment]
I think we still need to modify `https://github.com/isce-framework/isce2/blob/main/release_history.py`

**Comment by EJFielding** [comment]
I added PR #561
