### ISSUE TITLE
Build Error: Arguments of iand have different kind type parameters

### ISSUE THREAD

**Issue by S0sh0rt** [isce-framework/isce2#56]
Error from scons install when building ALOS_pre_process/readOrbitPulse.f

[ isce2-master]# /usr/bin/gfortran -o /opt/isce/components/isceobj/Sensor/src/ALOS_pre_process/readOrbitPulse.o -c -O2 -Wall -ffixed-line-length-none -fno-second-underscore -fPIC -fno-range-check -m64 -I/usr/include -I/opt/isce_build/mods -J/opt/isce_build/mods /opt/isce/components/isceobj/Sensor/src/ALOS_pre_process/readOrbitPulse.f
f951: Warning: Nonconforming tab character in column 1 of line 109 [-Wtabs]
/opt/isce/components/isceobj/Sensor/src/ALOS_pre_process/readOrbitPulse.f:110:41:

  110 |      $     iand(indata(38),255)*256+iand(indata(37),255)
      |                                         1
Error: Arguments of 'iand' have different kind type parameters at (1)
/opt/isce/components/isceobj/Sensor/src/ALOS_pre_process/readOrbitPulse.f:112:41:

  112 |      $     iand(indata(42),255)*256+iand(indata(41),255)
      |                                         1
Error: Arguments of 'iand' have different kind type parameters at (1)
/opt/isce/components/isceobj/Sensor/src/ALOS_pre_process/readOrbitPulse.f:114:41:

  114 |      $     iand(indata(46),255)*256+iand(indata(45),255)
      |                                         1
Error: Arguments of 'iand' have different kind type parameters at (1)

[ isce2-master]# /usr/bin/gfortran --version
GNU Fortran (GCC) 9.2.0

**Comment by piyushrpt** [comment]
The solution to this would be something like this:

```
!c Do this early in the function
integer*2 b1, b2, b3, b4  

...
!c Whenever you want to interpret 4 bytes as big endian int32
b1 = indata(40)
b2 = indata(39)
b3 = indata(38)
b4 = indata(37)
```
and then use these integer*2 variables in the iand statements.

This error is due to gfortran in gcc9 complying with the standards unlike earlier versions which were lax.

**Comment by S0sh0rt** [comment]
I am not a developer and have not worked with Fortran for 30 years.
It is probably best for someone else to make the adjustment.

Chris
