### ISSUE TITLE
Combined MTI Procesing

### ISSUE THREAD

**Issue by hariiirs** [isce-framework/isce2#575]
Dear All

I have processed first five steps of PSI as well as SBAS. Since I want to apply combined MTI processing, therefore I need to merge both PS and SB pixels. For that I run -

>> ps_sb_merge 

While running this command in matlab, I got the following error message-
![1](https://user-images.githubusercontent.com/42439461/188109641-b5fc014a-fea3-4817-a2e6-4db3e6109f58.png)

Kindly suggest me the possible solution for the same.

with regards
Hari Shankar

**Comment by EJFielding** [comment]
I guess you are using StaMPS. I think you will get more help on a StaMPS forum. This error has nothing to do with ISCE2.
