### ISSUE TITLE
The problem of mergeing dem with water failed

### ISSUE THREAD

**Issue by Xin-Wang-520** [isce-framework/isce2#601]
I recently processed the D-InSAR of the Mexico earthquake, I found that a part of the sentinel image covered by ESA is inside the sea, as shown below, a large part is inside the water, there is no dem inside the water, how to do without water, how to splice it, do you know this, I tried to splice the whole area, there is no dem without water, and finally the splicing dem failed, how to solve it?
![2022-10-19 09-36-02 的屏幕截图](https://user-images.githubusercontent.com/96721536/197124153-02eca98c-db1a-49af-b858-a403fc08b74c.png)
![2022-10-19 09-40-03 的屏幕截图](https://user-images.githubusercontent.com/96721536/197124187-b3cfb7a6-81cb-4aa4-959b-004da385d831.png)

**Comment by Xin-Wang-520** [comment]
@EJFielding Do you konw that?

**Comment by EJFielding** [comment]
If you use the `-f` flag with `dem.py` then it will fill the water with "no data" and you can use it for ISCE2 processing.

**Comment by Xin-Wang-520** [comment]
> If you use the `-f` flag with `dem.py` then it will fill the water with "no data" and you can use it for ISCE2 processing.

Thank you ,I've solved the dem mergeing problem.But when I run topsapp.py insarApp2.xml, I get the following problem: Exception: Coherence threshold too strict. No points left for reliable ESD estimate. Is it caused by water? This is my insarApp2.xml and log file. Do you know how to solve it?Do you want to change Coherence threshold, how to change it?
![2022-10-24 12-16-10 的屏幕截图](https://user-images.githubusercontent.com/96721536/197447832-afc3e0ba-8475-478c-a09c-7220d041369e.png)


![2022-10-24 12-20-26 的屏幕截图](https://user-images.githubusercontent.com/96721536/197447924-cc788254-c771-4392-a394-947f524d3db6.png)
[isce.log](https://github.com/isce-framework/isce2/files/9848715/isce.log)

**Comment by EJFielding** [comment]
Yes, the ESD calculations won't work well if a large part of your image is water. A good solution is to turn off the ESD calculation in your "topsApp.xml" file.
`<property name="do ESD">False</property>`

**Comment by Xin-Wang-520** [comment]
> Yes, the ESD calculations won't work well if a large part of your image is water. A good solution is to turn off the ESD calculation in your "topsApp.xml" file. `<property name="do ESD">False</property>`

thank you
