### ISSUE TITLE
Unable install isce2 on macOS Monterey (v12.6.1)

### ISSUE THREAD

**Issue by rprasanth49** [isce-framework/isce2#608]
Hello All,

I am new to Mac world and isce. I am trying to get isce2 installed on mac (Monterey 12.6.1) but facing various issue while trying to build GCC in the process. I would not move past building gcc on every method I tried to install isce2. I have listed all the methods I tried so far below. Is there something I am missing on the mac or in my process of doing the installation? Is there any documentation to install the isce with the latest libraries on the latest version of mac? I cannot seem to find anything that is working. Sorry for asking this type of question here but this is my second week trying to install isce2 and still no success. Looking for some kind of help on setting up the system.

Methods tried so far to install the isce2:

1. Tried to install isce2 and all dependencies individually using Anaconda but I was always getting isce2 is not installed from Python. 
2.  Installed MacPorts and tried to install dependencies and it failed the first to install the gcc7 saying unsupported mac OS version.
3. Tried to use the .install.sh file to install the dependencies and isce but again building GCC failed to stating that \lib\cpp fails sanity check. Used this link has reference - http://etdedata.gein.noa.gr/ISCE_UNAVCO/ISCE-2.0.0_201511.pdf
4. Formatted the mac and started the fresh install using install.sh from the setup folder in isce2 but faced the same issue as in method 3 (\lib\cpp fails sanity check)
5. I even tried Google Colab by following this link (https://colab.research.google.com/github/SERVIR/ForestStandHeight/blob/master/Section_2/Install_ISCE.ipynb) and still no luck. 

Thanks,
Prasanth

**Comment by eai-eo** [comment]
You can try this: [https://github.com/parosen/Geo-SInC/blob/main/UNAVCO2022/0.6_Installation_of_ISCE_using_conda_and_containers/funning_isce_installation.pdf](url) 

Install Anaconda
conda config --add channels conda-forge
conda config --set channel_priority strict
Make the isce_requirements.txt file:
> 	python=3.8.6
	cython
	gdal
	git
	h5py
	libgdal
	pytest
	numpy
	fftw
	scipy
	basemap
	scons
        Opencv
        
conda create --name isce2env --file isce_requirements.txt
conda activate isce2env
conda install isce2
(if necessary, symlink cython to cython3)
(set your PYTHONPATH, ISCE_HOME etc variables)

**Comment by rprasanth49** [comment]
The above-mentioned steps worked for me and now I am able to call isce in python. Thank you very much @eai-eo for your help here.

**Comment by eai-eo** [comment]
Great, you're welcome!
