### ISSUE TITLE
HELP,I can't run stamps(1,1),did anyone met like that 

### ISSUE THREAD

**Issue by jerry7nol** [isce-framework/isce2#616]
i run stamps after finished isce, but i can't solve this problem.

![image](https://user-images.githubusercontent.com/111356557/200206343-8de993c6-eae7-4be2-9ea2-258450a91d58.png)
or like this, in this directory
![image](https://user-images.githubusercontent.com/111356557/200206356-838079bf-8033-4b62-bdd3-85851a27e5b8.png)

**Comment by rtburns-jpl** [comment]
This looks like an issue with StaMPS rather than isce2.
