### ISSUE TITLE
Issue by visualizing ---> sh: 1: mdx: not found

### ISSUE THREAD

**Issue by alevasca** [isce-framework/isce2#624]
Hello everyone,

I just installed the latest version of ISCE2 on Python 3.9. I did a first test with topsApp.py and the processing worked. However, when I try to visualize the files with mdx.py, I got this message:

```
22122018_28122022_DESC/interferogram/merged$ mdx.py filt_topophase.unw.geo
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
Running: mdx filt_topophase.unw.geo -s 1226 -ch1 -r4  -rtlr 4904  -ch2 -r4 -rhdr 4904  
sh: 1: mdx: not found
```
And **mdx.py** is not missing in the installation, it's there in _applications_: 

```
:~/isce/isce_env/lib/python3.9/site-packages/isce/applications$ l
ISSI.py*     __pycache__/  alos2burstApp.py*    dem.py*    downsampleDEM.py*  gdal2isce_xml.py*  insarApp.py*      isce2gis.py*  iscehelp.py*  make_raw.py*  rtcApp.py*    stripmapApp.py*  upsampleDem.py*  wbd.py*
__init__.py  alos2App.py*  dataTileManager.py*  demdb.py*  fixImageXml.py*    imageMath.py*      isce2geotiff.py*  isceApp.py*   looks.py*     mdx.py*      stitcher.py*  topsApp.py*      waterMask.py*    wbdStitcher.py*
```

Do you maybe have any clue on this issue?

**Comment by rtburns-jpl** [comment]
That error message isn't saying that `mdx.py` wasn't found, it's saying that `mdx` wasn't found. `mdx.py` is a wrapper around the lower-level `mdx` utility. Is there an `mdx` on your path? If you built isce2 yourself, it's possible `mdx` wasn't built, if it wasn't able to find all the prereqs necessary (X11, motif, etc)

**Comment by alevasca** [comment]
Thank you! Yes, I corrected a path in my .bashrc and it worked!

**Comment by rtburns-jpl** [comment]
Great! Glad it was a simple fix.

**Comment by priscillasterna** [comment]
hi, I am also getting the same error. Can you tell me what you changed in the path


Thanks in advance

**Comment by ditafaith** [comment]
@dehaumarhadi it looks like you installed the package without conda, then you suggest added the path manually.
