### ISSUE TITLE
problems with dem.py

### ISSUE THREAD

**Issue by songzwgithub** [isce-framework/isce2#625]
Hello everyone,

Sorry for the basic question, I have been having problems using dem.py. In any configuration (stitch or download....) I use the command I get messages like the one below

_dem.py -a stitch -b 51 52 -106 -105 -r -s 1 -c
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
curl -n  -L -c $HOME/.earthdatacookie -b $HOME/.earthdatacookie -k -f -O https://e4ftl01.cr.usgs.gov/MEASURES/SRTMGL1.003/2000.02.11/N51W106.SRTMGL1.hgt.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   498    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
**curl: (22) The requested URL returned error: 401**
2022-11-21 21:47:28,436 - isce.contrib.demUtils.DemStitcher - WARNING - There was a problem in retrieving the file  https://e4ftl01.cr.usgs.gov/MEASURES/SRTMGL1.003/2000.02.11/N51W106.SRTMGL1.hgt.zip. Exception 
Could not create a stitched DEM. Some tiles are missing
N51W106.SRTMGL1.hgt.zip = failed_

I've already set up .netrc, and indeed I've already used it with success dem.py several days ago.
I've extracted the dataset link from dem.py output and used it with success into wget https://e4ftl01.cr.usgs.gov/MEASURES/SRTMGL1.003/2000.02.11/N51W106.SRTMGL1.hgt.zip

Do you have any suggestions in this regard?

Thank you very much and good work

**Comment by EJFielding** [comment]
You might have hit a temporary problem. The same command worked for me:
```
dem.py -a stitch -b 51 52 -106 -105 -r -s 1 -c
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
curl -n  -L -c $HOME/.earthdatacookie -b $HOME/.earthdatacookie -k -f -O https://e4ftl01.cr.usgs.gov/MEASURES/SRTMGL1.003/2000.02.11/N51W106.SRTMGL1.hgt.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   498    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   291    0   291    0     0    173      0 --:--:--  0:00:01 --:--:--   265
  0   267    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100 3949k  100 3949k    0     0   528k      0  0:00:07  0:00:07 --:--:--  810k
API open (R): ./demLat_N51_N52_Lon_W106_W105.dem
API close:  ./demLat_N51_N52_Lon_W106_W105.dem
Writing geotrans to VRT for ./demLat_N51_N52_Lon_W106_W105.dem
GDAL open (R): ./demLat_N51_N52_Lon_W106_W105.dem.vrt
API open (WR): demLat_N51_N52_Lon_W106_W105.dem.wgs84

    << Geoid Correction I2 SRTM>>

Jet Propulsion Laboratory - Radar Science and Engineering


Sampling Geoid at grid points -  Longitude Samples:    13 Latitude Lines:    13
Corner Geoid Heights (m) =  -20.82 -21.01 -21.89 -22.51

Correcting data to geoid height...

At line:      512
At line:     1024
At line:     1536
At line:     2048
At line:     2560
At line:     3072
At line:     3584
GDAL close: ./demLat_N51_N52_Lon_W106_W105.dem.vrt
API close:  demLat_N51_N52_Lon_W106_W105.dem.wgs84
API open (R): demLat_N51_N52_Lon_W106_W105.dem.wgs84
API close:  demLat_N51_N52_Lon_W106_W105.dem.wgs84
Writing geotrans to VRT for demLat_N51_N52_Lon_W106_W105.dem.wgs84
Writing geotrans to VRT for /Users/fielding/Downloads/demLat_N51_N52_Lon_W106_W105.dem.wgs84
N51W106.SRTMGL1.hgt.zip = succeded
```

**Comment by songzwgithub** [comment]
Thanks for your answer. The command still doesn't work, but I've successfully downloaded the DEM through the - u option. The full command is  _dem.py -a stitch -b 51 52 -106 -105 -r -s 1 -c -u http://step.esa.int/auxdata/dem/SRTMGL1/_.

**Comment by FedeDC** [comment]
Maybe try with -n and -w arguments. The .netrc file may not working for you.
- n is for the username and -w for password
dem.py -a stitch -b 51 52 -106 -105 -r -s 1 -c -n username -w pass

**Comment by priyanka-duIn** [comment]
Hello all
I am having problem using dem.py. I am trying to stitch the DEM but constantly getting an error.

_dem.py -a stitch -b 31 32 78 79 -r -s 1 -c_

Using default ISCE Path: /home/miniforge3/envs/isce2/lib/python3.11/site-packages/isce
curl -n  -L -c $HOME/.earthdatacookie -b $HOME/.earthdatacookie -k -f -O http://step.esa.int/auxdata/dem/SRTMGL1/N31E078.SRTMGL1.hgt.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to open the file N31E078.SRTMGL1.hgt.zip: Permission denied
  0 17.2M    0 13418    0     0  21521      0  0:14:01 --:--:--  0:14:01 21503
curl: (23) Failure writing output to destination
2025-01-06 16:12:00,506 - isce.contrib.demUtils.DemStitcher - WARNING - There was a problem in retrieving the file  http://step.esa.int/auxdata/dem/SRTMGL1/N31E078.SRTMGL1.hgt.zip. Exception 
Could not create a stitched DEM. Some tiles are missing
N31E078.SRTMGL1.hgt.zip = failed

I stitched the DEM using the same command earlier and could able to stitch but now it's not working. I have also used -_u http://step.esa.int/auxdata/dem/SRTMGL1/_ and -n -w option but still same warning and error!. 

Could anyone help me in this regard?

Thank you!

**Comment by songzwgithub** [comment]
> Hello all I am having problem using dem.py. I am trying to stitch the DEM but constantly getting an error.
> 
> _dem.py -a stitch -b 31 32 78 79 -r -s 1 -c_
> 
> Using default ISCE Path: /home/miniforge3/envs/isce2/lib/python3.11/site-packages/isce curl -n -L -c $HOME/.earthdatacookie -b $HOME/.earthdatacookie -k -f -O http://step.esa.int/auxdata/dem/SRTMGL1/N31E078.SRTMGL1.hgt.zip % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0Warning: Failed to open the file N31E078.SRTMGL1.hgt.zip: Permission denied 0 17.2M 0 13418 0 0 21521 0 0:14:01 --:--:-- 0:14:01 21503 curl: (23) Failure writing output to destination 2025-01-06 16:12:00,506 - isce.contrib.demUtils.DemStitcher - WARNING - There was a problem in retrieving the file http://step.esa.int/auxdata/dem/SRTMGL1/N31E078.SRTMGL1.hgt.zip. Exception Could not create a stitched DEM. Some tiles are missing N31E078.SRTMGL1.hgt.zip = failed
> 
> I stitched the DEM using the same command earlier and could able to stitch but now it's not working. I have also used -_u http://step.esa.int/auxdata/dem/SRTMGL1/_ and -n -w option but still same warning and error!.
> 
> Could anyone help me in this regard?
> 
> Thank you!

Hi,
Maybe you can try the script run_download_DEM.sh. 
[run_download_DEM-main.zip](https://github.com/user-attachments/files/18328877/run_download_DEM-main.zip)
