### ISSUE TITLE
ModuleNotFoundError: No module named 'isce'

### ISSUE THREAD

**Issue by liveeo-nicolas-garcia** [isce-framework/isce2#642]
Hi! Happy holidays!

I am using the Dockerfile to run isce2 in a container. Still I find that cmake leaves the module in `.../dist-packages/isce2` But eveything tries to import the module `isce` which is not found. At the same time when I make an installation with conda, it does install the module under `.../dist-packages/isce`. Should I change something to the Dockerfile to remove that `2`?

Note: I did changed the name of the folder from `isce2` to `isce` and worked but that is definitely not a clean solution

Thanks for your attention

**Comment by rtburns-jpl** [comment]
When I wrote the cmake scripts, I thought it might be a good idea to provide a pathway for removing the isce package name in favor of isce2. So while scons installs to an `isce` directory, cmake installs to `isce2`. However, the cmake scripts should also install an `isce` symlink to the isce2 installation location. Is that symlink not being installed properly?

**Comment by liveeo-nicolas-garcia** [comment]
I used the find tool in the terminal and there is no `isce` directory. So I presume it is not being installed

**Comment by liveeo-nicolas-garcia** [comment]
To close this. It was not creating the symlink in the image. I made a new Dockerfile that does not use the builder image but does everything rightaway and it worked well
