### ISSUE TITLE
Issue with conda install isce2 after numpy v1.24.0 release

### ISSUE THREAD

**Issue by Dani-Lindsay** [isce-framework/isce2#649]
Hi all,

I've just installed isce with conda and got the error while running `alos2App.py`

```
AttributeError: module 'numpy' has no attribute 'int'
```
I found the following [article](https://levelup.gitconnected.com/fix-attributeerror-module-numpy-has-no-attribute-float-d7d68c5a4971) which describes the issue people are having after the latest numpy release. I downgraded the numpy version in my environment to 1.23 and things seem to be running smoothly again. 

```
conda create -n insar_23 python=3.8
conda activate insar_23
conda install -c conda-forge isce2
conda install numpy==1.23
```

Best, 
Dani

p.s. I don't have administrative permissions on hpc so conda is the easiest way to get things installed quickly.

**Comment by rtburns-jpl** [comment]
This was fixed by https://github.com/isce-framework/isce2/pull/639. Our next conda release will include that fix.

**Comment by MSSJoud** [comment]
Yes, this is a known issue with `np.int` being removed in NumPy ≥ 1.24.

You can fix it in **two ways**:

Option 1 – Downgrade NumPy (recommended)

conda install numpy=1.23

Option 2 – Patch the source

Edit this line in `TOPSSwathSLCProduct.py` (or similar):


dtype=np.int

Change to:


dtype=int

Both methods solve the problem if you’re using ISCE2 via conda.
