### ISSUE TITLE
New numpy version issues

### ISSUE THREAD

**Issue by ekh351** [isce-framework/isce2#659]
Hi,

In the latest version of NumPy (1.24), the following attributes have been deprecated, which cause problems running topsApps.py

np.object
np.bool
np.float
np.complex
np.str
np.int

I fixed it by downgrading my numpy to version 1.23.5, but thought I should let you know.

Cheres,
Ekbal

**Comment by EJFielding** [comment]
Yes, I have seen that in other Python code. the NumPy version 1.24 has fully removed those datatypes after they were previously deprecated.
