### ISSUE TITLE
Latest release does not support `numpy>=1.20`

### ISSUE THREAD

**Issue by jtherrmann** [isce-framework/isce2#696]
The release notes for [Release 2.6.2](https://github.com/isce-framework/isce2/releases/tag/v2.6.2) include:

> * Fixes for Python 3.10+ support and modern numpy support

However, https://github.com/isce-framework/isce2/commit/735fba0bdb23b255055d8cc37222bec25246b680 for replacing the deprecated `numpy.int` alias has not yet been released, so `isce2 2.6.2` is incompatible with `numpy>=1.20`. It would be nice to get this change released so that `isce2` can support modern versions of `numpy`.

**Comment by rtburns-jpl** [comment]
Sorry about that, I've just cut release v2.6.3 and will update the conda package shortly.

> * Fixes for Python 3.10+ support and modern numpy support

Well, v2.6.2 did include some fixes for numpy 1.20+ support... just not all the changes we needed, apparently :P

**Comment by jtherrmann** [comment]
@rtburns-jpl No worries, thanks for getting that merged!
