### ISSUE TITLE
consider removing large docs/ folder to separate repo

### ISSUE THREAD

**Issue by scottyhq** [isce-framework/isce2#7]
First of all, thanks so much for open-sourcing ISCE! It's excellent software and it's great that more people now have access to it. Hopefully the move to github facilitates more community contributions.

The tutorial material is fantastic under the docs/ directory, but the file sizes are large and it would be great to separate this from the source code (in particular it will speed up cloning and building packages). Currently, cloning the repo locally results in **287Mb** because the folder is also kept track of in the hidden .git/ folder.

An easy solution is to move the docs to another repository (e.g. isce-framework/isce2-docs). I've confirmed that you can remove these files and commit history with the following commands:

```bash
cp -r docs/ ../isce2-docs
git filter-branch --tree-filter 'rm -rf docs' --prune-empty HEAD
git for-each-ref --format="%(refname)" refs/original/ | xargs -n 1 git update-ref -d
echo docs/ >> .gitignore
git add .gitignore
git commit -m 'Removing docs/ from git history'
rm -Rf .git/logs .git/refs/original
git gc --prune=all --aggressive
git push origin master --force
git pull
rm -Rf .git/logs .git/refs/original
git gc --prune=all --aggressive
```

The repo is then reduced to **29Mb**. I think that with the above solution people who have already forked this repository will have to re-fork to be in sync since the commit history changes.

**Comment by piyushrpt** [comment]
We are working on this. We would like to do this before making a release, to allow ports and other package managers to build with the smaller repo.

**Comment by piyushrpt** [comment]
Should be done now. There is a separate repo for docs now https://github.com/isce-framework/isce2-docs .

**Comment by scottyhq** [comment]
Thanks @piyushrpt, note that the large files are still there in the hidden ".git" folder. See the last 3 commands above for how to remove them. The releases don't have the .git/ folder and as a result are much smaller.

**Comment by piyushrpt** [comment]
Looking into it.

**Comment by rtburns-jpl** [comment]
You can avoid having to download the large files as of https://github.com/isce-framework/isce2/commit/9ede3f053f4e4c9ab0ca304c9e7d5987f6674692 by shallow cloning e.g. with `--depth=1`. But if we're open to changing the commit history it's probably a good idea to nip this one in the bud.

**Comment by piyushrpt** [comment]
I agree. If the repo cloning is for deployment, using depth significantly reduces the size. I'm not able to reduce the size below 140MB. Will need to look deeper.

**Comment by rtburns-jpl** [comment]
Filter-branch wasn't working for me so I eventually just went with [bfg](https://rtyley.github.io/bfg-repo-cleaner).
````
git clone --mirror git://github.com/isce-framework/isce2
curl https://repo1.maven.org/maven2/com/madgag/bfg/1.13.0/bfg-1.13.0.jar > bfg.jar
java -jar bfg.jar --delete-folders docs isce2.git
cd isce2.git
git gc --prune=all
````
You can then force push the local mirror. It should be about 29MB when cloned.

**Comment by piyushrpt** [comment]
Looks like this should be done now? You might have to refork. Can you test this?

**Comment by scottyhq** [comment]
Looks good. down to 29Mb
