### ISSUE TITLE
Verify normalization in rtcApp.py

### ISSUE THREAD

**Issue by piyushrpt** [isce-framework/isce2#70]
rtcApp appears to use the following equation:
https://github.com/isce-framework/isce2/blob/master/components/isceobj/RtcProc/runNormalize.py#L45

This suggests that the input image was in sigma0 to start with like UAVSAR. I think the correct term is just the numerator term if Sentinel1 GRD data was unpacked to beta0. 

@MIRSL can you confirm the interpretation?

**Comment by sgk0** [comment]
The normalization should be fine, it is the formula for the projection angle approach (Ulander 1996), see this thread: http://earthdef.caltech.edu/boards/4/topics/3093.

**Comment by piyushrpt** [comment]
Great. Thanks for confirming. Closing this.
