### ISSUE TITLE
The unwrapping step is slowly

### ISSUE THREAD

**Issue by InSAR2023** [isce-framework/isce2#712]
Functions to be executed:
['Function-1']
Running: unwrap
['--ifg', '/media/insar/53bb474c-9882-4dbd-a577-cfaa886beb00/NewZealand/merged/interferograms/20220101_20220125/filt_fine.int', '--unw', '/media/insar/53bb474c-9882-4dbd-a577-cfaa886beb00/NewZealand/merged/interferograms/20220101_20220125/filt_fine.unw', '--coh', '/media/insar/53bb474c-9882-4dbd-a577-cfaa886beb00/NewZealand/merged/interferograms/20220101_20220125/filt_fine.cor', '--reference', '/media/insar/53bb474c-9882-4dbd-a577-cfaa886beb00/NewZealand/reference', '--defomax', '2', '--rlks', '4', '--alks', '1', '--method', 'snaphu']
unwrapping method :  snaphu

snaphu v1.4.2
Reading wrapped phase from file /media/insar/53bb474c-9882-4dbd-a577-cfaa886beb00/NewZealand/merged/interferograms/20220101_20220125/filt_fine.int
No weight file specified.  Assuming uniform weights
Reading correlation data from file /media/insar/53bb474c-9882-4dbd-a577-cfaa886beb00/NewZealand/merged/interferograms/20220101_20220125/filt_fine.cor
Calculating smooth-solution cost parameters
Initializing flows with MCF algorithm
Integrating phase
Writing output to file /media/insar/53bb474c-9882-4dbd-a577-cfaa886beb00/NewZealand/merged/interferograms/20220101_20220125/filt_fine.unw
Growing connected components on second pass

snaphu v1.4.2
Reading unwrapped phase from file /media/insar/53bb474c-9882-4dbd-a577-cfaa886beb00/NewZealand/merged/interferograms/20220101_20220125/filt_fine.unw
No weight file specified.  Assuming uniform weights
Reading correlation data from file /media/insar/53bb474c-9882-4dbd-a577-cfaa886beb00/NewZealand/merged/interferograms/20220101_20220125/filt_fine.cor
Calculating smooth-solution cost parameters
Growing connected component mask
Writing connected components to file /media/insar/53bb474c-9882-4dbd-a577-cfaa886beb00/NewZealand/merged/interferograms/20220101_20220125/filt_fine.unw.conncomp
time used: 155 mins 3.7 secs.

**Comment by comma-never-coma** [comment]
A clear explanation was given by @EJFielding from [https://forum.step.esa.int/t/long-processing-time-for-phase-unwrapping-snaphu/35306/5](url)
> The amount of memory that SNAPHU requires to run depends on the number of pixels in each tile. If you are trying to unwrap an interferogram without any multilooking, then you will have much larger images. If your SNAPHU program is using a large percentage of the memory on your computer, it may run very slowly even if it does not get an “out of memory” error.

As mentioned above, I recommend to apply larger range looks and azimuth looks, such as "10:2" or "20:4". Otherwise you have to make sure that computer memory is sufficient.

**Comment by InSAR2023** [comment]
> 

Thank you so much.
