### ISSUE TITLE
run_01_unpack_topo_reference

### ISSUE THREAD

**Issue by bboudhane** [isce-framework/isce2#719]
Completed Parsing the Configuration file
Functions to be executed:
['Function-1', 'Function-2']
Running: Sentinel1_TOPS
['--dirname', '/home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip', '--swaths', '1 2 3', '--orbitdir', '/home/boudhane/Desktop/ascen/orbits', '--outdir', '/home/boudhane/Desktop/ascen/reference', '--auxdir', '/home/boudhane/Desktop/ascen/auxdir', '--bbox', '-3.1853 -1.3878 28.6672 31.071', '--pol', 'vv']
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
Input XML files:  ['/vsizip//home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/annotation/s1a-iw1-slc-vv-20141228t162010-20141228t162035-003921-004b60-004.xml']
Input TIFF files:  ['/vsizip//home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/measurement/s1a-iw1-slc-vv-20141228t162010-20141228t162035-003921-004b60-004.tiff']
Manifest files:  ['/vsizip//home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/manifest.safe']
MANS:  /home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/manifest.safe
Setting IPF version to :  002.72
unclosed token: line 55323, column 6
Input XML files:  ['/vsizip//home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/annotation/s1a-iw2-slc-vv-20141228t162008-20141228t162033-003921-004b60-005.xml']
Input TIFF files:  ['/vsizip//home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/measurement/s1a-iw2-slc-vv-20141228t162008-20141228t162033-003921-004b60-005.tiff']
Manifest files:  ['/vsizip//home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/manifest.safe']
MANS:  /home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/manifest.safe
Setting IPF version to :  002.72
unclosed token: line 55323, column 6
Input XML files:  ['/vsizip//home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/annotation/s1a-iw3-slc-vv-20141228t162009-20141228t162034-003921-004b60-006.xml']
Input TIFF files:  ['/vsizip//home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/measurement/s1a-iw3-slc-vv-20141228t162009-20141228t162034-003921-004b60-006.tiff']
Manifest files:  ['/vsizip//home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/manifest.safe']
MANS:  /home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/manifest.safe
Setting IPF version to :  002.72
unclosed token: line 55323, column 6
Running: topo
['--reference', '/home/boudhane/Desktop/ascen/reference', '--dem', '/home/boudhane/Desktop/ascen/DEM/demLat_S04_S01_Lon_E028_E032.dem.wgs84', '--geom_referenceDir', '/home/boudhane/Desktop/ascen/geom_reference', '--numProcess', '1']
running in parallel with 1 processes
Traceback (most recent call last):
  File "/home/boudhane/tools_insar/proc_insar/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 251, in <module>
    main(args.start,args.end)
  File "/home/boudhane/tools_insar/proc_insar/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 242, in main
    cfgParser.runCmd()
  File "/home/boudhane/tools_insar/proc_insar/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 54, in runCmd
    func_modules.main(self.funcParams[section])
  File "/home/boudhane/tools_insar/proc_insar/isce2/contrib/stack/topsStack/topo.py", line 112, in main
    bbox = [np.min(boxes[:,0]), np.max(boxes[:,1]), np.min(boxes[:,2]), np.max(boxes[:,3])]
                   ~~~~~^^^^^
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by jerry7nol** [comment]
> Completed Parsing the Configuration file Functions to be executed: ['Function-1', 'Function-2'] Running: Sentinel1_TOPS ['--dirname', '/home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip', '--swaths', '1 2 3', '--orbitdir', '/home/boudhane/Desktop/ascen/orbits', '--outdir', '/home/boudhane/Desktop/ascen/reference', '--auxdir', '/home/boudhane/Desktop/ascen/auxdir', '--bbox', '-3.1853 -1.3878 28.6672 31.071', '--pol', 'vv'] This is the Open Source version of ISCE. Some of the workflows depend on a separate licensed package. To obtain the licensed package, please make a request for ISCE through the website: https://download.jpl.nasa.gov/ops/request/index.cfm. Alternatively, if you are a member, or can become a member of WinSAR you may be able to obtain access to a version of the licensed sofware at https://winsar.unavco.org/software/isce Input XML files: ['/vsizip//home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/annotation/s1a-iw1-slc-vv-20141228t162010-20141228t162035-003921-004b60-004.xml'] Input TIFF files: ['/vsizip//home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/measurement/s1a-iw1-slc-vv-20141228t162010-20141228t162035-003921-004b60-004.tiff'] Manifest files: ['/vsizip//home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/manifest.safe'] MANS: /home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/manifest.safe Setting IPF version to : 002.72 unclosed token: line 55323, column 6 Input XML files: ['/vsizip//home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/annotation/s1a-iw2-slc-vv-20141228t162008-20141228t162033-003921-004b60-005.xml'] Input TIFF files: ['/vsizip//home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/measurement/s1a-iw2-slc-vv-20141228t162008-20141228t162033-003921-004b60-005.tiff'] Manifest files: ['/vsizip//home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/manifest.safe'] MANS: /home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/manifest.safe Setting IPF version to : 002.72 unclosed token: line 55323, column 6 Input XML files: ['/vsizip//home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/annotation/s1a-iw3-slc-vv-20141228t162009-20141228t162034-003921-004b60-006.xml'] Input TIFF files: ['/vsizip//home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/measurement/s1a-iw3-slc-vv-20141228t162009-20141228t162034-003921-004b60-006.tiff'] Manifest files: ['/vsizip//home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/manifest.safe'] MANS: /home/boudhane/Desktop/ascen/slc/S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.zip S1A_IW_SLC__1SDV_20141228T162008_20141228T162035_003921_004B60_988C.SAFE/manifest.safe Setting IPF version to : 002.72 unclosed token: line 55323, column 6 Running: topo ['--reference', '/home/boudhane/Desktop/ascen/reference', '--dem', '/home/boudhane/Desktop/ascen/DEM/demLat_S04_S01_Lon_E028_E032.dem.wgs84', '--geom_referenceDir', '/home/boudhane/Desktop/ascen/geom_reference', '--numProcess', '1'] running in parallel with 1 processes Traceback (most recent call last): File "/home/boudhane/tools_insar/proc_insar/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 251, in main(args.start,args.end) File "/home/boudhane/tools_insar/proc_insar/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 242, in main cfgParser.runCmd() File "/home/boudhane/tools_insar/proc_insar/isce2/contrib/stack/topsStack/SentinelWrapper.py", line 54, in runCmd func_modules.main(self.funcParams[section]) File "/home/boudhane/tools_insar/proc_insar/isce2/contrib/stack/topsStack/topo.py", line 112, in main bbox = [np.min(boxes[:,0]), np.max(boxes[:,1]), np.min(boxes[:,2]), np.max(boxes[:,3])] ~~~~~^^^^^ IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

sir,do you solved it?,i meet the seem question like you meet
