### ISSUE TITLE
Errors in un_01_unpack_topo_reference

### ISSUE THREAD

**Issue by Technew94** [isce-framework/isce2#723]
Dear all,
when I run un_01_unpack_topo_reference, I got an error with 
GDAL open (R): ./demLat_N46_N47_Lon_E106_E108.dem.vrt
ERROR 4: ./demLat_N46_N47_Lon_E106_E108.dem.vrt: No such file or directory
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot open the file ./demLat_N46_N47_Lon_E106_E108.dem.vrt in read mode.
2023-05-26 04:48:34,216 - isce.zerodop.topozero - WARNING - Default Peg heading set to: -2.890890034508479
Polynomial Order: 0 - by - 0 
0
Polynomial Order: 0 - by - 1 
801931  2.32956
GDAL open (R): ./demLat_N46_N47_Lon_E106_E108.dem.vrt
ERROR 4: ./demLat_N46_N47_Lon_E106_E108.dem.vrt: No such file or directory
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot open the file ./demLat_N46_N47_Lon_E106_E108.dem.vrt in read mode.
2023-05-26 04:48:34,366 - isce.zerodop.topozero - WARNING - Default Peg heading set to: -2.8901219925460704
Polynomial Order: 0 - by - 0 
0
Polynomial Order: 0 - by - 1 
848203  2.32956
GDAL open (R): ./demLat_N46_N47_Lon_E106_E108.dem.vrt
ERROR 4: ./demLat_N46_N47_Lon_E106_E108.dem.vrt: No such file or directory
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot open the file ./demLat_N46_N47_Lon_E106_E108.dem.vrt in read mode.
2023-05-26 04:48:34,517 - isce.zerodop.topozero - WARNING - Default Peg heading set to: -2.8915054438750887
Polynomial Order: 0 - by - 0 
0
Polynomial Order: 0 - by - 1 
848203  2.32956
GDAL open (R): ./demLat_N46_N47_Lon_E106_E108.dem.vrt
ERROR 4: ./demLat_N46_N47_Lon_E106_E108.dem.vrt: No such file or directory
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot open the file ./demLat_N46_N47_Lon_E106_E108.dem.vrt in read mode.

I'm wondering is it related to the location of orbits? Or the dem file is not overlap the AOI?
Any ideas to solve this problem?
Many thanks and all the best

**Comment by qiushuininan** [comment]
How can you solve it?

**Comment by 03ddd** [comment]
In which path did you run the run_01 command? I had the same error, the solution was to switch to the folder where the dem is stored and open the terminal with... /Stacks/run_files/run_01_ to run the command. It seems that the reason for this error is that the program restricts the opening of the dem.vrt file to relative paths only!
