### ISSUE TITLE
module 'isce' has no attribute 'stanford_license'

### ISSUE THREAD

**Issue by wjx325** [isce-framework/isce2#726]
I installed isce 2.6.3 through conda, and I can run programs such as topsApp.py normally, but when I run insarApp.py, an error will be reported:

Traceback (most recent call last):
  File "/home/wjx/anaconda3/envs/isce/lib/python3.9/site-packages/isce/applications/insarApp.py", line 1194, in <module>
    if not isce.stanford_license:
AttributeError: module 'isce' has no attribute 'stanford_license'

what should I do？

**Comment by EJFielding** [comment]
The ISCE2 `insarApp.py` requires some extra components that are not available in the GitHub version of ISCE (the ones that require the stanford_license), and that app is also very old, so it is not going to work. You should use stripmapApp.py instead.
