### ISSUE TITLE
Ion parameter file is not specified. Ionospheric estimation will not be done 

### ISSUE THREAD

**Issue by xiangbenzhang** [isce-framework/isce2#742]
hello,everybody
When I run the following command, a prompt appeared after generating the run_files file. I don't know what this prompt means? Is it a problem that must be solved? I am a rookie, please do n’t have to dislike my question, thank you for help.
The input code is：stackSentinel.py -s /media/xiangben/祥本硬盘/ubuntu/isce2/SLC/ -d /media/xiangben/ 祥本硬盘/ubuntu/isce2/DEM/demLat_N40_N43_Lon_E123_E125.dem.wgs84 -a /media/xiangben/祥本硬盘/ubuntu/isce2/AuxDir -o /media/xiangben/祥本硬盘/ubuntu/isce2/Orbits -b ' 41.80 41.87 123.84 124.01' -w slc -z 4 -r 20
The prompt you get is this：Ion parameter file is not specified. Ionospheric estimation will not be done

**Comment by Raven-svt** [comment]
请问这个问题你解决了吗？我也遇到了这个问题

**Comment by xiangbenzhang** [comment]
没有

**Comment by rtburns-jpl** [comment]
The ionospheric estimation is an optional step in stackSentinel.py. If you don't provide the parameter file, it's no problem, the rest of the workflow will proceed as normal.
