### ISSUE TITLE
The PAZ images (Spotlight Mode) processing with ISCE

### ISSUE THREAD

**Issue by InSAR2023** [isce-framework/isce2#745]
Hello everyone,

Is it possible to PAZ images (Spotlight Mode) processing with ISCE?

Best regards,

**Comment by EJFielding** [comment]
The ISCE2 software does not support spotlight modes completely from PAZ or any other satellites. You can try processing a spotlight SLC pair with stripmapApp, but you may get some phase distortions, especially far from the center of the spotlight scene.

**Comment by InSAR2023** [comment]
> The ISCE2 software does not support spotlight modes completely from PAZ or any other satellites. You can try processing a spotlight SLC pair with stripmapApp, but you may get some phase distortions, especially far from the center of the spotlight scene.

Thank you so much dear Prof. EJFielding
