### ISSUE TITLE
stackSentinel.py for single burst to process is wrong！！！

### ISSUE THREAD

**Issue by ZGHHGZ** [isce-framework/isce2#756]
**Coregistered stack of SLC**
 
When I used stackSentinel.py and selected the study area to be located in a single burst, an error occurred in 'run_07_pairs_misreg'.
When the study area covers multiple bursts, this error will not occur.

This is the processing command and parameters used
> os.system("python /home/jovyan/iscepredata/code/topsStack/stackSentinel.py -s ../process/data -d ./data/dem/full_res.dem.wgs84  -a ./data/aux_cal/ -o ./data/orbits -C NESD  -W slc -n '2'"+roi)

Here are some screenshots of single burst processing。
![8992909dbfabc2e86cbc236be3d962f2](https://github.com/isce-framework/isce2/assets/88225620/007f2c24-dd1e-4650-816a-317b94941f7d)
![5d3022a7879ba1ab05721a432a6724e0](https://github.com/isce-framework/isce2/assets/88225620/ad62cb6c-796c-4eac-92e1-7b80369895b8)
![1aced17b99df540437620af68aeed0e1](https://github.com/isce-framework/isce2/assets/88225620/9fdcdd74-6504-44ed-9889-af3b50bdaff8)
**What should I do to handle a single burst ?**

**Comment by EJFielding** [comment]
If you want to process only one burst, then you cannot do the ESD (Enhanced Spectral Diversity) and "misreg" calculation because that requires overlap between at least two bursts. You have to use the "geometry" only coregistration.

**Comment by ZGHHGZ** [comment]
Thanks. I have found a solution, as you said.

**Comment by EJFielding** [comment]
Good to hear you found the solution. Please close the issue.

**Comment by suatcoskun** [comment]
Hi @ZGHHGZ  I tried to process single burst with isce2. I choose geometry option but if  I set bbox (very small area) isce2 always choose 2 burst. Do you have any advice?

Best
Suat
