### ISSUE TITLE
Can I run isce on a Windows 11 system？

### ISSUE THREAD

**Issue by ZGHHGZ** [isce-framework/isce2#758]
Currently, ISCE can only run on Linux systems. Can I easily migrate it to Windows systems? Especially for the handling process of stackSentinel.

**Comment by geniusinaction** [comment]
Have you installed WSL (Windows Subsytem for Linux)? I have ISCE working in that environment with no issues.

**Comment by rtburns-jpl** [comment]
Going to mark this as resolved. As I understand, lots of users have had good results under WSL and we'd be happy to help out if you have any issues under that environment. As for natively building isce2 for Windows, it's my understanding that porting it over would be a pretty big undertaking and isn't something we're planning to do.
