### ISSUE TITLE
Unnecessary 'cv2' import in topsStack/Stack.py

### ISSUE THREAD

**Issue by feigl** [isce-framework/isce2#765]
https://github.com/isce-framework/isce2/blob/0dbb1679b61b4ac385c537269b91208e57024672/contrib/stack/topsStack/Stack.py#L1646

I get the error:

File "/opt/conda/envs/maise/share/isce2/topsStack/Stack.py", line 1646, in getkmlQUAD
    import cv2
ModuleNotFoundError: No module named 'cv2'

Looking at the code, I don't see any other mention of "cv2".

Any suggestions?

**Comment by geniusinaction** [comment]
It's missing opencv, which can be installed with pip:

`  pip install opencv-python`

**Comment by rtburns-jpl** [comment]
Gareth is correct, you can simply install the opencv python package to resolve this.

But digging a little deeper:

> Looking at the code, I don't see any other mention of "cv2".

That's a good point, I don't see why this import is here. Maybe you'll still end up needing cv2 for other parts of the code, but I think we should remove the extraneous import from this file.
