### ISSUE TITLE
Unable to find the orbit file for Envisat using the unpackFrame_ENV.py~

### ISSUE THREAD

**Issue by saeedmhanna1** [isce-framework/isce2#770]
I downloaded [Doris orbit files (version F)]( https://earth.esa.int/eogateway/catalog/envisat-doris-precise-orbit-state-vectors-dor-vor_ax-), and inside the `unpackFrame_ENV.py` I modified the path to the relevant directory. 
However, I keep getting an error: `Exception: Envisat orbit file could not be found in /home/jovyan/Envisat_Hama/ENVISAT/VOR/ORB`. 

`
obj.orbitDir = '/home/jovyan/Envisat_Hama/ENVISAT/VOR/ORB'
`
`obj.instrumentDir = '/home/jovyan/Envisat_Hama/ENVISAT/data/raw/ASAR_Auxiliary_Files/ASA_INS_AX'`

Can you please suggest what are the required orbit files, and how i can get them to work.

**Comment by alexnaoki** [comment]
Double-check the start and end orbit dates.

**Comment by saeedmhanna1** [comment]
Thanks Alex, it worked.
