### ISSUE TITLE
How to generate *.slc.full file (not *.slc.full.vrt)

### ISSUE THREAD

**Issue by gjustin40** [isce-framework/isce2#772]
I used ISCE2 to create an interferogram stack for use in Miaplpy. 

The list of files used in Miaplpy appears as follows:
(This is the example data of `PichinchaSenDT142` in Miaplpy)
![image](https://github.com/isce-framework/isce2/assets/25999141/918fc5ea-7faa-484d-a948-851efa182eba)

However, the files I generated using ISCE2 do not include *.slc.full files.
![image](https://github.com/isce-framework/isce2/assets/25999141/e285a59e-bffb-4417-a760-7c8b1fcdcc30)

The command I used is as follows:
```
stackSentinel.py -s SLC/ -d DEM/*.dem.wgs84 -a AuxDir/ -o Orbits/ -b "{bbox}" -c 2
```

How can I generate the *.slc.full files?

**Comment by gjustin40** [comment]
The reason of Issue was path problem.

**Comment by hy935** [comment]
hello，i encounter the same question，i see you said it is path question，how to fix it，thanks！

**Comment by gjustin40** [comment]
@hy935 
I'm not exactly sure where the problem is occurring,
but it seems that an error occurs during a specific step of ISCE2, resulting in the final output not being produced.

Therefore, please carefully check the results of each run step in ISCE2.

Before running the run_file for ISCE2(if you are trying to implement MiaplPy),
please make sure the `gdal_translate` command works correctly.
(In my case, an error occurred because of this command.)

**Comment by hy935** [comment]
@gjustin40 Thanks ,I have solved this problem.

**Comment by xiao-cai-ji0122** [comment]
I encountered the same situation. There was no slc.full in the merge folder, but I also changed it to an absolute path, but the same error was still reported. Why is this? How did you solve it?

**Comment by liu6054** [comment]
I also encountered this problem, how should this problem be solved?

> 谢谢，我已经解决了这个问题。

**Comment by hy935** [comment]
> I also encountered this problem, how should this problem be solved?我也遇到了这个问题，该如何解决这个问题呢？
> 
> > 谢谢，我已经解决了这个问题。
我记得当时重新检查了所有数据，好像是有的还有问题，还有就是把BBOX调大了就好了
