### ISSUE TITLE
fetchOrbit.py API address

### ISSUE THREAD

**Issue by SHP153** [isce-framework/isce2#792]
Hi, 
Copernicus Sentinel Data has moved datasets to a different address (Copernicus Data Space Ecosystem), and I cannot find a new appropriate API to get POEORB of Sentinel-1 through fetchOrbit.py. 

According to Copernicus Sentinel Data, this is new address:
https://dataspace.copernicus.eu/

Could you plz help me to find the new API to use fetchOrbit.py for download orbit data automatically ?

**Comment by rtburns-jpl** [comment]
Some other users have referred to Scott's sentineleof tool (https://github.com/scottstanie/sentineleof) as a replacement. Would that be a suitable workaround for you until fetchOrbit gets updated? It looks like he has already noted the problem and updated his code to use the new URL: https://github.com/scottstanie/sentineleof/commit/324581af120ba842febda7d74a86b40ddbd77b2e
