### ISSUE TITLE
Failed to find S1A orbits for tref 2019-03-30 10:03:10、IndexError: list index out of range

### ISSUE THREAD

**Issue by BianSun** [isce-framework/isce2#794]
stackSentinel.py -s ../SLC/ -d ../DEM/demLat_N30_N31_Lon_E120_E122.dem.wgs84 -a ../AuxDir/ -o ../Orbits -b '30.03 30.59 120.35 121.15' -W slc
Number of SAFE files found: 22
*****************************************
20190330
orbit was not found in the /media/wanchao/Elements/insar/hzbay/Orbits
downloading precise or restituted orbits ...
fetchOrbit.py -i /media/wanchao/Elements/insar/hzbay/SLC/S1A_IW_SLC__1SDV_20190330T100243_20190330T100310_026566_02FA62_C06C.zip -o /media/wanchao/Elements/insar/hzbay/Process/orbits/20190330
Reference time:  2019-03-30 10:03:10
Satellite name:  S1A
Failed to find S1A orbits for tref 2019-03-30 10:03:10
Traceback (most recent call last):
  File "/home/wanchao/isce2/contrib/stack/topsStack/stackSentinel.py", line 1023, in <module>
    main(sys.argv[1:])
  File "/home/wanchao/isce2/contrib/stack/topsStack/stackSentinel.py", line 985, in main
    acquisitionDates, stackReferenceDate, secondaryDates, safe_dict, updateStack = checkCurrentStatus(inps)
  File "/home/wanchao/isce2/contrib/stack/topsStack/stackSentinel.py", line 878, in checkCurrentStatus
    acquisitionDates, stackReferenceDate, secondaryDates, safe_dict = get_dates(inps)
  File "/home/wanchao/isce2/contrib/stack/topsStack/stackSentinel.py", line 305, in get_dates
    safeObj.get_orbit(inps.orbit_dirname, inps.work_dir)
  File "/home/wanchao/isce2/contrib/stack/topsStack/Stack.py", line 1824, in get_orbit
    self.orbit =  orbitFile[0]
IndexError: list index out of range

**Comment by BianSun** [comment]
I have tried some methods, but there are still some mistakes. 
I wonder how I should solve this problem.😭

**Comment by mirzawaqar** [comment]
@BianSun did you manage to solve this issue or not yet?

**Comment by DACRJ** [comment]
I am experiencing the same problem, may I ask how you solved it?

**Comment by hariiirs** [comment]
I am also getting the same error message. Did you got the solution?
