### ISSUE TITLE
How to use stackSentinel to handle only a small area of a single burst？

### ISSUE THREAD

**Issue by ZGHHGZ** [isce-framework/isce2#807]
The smallest unit of stackSentinel for data alignment is the burst, but my study area is often very small, maybe 1/100 of a single burst, but the program needs to align the entire burst, which usually takes a long time and generates huge files, is there a modification to align only a certain area in the burst?
I looked at the program code in topsStack and found that it reads the width and length of the entire burst. It is not clear to me from which file this reading is taken and whether I can modify the data that the program needs to read to achieve my purpose.
I tried changing the length and width values within the .vrt file or .xml, but it still aligns the entire burst!

**Comment by comma-never-coma** [comment]
A feasible method is to crop combined interferograms and geom files, thus u can obtain smaller filtered and unwrapped interferograms.

**Comment by Nirdesh31** [comment]
Hi @comma-never-coma,
Can you elaborate what do you mean by 'crop combined interferograms and geom files' here? 
And what files are you referring here?

**Comment by ZGHHGZ** [comment]
> 嗨，您能详细说明一下这里的“裁剪组合干涉图和几何文件”是什么意思吗？你在这里指的是什么文件？

https://github.com/isce-framework/isce2/blob/main/contrib/timeseries/prepStackToStaMPS/bin/run_SLCcropStack.csh

This might help you。
It can be used to clip the registered SLC.

**Comment by ZGHHGZ** [comment]
> Hi @comma-never-coma, Can you elaborate what do you mean by 'crop combined interferograms and geom files' here? And what files are you referring here?


https://github.com/isce-framework/isce2/blob/main/contrib/timeseries/prepStackToStaMPS/bin/run_SLCcropStack.csh

This might help you。
It can be used to clip the registered SLC.

**Comment by comma-never-coma** [comment]
This refers to the files located under the 'merged/interferograms' and 'merged/geom_reference' directories. In fact, you can also see this section of cropped data in the sample data [Sentinel-1 on Fernandina with ISCE](https://github.com/insarlab/MintPy/blob/main/docs/demo_dataset.md) from mintpy.
BTW, I haven't tried to crop SLC with '[run_SLCcropStack.csh](https://github.com/isce-framework/isce2/blob/main/contrib/timeseries/prepStackToStaMPS/bin/run_SLCcropStack.csh)'. I just use cropped merged interferograms and geom_reference files for filtering and unwrapping later. Generating interferograms with cropped SLC looks better.

**Comment by ZGHHGZ** [comment]
> Hi @comma-never-coma, Can you elaborate what do you mean by 'crop combined interferograms and geom files' here? And what files are you referring here?



> This refers to the files located under the 'merged/interferograms' and 'merged/geom_reference' directories. In fact, you can also see this section of cropped data in the sample data [Sentinel-1 on Fernandina with ISCE](https://github.com/insarlab/MintPy/blob/main/docs/demo_dataset.md) from mintpy. BTW, I haven't tried to crop SLC with '[run_SLCcropStack.csh](https://github.com/isce-framework/isce2/blob/main/contrib/timeseries/prepStackToStaMPS/bin/run_SLCcropStack.csh)'. I just use cropped merged interferograms and geom_reference files for filtering and unwrapping later. Generating interferograms with cropped SLC looks better.

Based on isce2, I have implemented the process of only downloading a single burst for processing, first cropping and then registering. For hundreds of images, if your research area is very small, it can take 1-2 hours to complete all the processes from data download to SBAS InSAR processing.
https://github.com/ZGHHGZ/ML-TS-InSAR

**Comment by ZGHHGZ** [comment]
> 一种可行的方法是裁剪组合的干涉图和几何文件，从而获得更小的过滤和展开的干涉图。

**Comment by HN-Jiang** [comment]
Hi @comma-never-coma A quick question about cropped merged interferograms and geom_reference files. I use stackSentinel.py -W interferogram and get 01-11 step in run_files. So  if I want to use run_SLCcropStack.csh to crop interferograms to save times for unwrapping. Can I directly copy this script into my run_files folder and run it?
![图片](https://github.com/user-attachments/assets/fd182a8b-0fd9-4a91-98af-c8782188c15e)

**Comment by ZGHHGZ** [comment]
> 嗨，一个关于裁剪合并干涉图和 geom_reference 文件的快速问题。我使用 stackSentinel.py -W 干涉图并在 run_files 中得到 01-11 步骤。因此，如果我想使用 run_SLCcropStack.csh 裁剪干涉图以节省展开时间。我可以直接将此脚本复制到我的 run_files 文件夹中并运行它吗？ ![图片](https://private-user-images.githubusercontent.com/53942586/362594149-fd182a8b-0fd9-4a91-98af-c8782188c15e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMTQ0NDcsIm5iZiI6MTcyNTAxNDE0NywicGF0aCI6Ii81Mzk0MjU4Ni8zNjI1OTQxNDktZmQxODJhOGItMGZkOS00YTkxLTk4YWYtYzg3ODIxODhjMTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDEwMzU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmYTlkN2NhNTBiZTJmYjI5OGM0MzJmYWI4YWEyNGFjMzM4NmZhM2UxZTA2MTFjM2I0ZjNiNTlkNDEwYzhiMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EyfyIlT66Q9JYSI-WBDQBgWKLspmHKxxhRsM-pdX8hI)

‘isce2/contrib/timeseries/prepStackToStaMPS/bin
The SLC cropping function in ‘/run_SLCcropStack.csh’ is specifically designed to prepare data for the StaMPS software and is not adapted to the stackSentinel interferometry process. isce's stackSentinel script interferometry utilises unmerged SLC data. If you want to make the cropped merged SLC available for interferometry, you may need to modify some of the stackSentinel code.
![006de0c7cc4d68685eab37374591abb5](https://github.com/user-attachments/assets/b77d23fa-0bd8-42ce-a709-68e6e18ae0b2)

Of course, you can also try the following method for fast processing of time series InSAR.
https://github.com/ZGHHGZ/ESIS

https://github.com/ZGHHGZ/ML-TS-InSAR

**Comment by ZGHHGZ** [comment]
> Hi @comma-never-coma A quick question about cropped merged interferograms and geom_reference files. I use stackSentinel.py -W interferogram and get 01-11 step in run_files. So if I want to use run_SLCcropStack.csh to crop interferograms to save times for unwrapping. Can I directly copy this script into my run_files folder and run it? ![图片](https://private-user-images.githubusercontent.com/53942586/362594149-fd182a8b-0fd9-4a91-98af-c8782188c15e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMjM0NzEsIm5iZiI6MTcyNTAyMzE3MSwicGF0aCI6Ii81Mzk0MjU4Ni8zNjI1OTQxNDktZmQxODJhOGItMGZkOS00YTkxLTk4YWYtYzg3ODIxODhjMTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDEzMDYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMzk0ODlhMjJmZDk0MmU4ZWM5MTZiMjU4ZWE2OTU1MWFkZWU2MzEyN2VkZjJkZTM5YzY0ZTUxMzZjMTkzMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MhB4xjqwfP-IooRYgAMoN_NW1lLIveW8KYQRlRZP3sM)

‘isce2/contrib/timeseries/prepStackToStaMPS/bin
The SLC cropping function in ‘/run_SLCcropStack.csh’ is specifically designed to prepare data for the StaMPS software and is not adapted to the stackSentinel interferometry process. isce's stackSentinel script interferometry utilises unmerged SLC data. If you want to make the cropped merged SLC available for interferometry, you may need to modify some of the stackSentinel code.
![006de0c7cc4d68685eab37374591abb5](https://github.com/user-attachments/assets/b77d23fa-0bd8-42ce-a709-68e6e18ae0b2)

Of course, you can also try the following method for fast processing of time series InSAR.
https://github.com/ZGHHGZ/ESIS

https://github.com/ZGHHGZ/ML-TS-InSAR
