### ISSUE TITLE
Step unwrap process killed

### ISSUE THREAD

**Issue by Asmit-iirs** [isce-framework/isce2#808]
I am using the notebook topsApp.ipynb in the [Geo_SInC repositiry ](https://github.com/parosen/Geo-SInC.git). While running the cell `!topsApp.py --dostep=unwrap &> unwrap.log`, in section 3.9.1. The following error is displayed `/bin/bash: line 1:  6488 Killed                  topsApp.py --dostep=unwrap &> unwrap.log`

Kindly help me how can I proceed. I am using OSL and earthscope_insar environment. The log file of the particular step and the step right above it is provided. 

[filter.log](https://github.com/isce-framework/isce2/files/13907207/filter.log)
[unwrap.log](https://github.com/isce-framework/isce2/files/13907208/unwrap.log)

**Comment by EJFielding** [comment]
The process `Killed` almost always means the computer or virtual machine ran out of memory. You should make sure you don't have too many other notebooks open that might be using memory on OSL. The other option is to take more looks to reduce the size of the interferogram before doing the unwrapping step.

**Comment by Asmit-iirs** [comment]
Would it work if I crop the unwrapped inf and then run this step?

**Comment by EJFielding** [comment]
Yes, cropping a smaller area will also reduce the memory required for unwrapping.

**Comment by rtburns-jpl** [comment]
Closing as this seems to have been a memory usage issue, feel free to reopen if this is not the case.

**Comment by HN-Jiang** [comment]
> Yes, cropping a smaller area will also reduce the memory required for unwrapping.
Hello, I also have the problem with memory, so can you please tell me how to crop interferogram?
I found an answer about crop SLC (run_SLCcropStack.csh). But I think it didn't crop the interferogram.

**Comment by HN-Jiang** [comment]
> Yes, cropping a smaller area will also reduce the memory required for unwrapping.

Hello, I also have the problem with memory, so can you please tell me how to crop interferogram?
I found an answer about crop SLC (run_SLCcropStack.csh). But I think it didn't crop the interferogram @EJFielding
