### ISSUE TITLE
Can alos2App.py process several pairs or only one?

### ISSUE THREAD

**Issue by itingwanggeo** [isce-framework/isce2#820]
Hello everyone,
I am trying to process ALOS-2 ScanSAR WD1 level 1.1 data **(WBD and WWD)** with alos2App.py in ISCE. I can process a pair, but I would like to know **whether alos2App.py can process several pairs in different acquisition modes in the workflow**? I know alosStack can process several pairs like a network, but my data are in two different modes (WBD, WWD). I read the example xml for alos2App.py that just assigned one reference and one secondary product folder. **Can I assign more secondary data**?

I tried to assign the secondary data folder that contains two acquisitions, but here comes the error:
2024-02-15 16:33:34,465 - isce.insar - INFO - ISCE VERSION = 2.6.1, RELEASE_SVN_REVISION = ,RELEASE_DATE = 20220811, CURRENT_SVN_REVISION =
ISCE VERSION = 2.6.1, RELEASE_SVN_REVISION = ,RELEASE_DATE = 20220811, CURRENT_SVN_REVISION = None
The currently supported sensors are: [‘ALOS2’]
Traceback (most recent call last):
File “/home/iting/anaconda3/envs/ISCE/lib/python3.8/site-packages/isce/applications/alos2App.py”, line 1173, in
insar.run()
File “ /home/iting/anaconda3/envs/ISCE/lib/python3.8/site-packages/isce/components/iscesys/Component/Application.py ”, line 144, in run
exitStatus = self.main()
File “ /home/iting/anaconda3/envs/ISCE/lib/python3.8/site-packages/isce/applications/alos2App.py”, line 1061, in main
self.runPreprocessor()
File “/home/iting/anaconda3/envs/ISCE/lib/python3.8/site-packages/isce/components/isceobj/Alos2Proc/Factories.py”, line 40, in call
return self.method(self.other, *args, **kwargs)
File “/home/iting/anaconda3/envs/ISCE/lib/python3.8/site-packages/isce/components/isceobj/Alos2Proc/runPreprocessor.py”, line 41, in runPreprocessor
firstFrameSecondary = ledFilesSecondary[0].split(‘-‘)[-3][-4:]
**IndexError: list index out of range**

Is there anyone know how to deal with this problem? **Can alos2App.py process several pairs or only one?**

Data I used: (Only process swath 5)
Reference data folder:
BRS-HH-ALOS2114003150-160703-WBDR1.1__D-F5.jpg
BRS-HV-ALOS2114003150-160703-WBDR1.1__D-F5.jpg
IMG-HH-ALOS2114003150-160703-WBDR1.1__D-F5
IMG-HV-ALOS2114003150-160703-WBDR1.1__D-F5
LED-ALOS2114003150-160703-WBDR1.1__D
TRL-ALOS2114003150-160703-WBDR1.1__D
VOL-ALOS2114003150-160703-WBDR1.1__D
summary.txt
Secondary data folder:
160327:
160508:
BRS-HH-ALOS2105723150-160508-WWDR1.1__D-F5.jpg
BRS-HV-ALOS2105723150-160508-WWDR1.1__D-F5.jpg
IMG-HH-ALOS2105723150-160508-WWDR1.1__D-F5
IMG-HV-ALOS2105723150-160508-WWDR1.1__D-F5
LED-ALOS2105723150-160508-WWDR1.1__D
TRL-ALOS2105723150-160508-WWDR1.1__D
VOL-ALOS2105723150-160508-WWDR1.1__D
summary.txt

Thanks for any help!

**Comment by hillsonghimire** [comment]
I faced similar issue while processing for the WBD mode in `ion-filt` step. 

https://github.com/CunrenLiang/insarzd/issues/2#issue-2005701025

Could you also provide a sample XML configuration file that you used and the command you used to run it so, it could be reproducible?

**Comment by itingwanggeo** [comment]
Hi, here is my input xml configuration file:
![Screenshot from 2024-02-21 16-04-03](https://github.com/isce-framework/isce2/assets/156284577/6412a6cf-8b5f-4a71-884d-7b4bc1f8f2a6)

**Comment by CunrenLiang** [comment]
alos2App.py is designed to process only one pair of images. WWD is rarely used by ALOS-2. In the future, we might add the range band pass filtering capability to support cross WBD-WWD stacks.

For now, you can use alos2App.py to process the stack pair by pair, and use the same geocode bounding box for all pairs. Then you will get a stack of coregistered and geocoded interferograms ready for time series analysis.

**Comment by rtburns-jpl** [comment]
Closing based on CunrenLiang's response.

**Comment by weiyuhang1111** [comment]
Hello, I encountered a similar problem. Did you solve it? Could you please share how you resolved it?
