### ISSUE TITLE
run_07_pairs_misreg ,Bad match at level 1，how to deal it?

### ISSUE THREAD

**Issue by Xious-1314** [isce-framework/isce2#855]
![2024-07-02 11-38-04屏幕截图](https://github.com/isce-framework/isce2/assets/64820267/9105e31c-ade2-441e-b8c3-a4074fc06059)
![2024-07-02 11-36-58屏幕截图](https://github.com/isce-framework/isce2/assets/64820267/2978fceb-5816-4cd3-af1c-bb27aaf0b274)

**Comment by Xious-1314** [comment]
@vincentschut ,hello,can you help me?Thanks!

**Comment by keepfighting666** [comment]
> @vincentschut ,hello,can you help me?Thanks!

Hi, did you fix it? I have the same error with you. And this step takes much time, I have no idea when it can success.

**Comment by david-ncu2019** [comment]
> > @vincentschut ,hello,can you help me?Thanks!
> 
> Hi, did you fix it? I have the same error with you. And this step takes much time, I have no idea when it can success.

I think this is not an error, just a message from the program to show what it is doing now.

I have successfully run all the scripts, and the log file still shows 'Bad match at ...', but it doesn't affect the workflow.

**Comment by Xious-1314** [comment]
> > @vincentschut ,hello,can you help me?Thanks!
> 
> Hi, did you fix it? I have the same error with you. And this step takes much time, I have no idea when it can success.

sorry,i i haven't good methods.

**Comment by EJFielding** [comment]
This is not an error, just a warning that some of the matches were not successful. This happens all very often and can be ignored.

**Comment by Xious-1314** [comment]
> This is not an error, just a warning that some of the matches were not successful. This happens very often and can be ignored.

thanks

**Comment by EJFielding** [comment]
You are welcome. Please close the issue.

**Comment by keepfighting666** [comment]
from this question:https://github.com/isce-framework/isce2/issues/855.
3) can be ignored?
