### ISSUE TITLE
an error in mocompath stage of insarApp.py

### ISSUE THREAD

**Issue by ssharifi1994** [isce-framework/isce2#859]
Hello,

I'm running into the following issue, I'd appreciate any input on what I'm doing wrong. Thank you! --Sohrab

![Screenshot from 2024-07-22 12-27-46](https://github.com/user-attachments/assets/76eb5a7e-a4a7-4448-9d06-4d883b7eb296)

**Comment by EJFielding** [comment]
Hello ssharifi,

The application `insarApp` requires motion compensation components that are not in the GitHub version of ISCE2. You should use the newer `stripmapApp` instead.

**Comment by ssharifi1994** [comment]
Thank you, Eric!
