### ISSUE TITLE
./run_02_unpack_secondary_slc Runtime Taking Too Long

### ISSUE THREAD

**Issue by keepfighting666** [isce-framework/isce2#876]
Hi everyone,

I am experiencing an issue where the ./run_02_unpack_secondary_slc script takes an exceptionally long time to run. My system has sufficient memory, so I am unsure what might be causing this delay.

Has anyone encountered a similar issue or could provide guidance on how to troubleshoot this?
![image](https://github.com/user-attachments/assets/ebc3cbae-456f-4ad9-893f-ed6d725ad27c)

**Comment by zzp1101** [comment]
I'm also having this issue and I'm getting this error all the time, could you please fix it

![Uploading 微信图片_20250108212116.png…]()

**Comment by keepfighting666** [comment]
it already finished actually, you need adjust your parameter, i can't recall it clearly, maybe num_proc?
