### ISSUE TITLE
splitSpectrum.py issue

### ISSUE THREAD

**Issue by weiyuhang1111** [isce-framework/isce2#894]
hello,i am new to use ISCE.
I want to use splitSpectrum.py in ISCE to obtain low-frequency and high-frequency sub-band SLC data. However, I encounter the following error when running the command. Is it an issue with the way I'm using it or with the parameter settings?
unsupported operandtype(s)for +:'NoneType'and 'str
my settings are：
splitSpectrum.py -s 2007/20070715.slc -o TRY/

**Comment by weiyuhang1111** [comment]
it is a easy problem

**Comment by leixiaoyang** [comment]
hello,i am new to use ISCE，too.
I'm now using mintpy to do ionospheric delay correction for a part of the region（Sentinel1A）, and now I need to use isce2 to get the split specturm results , this is my first time I've used mintpy and isce, I'm not very clear about this process.
I try to _use  splitSpectrum.py -s slc -o TRY/_ （_runSplitSpectrum.py_ ）,but my terminal command line shows that the command was not found.Is it a problem with my version?
I would appreciate an answer,thank you.
